---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords: retain transaction log backups 
summary: Le plug-in SnapCenter pour Microsoft SQL Server a besoin de sauvegardes du journal des transactions pour effectuer des opérations de restauration à la minute près, qui restaurent votre base de données à un moment compris entre deux sauvegardes complètes. 
---
= Combien de temps faut-il conserver les sauvegardes du journal des transactions sur le système de stockage source ?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le plug-in SnapCenter pour Microsoft SQL Server a besoin de sauvegardes du journal des transactions pour effectuer des opérations de restauration à la minute près, qui restaurent votre base de données à un moment compris entre deux sauvegardes complètes.

Par exemple, si Plug-in pour SQL Server a effectué une sauvegarde complète à 8h00 et une autre sauvegarde complète à 17h00, il pourrait utiliser la dernière sauvegarde du journal des transactions pour restaurer la base de données à tout moment entre 8h00 et 17h00. Si les journaux des transactions ne sont pas disponibles, Plug-in pour SQL Server peut effectuer uniquement des opérations de restauration à un moment précis, qui restaurent une base de données au moment où Plug-in pour SQL Server a effectué une sauvegarde complète.

En règle générale, vous avez besoin d’opérations de restauration à la minute près pendant seulement un jour ou deux.  Par défaut, SnapCenter conserve un minimum de deux jours.
