---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords: Type of backups 
summary: 'La sauvegarde des bases de données système et utilisateur SQL Server à l"aide de SnapCenter nécessite que vous choisissiez le type de ressource, tel que les bases de données, les instances de serveur SQL et les groupes de disponibilité (AG).  La technologie Snapshot est utilisée pour créer des copies en ligne, en lecture seule, des volumes sur lesquels résident les ressources.' 
---
= Type de sauvegardes prises en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sauvegarde des bases de données système et utilisateur SQL Server à l'aide de SnapCenter nécessite que vous choisissiez le type de ressource, tel que les bases de données, les instances de serveur SQL et les groupes de disponibilité (AG).  La technologie Snapshot est utilisée pour créer des copies en ligne, en lecture seule, des volumes sur lesquels résident les ressources.

Vous pouvez sélectionner l’option de copie uniquement pour spécifier que SQL Server ne tronque pas les journaux de transactions.  Vous devez utiliser cette option lorsque vous gérez également le serveur SQL avec d’autres applications de sauvegarde.  La conservation des journaux de transactions intacts permet à toute application de sauvegarde de restaurer les bases de données système.  Les sauvegardes de copie uniquement sont indépendantes de la séquence de sauvegardes planifiées et n'affectent pas les procédures de sauvegarde et de restauration de la base de données.

|===
| Type de sauvegarde | Description | Option de copie uniquement avec type de sauvegarde 


 a| 
Sauvegarde complète et sauvegarde du journal
 a| 
Sauvegarde la base de données système et tronque les journaux de transactions.

Le serveur SQL tronque les journaux de transactions en supprimant les entrées déjà validées dans la base de données.

Une fois la sauvegarde complète terminée, cette option crée un journal des transactions qui capture les informations de transaction.  En règle générale, vous devriez choisir cette option.  Cependant, si votre temps de sauvegarde est court, vous pouvez choisir de ne pas exécuter une sauvegarde du journal des transactions avec une sauvegarde complète.

Vous ne pouvez pas créer de sauvegarde de journal pour les bases de données système master et msdb.  Cependant, vous pouvez créer des sauvegardes de journaux pour la base de données du système modèle.
 a| 
Sauvegarde les fichiers de la base de données système et les journaux de transactions sans tronquer les journaux.

Une sauvegarde de copie uniquement ne peut pas servir de base différentielle ou de sauvegarde différentielle et n'affecte pas la base différentielle.  La restauration d’une sauvegarde complète de copie uniquement est identique à la restauration de toute autre sauvegarde complète.



 a| 
Sauvegarde complète de la base de données
 a| 
Sauvegarde les fichiers de la base de données système.

Vous pouvez créer une sauvegarde complète de la base de données pour les bases de données maître, modèle et système msdb.
 a| 
Sauvegarde les fichiers de la base de données système.



 a| 
Sauvegarde du journal des transactions
 a| 
Sauvegarde les journaux de transactions tronqués, en copiant uniquement les transactions qui ont été validées depuis la sauvegarde du journal de transactions le plus récent.

Si vous planifiez des sauvegardes fréquentes du journal des transactions parallèlement aux sauvegardes complètes de la base de données, vous pouvez choisir des points de récupération granulaires.
 a| 
Sauvegarde les journaux de transactions sans les tronquer.

Ce type de sauvegarde n’affecte pas le séquençage des sauvegardes de journaux régulières.  Les sauvegardes de journaux en copie uniquement sont utiles pour effectuer des opérations de restauration en ligne.

|===