---
permalink: protect-scsql/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Avant d"ajouter un hôte et d"installer les packages de plug-ins, vous devez remplir toutes les conditions requises.' 
---
= Conditions préalables pour ajouter des hôtes et installer le plug-in SnapCenter pour Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'ajouter un hôte et d'installer les packages de plug-ins, vous devez remplir toutes les conditions requises.

* Si vous utilisez iSCSI, le service iSCSI doit être en cours d’exécution.
* Vous devez disposer d’un utilisateur disposant de privilèges d’administrateur local avec des autorisations de connexion locales sur l’hôte distant.
* Si vous gérez des nœuds de cluster dans SnapCenter, vous devez disposer d'un utilisateur disposant de privilèges administratifs sur tous les nœuds du cluster.
* Vous devez disposer d’un utilisateur avec des autorisations d’administrateur système sur le serveur SQL.
+
Le plug-in SnapCenter pour Microsoft SQL Server utilise Microsoft VDI Framework, qui nécessite un accès administrateur système.

+
https://mskb.pkisolutions.com/kb/2926557["Article de support Microsoft 2926557 : Les opérations de sauvegarde et de restauration de SQL Server VDI nécessitent des privilèges d'administrateur système."]

* Lors de l'installation d'un plug-in sur un hôte Windows, si vous spécifiez des informations d'identification qui ne sont pas intégrées ou si l'utilisateur appartient à un utilisateur de groupe de travail local, vous devez désactiver l'UAC sur l'hôte.
* Si SnapManager pour Microsoft SQL Server est installé, vous devez avoir arrêté ou désactivé le service et les planifications.
+
Si vous prévoyez d'importer des tâches de sauvegarde ou de clonage dans SnapCenter, ne désinstallez pas SnapManager pour Microsoft SQL Server.

* L'hôte doit pouvoir être résolu par le nom de domaine complet (FQDN) du serveur.
+
Si le fichier hosts est modifié pour le rendre résoluble et si le nom court et le FQDN sont tous deux spécifiés dans le fichier hosts, créez une entrée dans le fichier hosts de SnapCenter au format suivant : <adresse_ip> <nom_hôte_complet> <nom_hôte>


