---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords: migrate resources 
summary: 'Après avoir provisionné votre système de stockage NetApp à l"aide du plug-in SnapCenter pour Microsoft Windows, vous pouvez migrer vos ressources vers le système de stockage NetApp ou d"un LUN NetApp vers un autre LUN NetApp à l"aide de l"interface utilisateur graphique (GUI) de SnapCenter ou des applets de commande PowerShell.' 
---
= Migrer les ressources vers le système de stockage NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir provisionné votre système de stockage NetApp à l'aide de SnapCenter Plug-in pour Microsoft Windows, vous pouvez migrer vos ressources vers le système de stockage NetApp ou d'un LUN NetApp vers un autre LUN NetApp à l'aide de l'interface utilisateur graphique (GUI) de SnapCenter ou des applets de commande PowerShell.

.Avant de commencer
* Vous devez avoir ajouté des systèmes de stockage à SnapCenter Server.
* Vous devez avoir actualisé (découvert) les ressources SQL Server.


La plupart des champs de ces pages d’assistant sont explicites.  Les informations suivantes décrivent certains des domaines pour lesquels vous pourriez avoir besoin de conseils.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Ressources*, puis sélectionnez le plug-in approprié dans la liste.
. Dans la page Ressources, sélectionnez *Base de données* ou *Instance* dans la liste déroulante *Affichage*.
. Sélectionnez la base de données ou l’instance dans la liste et cliquez sur *Migrer*.
. Dans la page Ressources, effectuez les actions suivantes :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
*Nom de la base de données* (facultatif)
 a| 
Si vous avez sélectionné une instance pour la migration, vous devez sélectionner les bases de données de cette instance dans la liste déroulante *Bases de données*.



 a| 
*Choisir des destinations*
 a| 
Sélectionnez l’emplacement cible des fichiers de données et journaux.

Les fichiers de données et journaux sont déplacés respectivement vers les dossiers Données et Journal sous le lecteur NetApp sélectionné.  Si un dossier dans la structure de dossiers n’est pas présent, un dossier est créé et la ressource est migrée.



 a| 
*Afficher les détails du fichier de base de données* (facultatif)
 a| 
Sélectionnez cette option lorsque vous souhaitez migrer plusieurs fichiers d’une même base de données.


NOTE: Cette option ne s'affiche pas lorsque vous sélectionnez la ressource *Instance*.



 a| 
*Options*
 a| 
Sélectionnez *Supprimer la copie de la base de données migrée à l'emplacement d'origine* pour supprimer la copie de la base de données de la source.

Facultatif : *EXÉCUTER UPDATE STATISTICS sur les tables avant de détacher la base de données*.

|===
. Dans la page Vérifier, effectuez les actions suivantes :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
*Options de vérification de la cohérence de la base de données*
 a| 
Sélectionnez *Exécuter avant* pour vérifier l’intégrité de la base de données avant la migration.  Sélectionnez *Exécuter après* pour vérifier l’intégrité de la base de données après la migration.



 a| 
*Options DBCC CHECKDB*
 a| 
** Sélectionnez l'option *PHYSICAL_ONLY* pour limiter la vérification d'intégrité à la structure physique de la base de données et pour détecter les pages déchirées, les échecs de somme de contrôle et les pannes matérielles courantes qui ont un impact sur la base de données.
** Sélectionnez l'option *NO_INFOMSGS* pour supprimer tous les messages d'information.
** Sélectionnez l'option *ALL_ERRORMSGS* pour afficher toutes les erreurs signalées par objet.
** Sélectionnez l'option *NOINDEX* si vous ne souhaitez pas vérifier les index non clusterisés.
+
La base de données SQL Server utilise Microsoft SQL Server Database Consistency Checker (DBCC) pour vérifier l'intégrité logique et physique des objets de la base de données.

+

NOTE: Vous souhaiterez peut-être sélectionner cette option pour réduire le temps d'exécution.

** Sélectionnez l'option **TABLOCK** pour limiter les vérifications et obtenir des verrous au lieu d'utiliser un instantané de base de données interne.


|===
. Consultez le résumé, puis cliquez sur **Terminer**.

