---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter utilise des informations d’identification pour authentifier les utilisateurs pour les opérations SnapCenter .  Vous devez créer des informations d’identification pour l’installation des plug-ins SnapCenter et des informations d’identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données ou les systèmes de fichiers Windows. 
---
= Configurer les informations d'identification pour le package de plug-ins SnapCenter pour Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilise des informations d’identification pour authentifier les utilisateurs pour les opérations SnapCenter .  Vous devez créer des informations d’identification pour l’installation des plug-ins SnapCenter et des informations d’identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données ou les systèmes de fichiers Windows.

.Avant de commencer
* Vous devez configurer les informations d’identification Windows avant d’installer les plug-ins.
* Vous devez configurer les informations d’identification avec des privilèges d’administrateur, y compris des droits d’administrateur sur l’hôte distant.
* Authentification SQL sur les hôtes Windows
+
Vous devez configurer les informations d’identification SQL après l’installation des plug-ins.

+
Si vous déployez SnapCenter Plug-in pour Microsoft SQL Server, vous devez configurer les informations d'identification SQL après l'installation des plug-ins.  Configurez des informations d’identification pour un utilisateur disposant d’autorisations d’administrateur système SQL Server.

+
La méthode d’authentification SQL s’authentifie auprès d’une instance SQL Server.  Cela signifie qu'une instance SQL Server doit être découverte dans SnapCenter.  Par conséquent, avant d’ajouter des informations d’identification SQL, vous devez ajouter un hôte, installer des packages de plug-in et actualiser les ressources.  Vous avez besoin de l’authentification SQL Server pour effectuer des opérations telles que la planification ou la découverte de ressources.



.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Informations d'identification*.
. Cliquez sur *Nouveau*.
. Dans la page Informations d’identification, spécifiez les informations requises pour la configuration des informations d’identification :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Nom d'identification
 a| 
Saisissez un nom pour l’identifiant.



 a| 
Nom d'utilisateur/Mot de passe
 a| 
Saisissez le nom d’utilisateur et le mot de passe qui doivent être utilisés pour l’authentification.

** Administrateur de domaine
+
Indiquez l'administrateur du domaine du système sur lequel vous installez le plug-in SnapCenter . Les formats valides pour le champ Nom d'utilisateur sont :

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrateur local (pour les groupes de travail uniquement)
+
Pour les systèmes appartenant à un groupe de travail, spécifiez l'administrateur local intégré du système sur lequel vous installez le plug-in SnapCenter . Vous pouvez spécifier un compte utilisateur local appartenant au groupe des administrateurs locaux si ce compte dispose de privilèges élevés ou si la fonctionnalité de contrôle d'accès utilisateur est désactivée sur le système hôte.  Le format valide pour le champ Nom d'utilisateur est : `UserName`

+
N'utilisez pas de guillemets doubles (") ou de backtick (`) dans les mots de passe.  Vous ne devez pas utiliser les symboles inférieur à (<) et d'exclamation (!) ensemble dans les mots de passe.  Par exemple, lessthan<!10, lessthan10<!, backtick`12.





 a| 
Mode d'authentification
 a| 
Sélectionnez le mode d’authentification que vous souhaitez utiliser.  Si vous sélectionnez le mode d’authentification SQL, vous devez également spécifier l’instance du serveur SQL et l’hôte sur lequel se trouve l’instance SQL.

|===
. Cliquez sur *OK*.


Une fois que vous avez terminé de configurer les informations d’identification, vous souhaiterez peut-être attribuer la maintenance des informations d’identification à un utilisateur ou à un groupe d’utilisateurs dans la page Utilisateur et accès.
