---
permalink: protect-scsql/task_storage_disaster_recovery_for_scsql.html 
sidebar: sidebar 
keywords: disaster recovery 
summary: Vous pouvez récupérer le plug-in SnapCenter pour le stockage SQL Server en activant le mode DR pour le stockage dans la page Paramètres globaux. 
---
= Reprise après sinistre du stockage (DR) pour le plug-in SnapCenter pour SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez récupérer le plug-in SnapCenter pour le stockage SQL Server en activant le mode DR pour le stockage dans la page Paramètres globaux.

.Avant de commencer
* Assurez-vous que les plug-ins sont en mode maintenance.
* Rompre la relation SnapMirror/ SnapVault .link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-950/GUID-8A3F828F-CD3D-48E8-A171-393581FEB2ED.html["Rompre les relations SnapMirror"]
* Connectez le LUN du secondaire à la machine hôte avec la même lettre de lecteur.
* Assurez-vous que tous les disques sont connectés à l’aide des mêmes lettres de lecteur que celles utilisées avant DR.
* Redémarrez le service serveur MSSQL.
* Assurez-vous que les ressources SQL sont de nouveau en ligne.


.À propos de cette tâche
La reprise après sinistre (DR) n'est pas prise en charge sur les configurations VMDK et RDM.

.Étapes
. Dans la page Paramètres, accédez à *Paramètres* > *Paramètres globaux* > *Reprise après sinistre*.
. Sélectionnez *Activer la récupération après sinistre*.
. Cliquez sur *Appliquer*.
. Vérifiez si la tâche DR est activée ou non en cliquant sur *Surveillance* > *Tâches*.


.Après avoir terminé
* Si de nouvelles bases de données sont créées après le basculement, les bases de données seront en mode non DR.
+
Les nouvelles bases de données continueront de fonctionner comme avant le basculement.

* Les nouvelles sauvegardes créées en mode DR seront répertoriées sous SnapMirror ou SnapVault (secondaire) dans la page Topologie.
+
Une icône « i » s'affiche à côté des nouvelles sauvegardes pour indiquer que ces sauvegardes ont été créées pendant le mode DR.

* Vous pouvez supprimer les sauvegardes du plug-in SnapCenter pour SQL Server créées lors du basculement à l'aide de l'interface utilisateur ou de l'applet de commande suivante : `Remove-SmBackup`
* Après le basculement, si vous souhaitez que certaines ressources soient en mode non-DR, utilisez l'applet de commande suivante : `Remove-SmResourceDRMode`
+
Pour plus d'informations, reportez-vous à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .

* SnapCenter Server gère les ressources de stockage individuelles (bases de données SQL) qui sont en mode DR ou non DR, mais pas le groupe de ressources avec des ressources de stockage qui sont en mode DR ou non DR.

