---
permalink: protect-scsql/task_define_a_backup_strategy_for_sql_server_resources.html 
sidebar: sidebar 
keywords: backup strategy 
summary: 'Définir une stratégie de sauvegarde avant de créer vos tâches de sauvegarde permet de garantir que vous disposez des sauvegardes dont vous avez besoin pour restaurer ou cloner avec succès vos bases de données.  Votre contrat de niveau de service (SLA), votre objectif de temps de récupération (RTO) et votre objectif de point de récupération (RPO) déterminent en grande partie votre stratégie de sauvegarde.' 
---
= Définir une stratégie de sauvegarde pour les ressources SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Définir une stratégie de sauvegarde avant de créer vos tâches de sauvegarde permet de garantir que vous disposez des sauvegardes dont vous avez besoin pour restaurer ou cloner avec succès vos bases de données.  Votre contrat de niveau de service (SLA), votre objectif de temps de récupération (RTO) et votre objectif de point de récupération (RPO) déterminent en grande partie votre stratégie de sauvegarde.

Un SLA définit le niveau de service attendu et aborde de nombreux problèmes liés au service, notamment la disponibilité et les performances du service.  Le RTO est le délai dans lequel un processus métier doit être restauré après une interruption de service.  Un RPO définit la stratégie relative à l'âge des fichiers qui doivent être récupérés à partir du stockage de sauvegarde pour que les opérations régulières reprennent après une panne.  Le SLA, le RTO et le RPO contribuent à la stratégie de sauvegarde.
