---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords: clone strategy 
summary: Définir une stratégie de clonage vous permet de cloner votre base de données avec succès. 
---
= Définir une stratégie de clonage pour SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Définir une stratégie de clonage vous permet de cloner votre base de données avec succès.

. Passez en revue les limitations liées aux opérations de clonage.
. Décidez du type de clone dont vous avez besoin.




== Limitations des opérations de clonage

Vous devez être conscient des limites des opérations de clonage avant de cloner les bases de données.

* Si vous utilisez une version d'Oracle comprise entre 11.2.0.4 et 12.1.0.1, l'opération de clonage sera bloquée lorsque vous exécuterez la commande _renamedg_.  Vous pouvez appliquer le correctif Oracle 19544733 pour résoudre ce problème.
* Le clonage de bases de données à partir d'un LUN directement connecté à un hôte (par exemple, à l'aide de Microsoft iSCSI Initiator sur un hôte Windows) vers un LUN VMDK ou RDM sur le même hôte Windows, ou un autre hôte Windows, ou vice versa, n'est pas pris en charge.
* Le répertoire racine du point de montage du volume ne peut pas être un répertoire partagé.
* Si vous déplacez un LUN contenant un clone vers un nouveau volume, le clone ne peut pas être supprimé.




== Types d'opérations de clonage

Vous pouvez utiliser SnapCenter pour cloner une sauvegarde de base de données SQL Server ou une base de données de production.

* Cloner à partir d'une sauvegarde de base de données
+
La base de données clonée peut servir de base de référence pour le développement de nouvelles applications et aider à isoler les erreurs d’application qui se produisent dans l’environnement de production.  La base de données clonée peut également être utilisée pour la récupération d'erreurs de base de données logicielles.

* Cycle de vie du clone
+
Vous pouvez utiliser SnapCenter pour planifier des tâches de clonage récurrentes qui se produiront lorsque la base de données de production n'est pas occupée.


