---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-restore.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, restore 
summary: 'SnapCenter vous permet d"utiliser les variables d"environnement prédéfinies lorsque vous exécutez le prescript et le postscript lors de la restauration d"une base de données.' 
---
= Variables d'environnement prédéfinies pour restaurer des prescripts et postscripts spécifiques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter vous permet d'utiliser les variables d'environnement prédéfinies lorsque vous exécutez le prescript et le postscript lors de la restauration d'une base de données.

*Variables d'environnement prédéfinies prises en charge pour la restauration d'une base de données*

* *SC_JOB_ID* spécifie l'ID de tâche de l'opération.
+
Exemple : 257

* *SC_ORACLE_SID* spécifie l'identifiant système de la base de données.
+
Si l'opération implique plusieurs bases de données, celle-ci contiendra les noms de bases de données séparés par un tube.

+
Exemple : NFSB31

* *SC_HOST* spécifie le nom d'hôte de la base de données.
+
Ce paramètre sera renseigné pour les volumes d’application.

+
Exemple : scsmohost2.gdl.englabe.netapp.com

* *SC_OS_USER* spécifie le propriétaire du système d'exploitation de la base de données.
+
Exemple : oracle

* *SC_OS_GROUP* spécifie le groupe de systèmes d'exploitation de la base de données.
+
Exemple : oinstall

* *SC_BACKUP_NAME* spécifie le nom de la sauvegarde.
+
Ce paramètre sera renseigné pour les volumes d’application.

+
Exemples:

+
** Si la base de données ne fonctionne pas en mode ARCHIVELOG : DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** Si la base de données s'exécute en mode ARCHIVELOG : DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1,RG2_scspr2417819002_07-21-2021_12.16.48.9267_1,RG2_scspr2417819002_07-22-2021_12.16.48.9267_1


* *SC_BACKUP_ID* spécifie l'ID de la sauvegarde.
+
Ce paramètre sera renseigné pour les volumes d’application.

+
Exemples:

+
** Si la base de données ne fonctionne pas en mode ARCHIVELOG : DATA@203|LOG@205
** Si la base de données fonctionne en mode ARCHIVELOG : DATA@203|LOG@205,206,207


* *SC_RESOURCE_GROUP_NAME* spécifie le nom du groupe de ressources.
+
Exemple : RG1

* *SC_ORACLE_HOME* spécifie le chemin du répertoire personnel Oracle.
+
Exemple : /ora01/app/oracle/product/18.1.0/db_1

* *SC_RECOVERY_TYPE* spécifie les fichiers à récupérer ainsi que l'étendue de la récupération.
+
Exemple : RESTORESCOPE : usingBackupControlfile=false|RECOVERYSCOPE : allLogs=true,noLogs=false,untiltime=false,untilscn=false.



Pour plus d'informations sur les délimiteurs, voirlink:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["Délimiteurs pris en charge"^] .
