---
permalink: protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html 
sidebar: sidebar 
keywords: storage types, iSCSI, NFS, RDM, VMDK, NFS, LVM, ASM, SAN filesystem 
summary: 'SnapCenter prend en charge une large gamme de types de stockage sur les machines physiques et virtuelles.  Vous devez vérifier la prise en charge de votre type de stockage avant d"installer le package de plug-ins SnapCenter pour Linux ou le package de plug-ins SnapCenter pour AIX.' 
---
= Types de stockage pris en charge par le plug-in pour Oracle Database
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter prend en charge une large gamme de types de stockage sur les machines physiques et virtuelles.  Vous devez vérifier la prise en charge de votre type de stockage avant d'installer le package de plug-ins SnapCenter pour Linux ou le package de plug-ins SnapCenter pour AIX.

SnapCenter ne prend pas en charge le provisionnement de stockage pour Linux et AIX.



== Types de stockage pris en charge sous Linux

Le tableau suivant répertorie les types de stockage pris en charge sous Linux.

|===
| Machine | Type de stockage 


 a| 
Serveur physique
 a| 
* LUN connectés au FC
* LUN connectés à iSCSI
* Volumes connectés NFS
* NVMe-FC
* NVMe/TCP




 a| 
VMware ESXi
 a| 
* L'analyse des adaptateurs de bus hôte (HBA) peut prendre beaucoup de temps, car SnapCenter analyse tous les adaptateurs de bus hôte présents dans l'hôte.
+
Vous pouvez modifier le fichier *LinuxConfig.pm* situé dans _/opt/ NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ pour définir la valeur du paramètre *SCSI_HOSTS_OPTIMIZED_RESCAN* sur 1 afin de réanalyser uniquement les HBA répertoriés dans HBA_DRIVER_NAMES.

* LUN iSCSI connectés directement au système invité par l'initiateur iSCSI
* VMDK sur les banques de données NFS
* VMDK sur VMFS créés via NVMe/TCP
+

NOTE: RAC est pris en charge sur ESX 8.0U2 qui prend en charge le VMDK partagé

* Volumes NFS connectés directement au système invité
* Banques de données vVol sur NFS et SAN
+
La banque de données vVol ne peut être provisionnée qu'avec ONTAP Tools pour VMware vSphere.



|===


== Types de stockage pris en charge sur AIX

Le tableau suivant répertorie les types de stockage pris en charge sur AIX.

|===
| Machine | Type de stockage 


 a| 
Serveur physique
 a| 
* LUN connectés via FC et iSCSI.
+
Dans un environnement SAN, les systèmes de fichiers ASM, LVM et SAN sont pris en charge.

+

NOTE: NFS sur AIX et le système de fichiers n'est pas pris en charge.

* Système de fichiers journalisé amélioré (JFS2)
+
Prend en charge la journalisation en ligne sur les systèmes de fichiers SAN et la disposition LVM.



|===
Le https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp"] contient les dernières informations sur les versions prises en charge.
