---
permalink: protect-sco/retention-backups.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: Options de conservation des sauvegardes. 
---
= Options de conservation des sauvegardes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez choisir le nombre de jours pendant lesquels conserver les copies de sauvegarde ou spécifier le nombre de copies de sauvegarde que vous souhaitez conserver, jusqu'à un maximum ONTAP de 255 copies.  Par exemple, votre organisation peut exiger que vous conserviez 10 jours de copies de sauvegarde ou 130 copies de sauvegarde.

Lors de la création d’une politique, vous pouvez spécifier les options de conservation pour le type de sauvegarde et le type de planification.

Si vous configurez la réplication SnapMirror , la stratégie de rétention est mise en miroir sur le volume de destination.

SnapCenter supprime les sauvegardes conservées dont les étiquettes de rétention correspondent au type de planification.  Si le type de planification a été modifié pour la ressource ou le groupe de ressources, les sauvegardes avec l'ancienne étiquette de type de planification peuvent toujours rester sur le système.


NOTE: Pour la conservation à long terme des copies de sauvegarde, vous devez utiliser la sauvegarde SnapVault .
