---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: Vous devez définir une stratégie avant de restaurer et de récupérer votre base de données afin de pouvoir effectuer les opérations de restauration et de récupération avec succès. 
---
= Définir une stratégie de restauration et de récupération pour les bases de données Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez définir une stratégie avant de restaurer et de récupérer votre base de données afin de pouvoir effectuer les opérations de restauration et de récupération avec succès.



== Types de sauvegardes prises en charge pour les opérations de restauration et de récupération

SnapCenter prend en charge la restauration et la récupération de différents types de sauvegardes de bases de données Oracle.

* Sauvegarde de données en ligne
* Sauvegarde des données d'arrêt hors ligne
* Sauvegarde des données de montage hors ligne
+

NOTE: Si vous restaurez une sauvegarde de données d'arrêt hors ligne ou de montage hors ligne, SnapCenter laisse la base de données dans un état hors ligne.  Vous devez récupérer manuellement la base de données et réinitialiser les journaux.

* Sauvegarde complète
* Sauvegardes hors ligne des bases de données de secours Data Guard
* Sauvegardes en ligne de données uniquement des bases de données de secours Active Data Guard
+

NOTE: Vous ne pouvez pas effectuer la récupération des bases de données de secours Active Data Guard.

* Sauvegardes de données en ligne, sauvegardes complètes en ligne, sauvegardes de montage hors ligne et sauvegardes d'arrêt hors ligne dans une configuration Real Application Clusters (RAC)
* Sauvegardes de données en ligne, sauvegardes complètes en ligne, sauvegardes de montage hors ligne et sauvegardes d'arrêt hors ligne dans une configuration de gestion automatique du stockage (ASM)




== Types de méthodes de restauration prises en charge pour les bases de données Oracle

SnapCenter prend en charge la connexion et la copie ou la restauration sur place pour les bases de données Oracle.  Lors d'une opération de restauration, SnapCenter détermine la méthode de restauration appropriée au système de fichiers à utiliser pour la restauration sans aucune perte de données.


NOTE: SnapCenter ne prend pas en charge SnapRestore basé sur le volume.



=== Restauration par connexion et copie

Si la disposition de la base de données diffère de la sauvegarde ou s'il existe de nouveaux fichiers après la création de la sauvegarde, une restauration par connexion et copie est effectuée.  Dans la méthode de restauration par connexion et copie, les tâches suivantes sont effectuées :

*Mesures*

. Le volume est cloné à partir du snapshot et la pile du système de fichiers est construite sur l'hôte à l'aide des LUN ou des volumes clonés.
. Les fichiers sont copiés des systèmes de fichiers clonés vers les systèmes de fichiers d'origine.
. Les systèmes de fichiers clonés sont ensuite démontés de l'hôte et les volumes clonés sont supprimés d' ONTAP.



NOTE: Pour une configuration Flex ASM (où la cardinalité est inférieure au nombre de nœuds dans le cluster RAC) ou des bases de données ASM RAC sur VMDK ou RDM, seule la méthode de restauration par connexion et copie est prise en charge.

Même si vous avez activé de force la restauration sur place, SnapCenter effectue une restauration par connexion et copie dans les scénarios suivants :

* Restaurer à partir du système de stockage secondaire
* Restauration des groupes de disques ASM présents sur les nœuds d'une configuration Oracle RAC sur lesquels l'instance de base de données n'est pas configurée
* Dans la configuration d'Oracle RAC, sur l'un des nœuds homologues si l'instance ASM ou l'instance de cluster n'est pas en cours d'exécution ou si le nœud homologue est en panne
* Restauration des fichiers de contrôle uniquement
* Restaurer un sous-ensemble d'espaces table résidant sur un groupe de disques ASM
* Le groupe de disques est partagé entre les fichiers de données, le fichier sp et le fichier de mots de passe
* Le service SnapCenter Plug-in Loader (SPL) n'est pas installé ou n'est pas en cours d'exécution sur le nœud distant dans un environnement RAC
* De nouveaux nœuds sont ajoutés à Oracle RAC et le serveur SnapCenter n'est pas conscient des nœuds nouvellement ajoutés




=== Restauration sur place

Si la disposition de la base de données est similaire à la sauvegarde et n'a subi aucune modification de configuration sur la pile de stockage et de base de données, une restauration sur place est effectuée, dans laquelle la restauration du fichier ou du LUN est effectuée sur ONTAP.  SnapCenter prend uniquement en charge Single File SnapRestore (SFSR) dans le cadre de la méthode de restauration sur place.


NOTE: NetApp ONTAP prend en charge la restauration sur place à partir d'un emplacement secondaire.

Si vous souhaitez effectuer une restauration sur place sur la base de données, assurez-vous que vous n'avez que des fichiers de données sur le groupe de disques ASM.  Vous devez créer une sauvegarde après toute modification apportée au groupe de disques ASM ou à la structure physique de la base de données.  Après avoir effectué une restauration sur place, le groupe de disques contiendra le même nombre de fichiers de données qu'au moment de la sauvegarde.

La restauration sur place sera appliquée automatiquement lorsque le groupe de disques ou le point de montage correspond aux critères suivants :

* Aucun nouveau fichier de données n'est ajouté après la sauvegarde (vérification des fichiers étrangers)
* Aucun ajout, suppression ou recréation de disque ASM ou de LUN après la sauvegarde (vérification des modifications structurelles du groupe de disques ASM)
* Aucun ajout, suppression ou recréation de LUN dans le groupe de disques LVM (vérification des modifications structurelles du groupe de disques LVM)



NOTE: Vous pouvez également activer de force la restauration sur place à l’aide de l’interface graphique utilisateur, de l’interface de ligne de commande SnapCenter ou de l’applet de commande PowerShell pour remplacer la vérification des fichiers étrangers et la vérification des modifications structurelles du groupe de disques LVM.



==== Exécution d'une restauration sur place sur ASM RAC

Dans SnapCenter, le nœud sur lequel vous effectuez la restauration est appelé nœud principal et tous les autres nœuds du RAC sur lesquels réside le groupe de disques ASM sont appelés nœuds homologues.  SnapCenter modifie l'état du groupe de disques ASM pour le démonter sur tous les nœuds où le groupe de disques ASM est dans l'état de montage avant d'effectuer l'opération de restauration de stockage.  Une fois la restauration du stockage terminée, SnapCenter modifie l’état du groupe de disques ASM tel qu’il était avant l’opération de restauration.

Dans les environnements SAN, SnapCenter supprime les périphériques de tous les nœuds homologues et exécute l'opération de démappage LUN avant l'opération de restauration du stockage.  Après l'opération de restauration du stockage, SnapCenter exécute l'opération de mappage LUN et construit des périphériques sur tous les nœuds homologues.  Dans un environnement SAN, si la disposition Oracle RAC ASM réside sur des LUN, lors de la restauration, SnapCenter exécute des opérations de démappage de LUN, de restauration de LUN et de mappage de LUN sur tous les nœuds du cluster RAC où réside le groupe de disques ASM.  Avant la restauration, même si tous les initiateurs des nœuds RAC n'ont pas été utilisés pour les LUN, après la restauration, SnapCenter crée un nouvel iGroup avec tous les initiateurs de tous les nœuds RAC.

* En cas d'échec lors de l'activité de pré-restauration sur les nœuds homologues, SnapCenter restaure automatiquement l'état du groupe de disques ASM tel qu'il était avant d'effectuer la restauration sur les nœuds homologues sur lesquels l'opération de pré-restauration a réussi.  La restauration n'est pas prise en charge pour le nœud principal et le nœud homologue sur lesquels l'opération a échoué.  Avant de tenter une autre restauration, vous devez résoudre manuellement le problème sur le nœud homologue et ramener le groupe de disques ASM sur le nœud principal à l'état de montage.
* En cas d'échec lors de l'activité de restauration, l'opération de restauration échoue et aucune restauration n'est effectuée.  Avant de tenter une autre restauration, vous devez résoudre manuellement le problème de restauration du stockage et ramener le groupe de disques ASM sur le nœud principal à l'état de montage.
* En cas d'échec lors de l'activité post-restauration sur l'un des nœuds homologues, SnapCenter poursuit l'opération de restauration sur les autres nœuds homologues.  Vous devez résoudre manuellement le problème de post-restauration sur le nœud homologue.




== Types d'opérations de restauration pris en charge pour les bases de données Oracle

SnapCenter vous permet d'effectuer différents types d'opérations de restauration pour les bases de données Oracle.

Avant de restaurer la base de données, les sauvegardes sont validées pour identifier si des fichiers manquent par rapport aux fichiers de base de données réels.



=== Restauration complète

* Restaure uniquement les fichiers de données
* Restaure uniquement les fichiers de contrôle
* Restaure les fichiers de données et les fichiers de contrôle
* Restaure les fichiers de données, les fichiers de contrôle et les fichiers journaux de rétablissement dans les bases de données de secours Data Guard et Active Data Guard




=== Restauration partielle

* Restaure uniquement les tablespaces sélectionnés
* Restaure uniquement les bases de données enfichables (PDB) sélectionnées
* Restaure uniquement les tablespaces sélectionnés d'un PDB




== Types d'opérations de récupération prises en charge pour les bases de données Oracle

SnapCenter vous permet d'effectuer différents types d'opérations de récupération pour les bases de données Oracle.

* La base de données jusqu'à la dernière transaction (tous les journaux)
* La base de données jusqu'à un numéro de changement de système spécifique (SCN)
* La base de données jusqu'à une date et une heure spécifiques
+
Vous devez spécifier la date et l'heure de récupération en fonction du fuseau horaire de l'hôte de la base de données.

+
SnapCenter fournit également l'option Aucune récupération pour les bases de données Oracle.




NOTE: Le plug-in pour la base de données Oracle ne prend pas en charge la récupération si vous avez effectué une restauration à l'aide d'une sauvegarde créée avec le rôle de base de données de secours.  Vous devez toujours effectuer une récupération manuelle pour les bases de données de secours physiques.



== Limitations liées à la restauration et à la récupération des bases de données Oracle

Avant d’effectuer des opérations de restauration et de récupération, vous devez connaître les limitations.

Si vous utilisez une version d'Oracle comprise entre 11.2.0.4 et 12.1.0.1, l'opération de restauration sera bloquée lorsque vous exécuterez la commande _renamedg_.  Vous pouvez appliquer le correctif Oracle 19544733 pour résoudre ce problème.

Les opérations de restauration et de récupération suivantes ne sont pas prises en charge :

* Restauration et récupération des tablespaces de la base de données conteneur racine (CDB)
* Restauration des tablespaces temporaires et des tablespaces temporaires associés aux PDB
* Restauration et récupération d'espaces table à partir de plusieurs PDB simultanément
* Restauration des sauvegardes de journaux
* Restauration des sauvegardes vers un emplacement différent
* Restauration des fichiers journaux de rétablissement dans toute configuration autre que les bases de données de secours Data Guard ou Active Data Guard
* Restauration du fichier SPFILE et du fichier de mots de passe
* Lorsque vous effectuez une opération de restauration sur une base de données qui a été recréée à l'aide du nom de base de données préexistant sur le même hôte, qui était gérée par SnapCenter et qui disposait de sauvegardes valides, l'opération de restauration écrase les fichiers de base de données nouvellement créés même si les DBID sont différents.
+
Cela peut être évité en effectuant l’une des actions suivantes :

+
** Découvrir les ressources SnapCenter après la recréation de la base de données
** Créer une sauvegarde de la base de données recréée






== Limitations liées à la récupération ponctuelle des tablespaces

* La récupération ponctuelle (PITR) des espaces table SYSTEM, SYSAUX et UNDO n'est pas prise en charge
* La restauration PITR des tablespaces ne peut pas être effectuée avec d'autres types de restauration.
* Si un tablespace est renommé et que vous souhaitez le récupérer à un point antérieur à son changement de nom, vous devez spécifier le nom antérieur du tablespace.
* Si les contraintes des tables d'un tablespace sont contenues dans un autre tablespace, vous devez récupérer les deux tablespaces.
* Si une table et ses index sont stockés dans des tablespaces différents, les index doivent être supprimés avant d'effectuer PITR
* PITR ne peut pas être utilisé pour récupérer l'espace table par défaut actuel
* PITR ne peut pas être utilisé pour récupérer des tablespaces contenant l'un des objets suivants :
+
** Objets avec des objets sous-jacents (tels que des vues matérialisées) ou des objets contenus (tels que des tables partitionnées), sauf si tous les objets sous-jacents ou contenus se trouvent dans l'ensemble de récupération
+
De plus, si les partitions d'une table partitionnée sont stockées dans des espaces table différents, vous devez soit supprimer la table avant d'exécuter PITR, soit déplacer toutes les partitions vers le même espace table avant d'exécuter PITR.

** Annuler ou restaurer des segments
** Files d'attente avancées compatibles Oracle 8 avec plusieurs destinataires
** Objets appartenant à l'utilisateur SYS
+
Des exemples de ces types d'objets sont PL/SQL, les classes Java, les programmes d'appel, les vues, les synonymes, les utilisateurs, les privilèges, les dimensions, les répertoires et les séquences.







== Sources et destinations pour la restauration des bases de données Oracle

Vous pouvez restaurer une base de données Oracle à partir d'une copie de sauvegarde sur un stockage principal ou secondaire.  Vous ne pouvez restaurer des bases de données qu'au même emplacement sur la même instance de base de données.  Cependant, dans la configuration Real Application Cluster (RAC), vous pouvez restaurer des bases de données sur d'autres nœuds.



=== Sources pour les opérations de restauration

Vous pouvez restaurer des bases de données à partir d’une sauvegarde sur un stockage principal ou secondaire.  Si vous souhaitez restaurer à partir d'une sauvegarde sur le stockage secondaire dans une configuration à miroirs multiples, vous pouvez sélectionner le miroir de stockage secondaire comme source.



=== Destinations pour les opérations de restauration

Vous ne pouvez restaurer des bases de données qu'au même emplacement sur la même instance de base de données.

Dans une configuration RAC, vous pouvez restaurer les bases de données RAC à partir de n’importe quel nœud du cluster.
