---
permalink: protect-sce/concept_requirements_for_restoring_an_exchange_database.html 
sidebar: sidebar 
keywords: restoring an Exchange database 
summary: 'Avant de restaurer une base de données Exchange Server à partir d"une sauvegarde SnapCenter Plug-in pour Microsoft Exchange Server, vous devez vous assurer que plusieurs exigences sont remplies.' 
---
= Conditions requises pour la restauration d'une base de données Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de restaurer une base de données Exchange Server à partir d'une sauvegarde SnapCenter Plug-in pour Microsoft Exchange Server, vous devez vous assurer que plusieurs exigences sont remplies.


NOTE: Pour utiliser pleinement la fonctionnalité de restauration, vous devez mettre à niveau SnapCenter Server et SnapCenter Plug-in pour la base de données Exchange vers la version 4.6.

* Le serveur Exchange doit être en ligne et en cours d’exécution avant de pouvoir restaurer une base de données.
* Les bases de données doivent exister sur le serveur Exchange.
+

NOTE: La restauration des bases de données supprimées n'est pas prise en charge.

* Les planifications SnapCenter pour la base de données doivent être suspendues.
* Le serveur SnapCenter et l'hôte SnapCenter Plug-in pour Microsoft Exchange Server doivent être connectés au stockage principal et secondaire contenant les sauvegardes que vous souhaitez restaurer.

