---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html 
sidebar: sidebar 
keywords: SMBR, Single Mailbox recovery, Exchange database 
summary: 'Le logiciel Single Mailbox Recovery (SMBR) vous permet de restaurer et de récupérer des e-mails ou des boîtes aux lettres au lieu de la base de données Exchange complète.' 
---
= Récupération granulaire des courriers et des boîtes aux lettres
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le logiciel Single Mailbox Recovery (SMBR) vous permet de restaurer et de récupérer des e-mails ou des boîtes aux lettres au lieu de la base de données Exchange complète.

Restaurer une base de données complète juste pour récupérer un seul courrier consommera beaucoup de temps et de ressources.  SMBR aide à récupérer rapidement les courriers en créant une copie clonée du snapshot, puis en utilisant les API Microsoft pour monter la boîte aux lettres dans SMBR.  Pour plus d'informations sur l'utilisation de SMBR, voir https://docs.netapp.com/p/snap/smbr/8.3/Administrative-Server-Administration-Guide.pdf["Guide d'administration SMBR"^] .

Pour plus d'informations sur SMBR, reportez-vous aux éléments suivants :

* https://kb.netapp.com/Legacy/SMBR/How_to_manually_restore_a_single_item_with_SMBR["Comment restaurer manuellement un seul élément avec SMBR (également applicable aux restaurations Ontrack Power Control)"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Single_Mailbox_Recovery_(SMBR)/How_to_restore_from_secondary_storage_in_SMBR_with_SnapCenter["Comment restaurer à partir d'un stockage secondaire dans SMBR avec SnapCenter"^]
* https://www.youtube.com/watch?v=wMSo049rREY&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg&index=3["Récupération de courrier Microsoft Exchange depuis SnapVault à l'aide de SMBR"^]

