---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: SnapCenter utilise des informations d’identification pour authentifier les utilisateurs pour les opérations SnapCenter .  Vous devez créer des informations d’identification pour l’installation du package de plug-in et des informations d’identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données. 
---
= Configurer les informations d'identification pour le plug-in SnapCenter pour Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilise des informations d’identification pour authentifier les utilisateurs pour les opérations SnapCenter .  Vous devez créer des informations d’identification pour l’installation du package de plug-in et des informations d’identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données.

.À propos de cette tâche
Vous devez configurer les informations d’identification pour l’installation des plug-ins sur les hôtes Windows.  Bien que vous puissiez créer des informations d’identification pour Windows après avoir déployé des hôtes et installé des plug-ins, la meilleure pratique consiste à créer des informations d’identification après avoir ajouté des SVM, avant de déployer des hôtes et d’installer des plug-ins.

Configurez les informations d’identification avec des privilèges d’administrateur, y compris les droits d’administrateur sur l’hôte distant.

Si vous configurez des informations d'identification pour des groupes de ressources individuels et que le nom d'utilisateur ne dispose pas de privilèges d'administrateur complets, vous devez attribuer au moins les privilèges de groupe de ressources et de sauvegarde au nom d'utilisateur.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Informations d'identification*.
. Cliquez sur *Nouveau*.
+
La fenêtre d'informations d'identification s'affiche.

. Dans la page Informations d’identification, procédez comme suit :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Nom d'identification
 a| 
Saisissez un nom pour l’identifiant.



 a| 
Nom d'utilisateur
 a| 
Saisissez le nom d'utilisateur utilisé pour l'authentification.

** Administrateur de domaine ou tout membre du groupe d'administrateurs
+
Indiquez l'administrateur du domaine ou tout membre du groupe d'administrateurs du système sur lequel vous installez le plug-in SnapCenter . Les formats valides pour le champ Nom d'utilisateur sont :

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Administrateur local (pour les groupes de travail uniquement)
+
Pour les systèmes appartenant à un groupe de travail, spécifiez l'administrateur local intégré du système sur lequel vous installez le plug-in SnapCenter . Vous pouvez spécifier un compte utilisateur local appartenant au groupe des administrateurs locaux si ce compte dispose de privilèges élevés ou si la fonctionnalité de contrôle d'accès utilisateur est désactivée sur le système hôte.  Le format valide pour le champ Nom d'utilisateur est : `UserName`





 a| 
Mot de passe
 a| 
Entrez le mot de passe utilisé pour l'authentification.



 a| 
Authentification
 a| 
Sélectionnez Windows comme mode d’authentification.

|===
. Cliquez sur *OK*.

