---
permalink: protect-sce/task_add_hosts_and_install_plug_in_for_exchange.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server, NET TCP 
summary: 'Vous pouvez utiliser la page SnapCenterAjouter un hôte pour ajouter des hôtes Windows.  Le plug-in pour Exchange est automatiquement installé sur l"hôte spécifié.  Il s’agit de la méthode recommandée pour l’installation des plug-ins.  Vous pouvez ajouter un hôte et installer un plug-in pour un hôte individuel ou un cluster.' 
---
= Ajouter des hôtes et installer le plug-in pour Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la page Ajouter un hôte de SnapCenter pour ajouter des hôtes Windows.  Le plug-in pour Exchange est automatiquement installé sur l'hôte spécifié.  Il s’agit de la méthode recommandée pour l’installation des plug-ins.  Vous pouvez ajouter un hôte et installer un plug-in pour un hôte individuel ou un cluster.

.Avant de commencer
* Si le système d'exploitation de l'hôte SnapCenter Server est Windows 2019 et que le système d'exploitation de l'hôte du plug-in est Windows 2022, vous devez effectuer les opérations suivantes :
+
** Mise à niveau vers Windows Server 2019 (build du système d'exploitation 17763.5936) ou version ultérieure
** Mise à niveau vers Windows Server 2022 (build du système d'exploitation 20348.2402) ou version ultérieure


* Vous devez être un utilisateur affecté à un rôle disposant des autorisations d'installation et de désinstallation du plug-in, tel que l'administrateur SnapCenter .
* Lors de l'installation d'un plug-in sur un hôte Windows, si vous spécifiez des informations d'identification qui ne sont pas intégrées ou si l'utilisateur appartient à un utilisateur de groupe de travail local, vous devez désactiver l'UAC sur l'hôte.
* Le service de mise en file d'attente des messages doit être en cours d'exécution.
* Si vous utilisez un compte de service géré de groupe (gMSA), vous devez configurer gMSA avec des privilèges administratifs. Pour plus d'informations, voirlink:task_configure_gMSA_on_windows_server_2012_or_later.html["Configurer un compte de service géré de groupe sur Windows Server 2016 ou version ultérieure pour Microsoft Exchange Server"^] .


.À propos de cette tâche
* Vous ne pouvez pas ajouter un serveur SnapCenter en tant qu’hôte de plug-in à un autre serveur SnapCenter .
* Vous pouvez ajouter un hôte et installer des packages de plug-ins pour un hôte individuel ou un cluster.
* Si un nœud d'échange fait partie d'un DAG, vous ne pouvez pas ajouter un seul nœud au serveur SnapCenter .
* Si vous installez des plug-ins sur un cluster (Exchange DAG), ils sont installés sur tous les nœuds du cluster même si certains nœuds ne disposent pas de bases de données sur les LUN NetApp .


À partir de SnapCenter 4.6, SCE prend en charge la multilocation et vous pouvez ajouter un hôte à l'aide des méthodes suivantes :

|===
| Ajouter une opération hôte | 4.5 et versions antérieures | 4.6 et versions ultérieures 


| Ajouter un DAG sans IP dans un domaine croisé ou différent | Non pris en charge | Soutenu 


| Ajoutez plusieurs DAG IP avec des noms uniques, résidant dans le même domaine ou dans plusieurs domaines | Soutenu | Soutenu 


| Ajoutez plusieurs DAG IP ou sans IP qui ont les mêmes noms d'hôte et/ou nom de base de données dans un domaine croisé | Non pris en charge | Soutenu 


| Ajoutez plusieurs DAG IP/sans IP avec le même nom et inter-domaines | Non pris en charge | Soutenu 


| Ajoutez plusieurs hôtes autonomes avec le même nom et le même domaine | Non pris en charge | Soutenu 
|===
Le plug-in pour Exchange dépend du package de plug-ins SnapCenter pour Windows et les versions doivent être identiques.  Lors de l'installation du plug-in pour Exchange, le package de plug-ins SnapCenter pour Windows est sélectionné par défaut et installé avec le fournisseur de matériel VSS.

Si SnapManager pour Microsoft Exchange Server et SnapDrive pour Windows sont déjà installés et que vous souhaitez installer Plug-in pour Exchange sur le même serveur Exchange, vous devez désinscrire le fournisseur de matériel VSS utilisé par SnapDrive pour Windows car il est incompatible avec le fournisseur de matériel VSS installé avec Plug-in pour Exchange et le package de plug-ins SnapCenter pour Windows. Pour plus d'informations, consultez la section  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_manually_register_the_Data_ONTAP_VSS_Hardware_Provider["Comment enregistrer manuellement le fournisseur de matériel Data ONTAP VSS"] .

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Hôtes*.
. Vérifiez que *Hôtes gérés* est sélectionné en haut.
. Cliquez sur *Ajouter*.
. Dans la page Hôtes, procédez comme suit :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Type d'hôte
 a| 
Sélectionnez *Windows* comme type d’hôte.

SnapCenter Server ajoute l'hôte, puis installe sur l'hôte le plug-in pour Windows et le plug-in pour Exchange s'ils ne sont pas déjà installés.

Le plug-in pour Windows et le plug-in pour Exchange doivent être de la même version.  Si une version différente de Plug-in pour Windows a été précédemment installée, SnapCenter met à jour la version dans le cadre de l'installation.



 a| 
Nom d'hôte
 a| 
Saisissez le nom de domaine complet (FQDN) ou l'adresse IP de l'hôte.

SnapCenter dépend de la configuration appropriée du DNS.  Par conséquent, la meilleure pratique consiste à saisir le nom de domaine complet (FQDN).

Une adresse IP est prise en charge pour les hôtes de domaine non approuvés uniquement si elle correspond au nom de domaine complet.

Si vous ajoutez un hôte à l’aide de SnapCenter et qu’il fait partie d’un sous-domaine, vous devez fournir le nom de domaine complet.

Vous pouvez saisir les adresses IP ou le FQDN de l’un des éléments suivants :

** Hôte autonome
** Échange DAG
+
Pour un DAG Exchange, vous pouvez :

+
*** Ajoutez un DAG en fournissant le nom du DAG, l’adresse IP du DAG, le nom du nœud ou l’adresse IP du nœud.
*** Ajoutez le cluster DAG sans IP en fournissant l’adresse IP ou le nom de domaine complet de l’un des nœuds du cluster DAG.
*** Ajoutez un DAG sans IP qui réside dans le même domaine ou dans un domaine différent.  Vous pouvez également ajouter plusieurs DAG IP/IP sans DAG avec le même nom mais des domaines différents.





NOTE: Pour un hôte autonome ou un DAG Exchange (inter-domaine ou même domaine), il est recommandé de fournir le FQDN ou l'adresse IP de l'hôte ou du DAG.



 a| 
Informations d'identification
 a| 
Sélectionnez le nom des informations d’identification que vous avez créées ou créez les nouvelles informations d’identification.

L'identifiant doit disposer de droits administratifs sur l'hôte distant.  Pour plus de détails, consultez les informations sur la création d'informations d'identification.

Vous pouvez afficher les détails des informations d’identification en positionnant votre curseur sur le nom des informations d’identification que vous avez spécifié.


NOTE: Le mode d’authentification des informations d’identification est déterminé par le type d’hôte que vous spécifiez dans l’assistant Ajouter un hôte.

|===
. Dans la section Sélectionner les plug-ins à installer, sélectionnez les plug-ins à installer.
+
Lorsque vous sélectionnez Plug-in pour Exchange, SnapCenter Plug-in pour Microsoft SQL Server est automatiquement désélectionné.  Microsoft recommande de ne pas installer SQL Server et Exchange Server sur le même système en raison de la quantité de mémoire utilisée et de l’utilisation d’autres ressources requises par Exchange.

. (Facultatif) Cliquez sur *Plus d'options*.
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Port
 a| 
Conservez le numéro de port par défaut ou spécifiez le numéro de port.

Le numéro de port par défaut est 8145.  Si le serveur SnapCenter a été installé sur un port personnalisé, ce numéro de port sera affiché comme port par défaut.


NOTE: Si vous avez installé manuellement les plug-ins et spécifié un port personnalisé, vous devez spécifier le même port.  Sinon, l’opération échoue.



 a| 
Chemin d'installation
 a| 
Le chemin par défaut est `C:\Program Files\NetApp\SnapCenter` .

Vous pouvez éventuellement personnaliser le chemin.



 a| 
Ajouter tous les hôtes dans le DAG
 a| 
Cochez cette case lorsque vous ajoutez un DAG.



 a| 
Ignorer les vérifications de préinstallation
 a| 
Cochez cette case si vous avez déjà installé les plug-ins manuellement et que vous ne souhaitez pas valider si l'hôte répond aux exigences d'installation du plug-in.



 a| 
Utiliser un compte de service géré de groupe (gMSA) pour exécuter les services du plug-in
 a| 
Cochez cette case si vous souhaitez utiliser un compte de service géré de groupe (gMSA) pour exécuter les services de plug-in.

Fournissez le nom gMSA au format suivant : _domainName\accountName$_.


NOTE: gMSA sera utilisé comme compte de service de connexion uniquement pour le service SnapCenter Plug-in pour Windows.

|===
. Cliquez sur *Soumettre*.
+
Si vous n'avez pas coché la case « Ignorer les pré-vérifications », l'hôte est validé afin de déterminer s'il remplit les conditions requises pour l'installation du plug-in. Si la configuration minimale requise n'est pas respectée, les messages d'erreur ou d'avertissement appropriés s'affichent.

+
Si l'erreur est liée à l'espace disque ou à la RAM, vous pouvez mettre à jour le fichier web.config situé à l'adresse `C:\Program Files\NetApp\SnapCenter` WebApp pour modifier les valeurs par défaut.  Si l’erreur est liée à d’autres paramètres, vous devez résoudre le problème.

+

NOTE: Dans une configuration HA, si vous mettez à jour le fichier web.config, vous devez mettre à jour le fichier sur les deux nœuds.

. Surveiller la progression de l'installation.




== Configurer un port personnalisé pour la communication NET TCP

Par défaut, à partir de la version SnapCenter 6.0, le plug-in SnapCenter pour Windows utilise le port 909 pour la communication NET TCP.  Si le port 909 est utilisé, vous pouvez configurer un autre port pour la communication NET TCP.

.Étapes
. Modifiez la valeur de la clé _NetTCPPort_ située dans _C:\Program Files\ NetApp\ SnapCenter\ SnapCenter Plug-in for Microsoft Windows\vssproviders\navssprv.exe.config_ avec le numéro de port requis.
`<add key="NetTCPPort" value="new_port_number" />`
. Modifiez la valeur de la clé _NetTCPPort_ située dans _C:\Program Files\ NetApp\ SnapCenter\ SnapCenter Plug-in for Microsoft Windows\SnapDriveService.dll.config_ avec le numéro de port requis.
`<add key="NetTCPPort" value="new_port_number" />`
. Désenregistrez le service _Data ONTAP VSS Hardware Provider_ en exécutant la commande ci-dessous :
`"C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\navssprv.exe" -r service -u`
+
Vérifiez que le service n’est pas affiché dans la liste des services dans _services.msc_.

. Enregistrez le service _Data ONTAP VSS Hardware Provider_ en exécutant la commande ci-dessous :
`"C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\vssproviders\navssprv.exe" -r service -a ".\LocalSystem"``
+
Vérifiez si le service est désormais affiché dans la liste des services dans _services.msc_.

. Redémarrez le service _Plug-in pour Windows_.

