---
permalink: protect-sce/task_install_plug_in_for_exchange_from_the_snapcenter_server_host_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 'Vous devez installer le plug-in pour Exchange à partir de l"interface graphique SnapCenter .  Si vous ne souhaitez pas utiliser l’interface graphique, vous pouvez utiliser les applets de commande PowerShell sur l’hôte SnapCenter Server ou sur un hôte distant.' 
---
= Installer le plug-in pour Exchange à partir de l'hôte SnapCenter Server à l'aide des applets de commande PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez installer le plug-in pour Exchange à partir de l'interface graphique SnapCenter .  Si vous ne souhaitez pas utiliser l’interface graphique, vous pouvez utiliser les applets de commande PowerShell sur l’hôte SnapCenter Server ou sur un hôte distant.

.Avant de commencer
* SnapCenter Server doit avoir été installé et configuré.
* Vous devez être un administrateur local sur l’hôte ou un utilisateur avec des privilèges administratifs.
* Vous devez être un utilisateur affecté à un rôle disposant des autorisations de plug-in, d'installation et de désinstallation, comme l'administrateur SnapCenter .
* Vous devez avoir examiné les exigences d’installation et les types de configurations prises en charge avant d’installer le plug-in pour Exchange.
* L’hôte sur lequel vous souhaitez installer le plug-in pour Exchange doit être un hôte Windows.


.Étapes
. Sur l’hôte SnapCenter Server, établissez une session à l’aide de l’applet de commande _Open-SmConnection_, puis entrez vos informations d’identification.
. Ajoutez l’hôte sur lequel vous souhaitez installer le plug-in pour Exchange à l’aide de l’applet de commande _Add-SmHost_ avec les paramètres requis.
+
Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .

+
L'hôte peut être un hôte autonome ou un DAG.  Si vous spécifiez un DAG, le paramètre _-IsDAG_ est obligatoire.

. Installez le plug-in pour Exchange à l’aide de l’applet de commande _Install-SmHostPackage_ avec les paramètres requis.
+
Cette commande installe le plug-in pour Exchange sur l'hôte spécifié, puis enregistre le plug-in auprès de SnapCenter.


