---
permalink: protect-sce/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_exchange_database.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Vous devez créer une connexion à une machine virtuelle de stockage (SVM) et des informations d’identification avant d’utiliser les applets de commande PowerShell pour la sauvegarde et la restauration.' 
---
= Créer une connexion au système de stockage et des informations d'identification à l'aide des applets de commande PowerShell pour Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer une connexion à une machine virtuelle de stockage (SVM) et des informations d’identification avant d’utiliser les applets de commande PowerShell pour la sauvegarde et la restauration.

.Avant de commencer
* Vous devez avoir préparé l’environnement PowerShell pour exécuter les applets de commande PowerShell.
* Vous devez disposer des autorisations requises dans le rôle d’administrateur d’infrastructure pour créer des connexions de stockage.
* Vous devez vous assurer que les installations de plug-ins ne sont pas en cours.
+
Les installations de plug-ins hôtes ne doivent pas être en cours lors de l'ajout d'une connexion au système de stockage, car le cache hôte peut ne pas être mis à jour et l'état des bases de données peut s'afficher dans l'interface graphique SnapCenter comme « Non disponible pour la sauvegarde » ou « Pas sur le stockage NetApp ».

* Les noms des systèmes de stockage doivent être uniques.
+
SnapCenter ne prend pas en charge plusieurs systèmes de stockage portant le même nom sur différents clusters.  Chaque système de stockage pris en charge par SnapCenter doit avoir un nom unique et une adresse IP LIF de données unique.



.Étapes
. Lancez une session de connexion PowerShell en utilisant le `Open-SmConnection` applet de commande.
+
Cet exemple ouvre une session PowerShell :

+
[listing]
----
PS C:\> Open-SmConnection
----
. Créez une nouvelle connexion au système de stockage en utilisant le `Add-SmStorageConnection` applet de commande.
+
Cet exemple crée une nouvelle connexion au système de stockage :

+
[listing]
----
PS C:\> Add-SmStorageConnection -SVM test_vs1 -Protocol Https
-Timeout 60
----
. Créez un nouveau compte Exécuter en tant que en utilisant le `Add-Credential` applet de commande.
+
Cet exemple crée un nouveau compte Exécuter en tant que nommé ExchangeAdmin avec les informations d'identification Windows :

+
[listing]
----
PS C:> Add-SmCredential -Name ExchangeAdmin -AuthMode Windows
-Credential sddev\administrator
----


Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .
