---
permalink: protect-sce/task_reseed_a_passive_exchange_node_replica.html 
sidebar: sidebar 
keywords:  
summary: 'Si vous devez réamorcer une copie de réplique, par exemple lorsqu"une copie est corrompue, vous pouvez réamorcer la dernière sauvegarde à l"aide de la fonction de réamorcer dans SnapCenter.' 
---
= Réensemencer une réplique de nœud Exchange passive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous devez réamorcer une copie de réplique, par exemple lorsqu'une copie est corrompue, vous pouvez réamorcer la dernière sauvegarde à l'aide de la fonction de réamorcer dans SnapCenter.

.Avant de commencer
Vous devez avoir créé une sauvegarde de la base de données que vous souhaitez réensemencer.

+ Pour éviter les décalages entre les nœuds, vous pouvez soit créer une nouvelle sauvegarde avant d'effectuer une opération de réamorçage, soit choisir l'hôte avec la dernière sauvegarde.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Ressources*, puis sélectionnez *Plug-in Microsoft Exchange Server* dans la liste.
. Dans la page Ressources, sélectionnez l’option appropriée dans la liste Affichage :
+
|===
| Option | Description 


 a| 
Pour réensemencer une seule base de données
 a| 
Sélectionnez *Base de données* dans la liste Affichage.



 a| 
Pour réensemencer les bases de données dans un DAG
 a| 
Sélectionnez *Groupe de disponibilité de la base de données* dans la liste Affichage.

|===
. Sélectionnez la ressource que vous souhaitez réensemencer.
. Dans la page Gérer les copies, cliquez sur *Réamorcer*.
. Dans la liste des copies de bases de données défectueuses de l'assistant de réamorçage, sélectionnez celle que vous souhaitez réamorcer, puis cliquez sur *Suivant*.
. Dans la fenêtre Hôte, sélectionnez l'hôte avec la sauvegarde à partir de laquelle vous souhaitez réamorcer, puis cliquez sur *Suivant*.
. Dans la page Notification, dans la liste déroulante *Préférence de courrier électronique*, sélectionnez les scénarios dans lesquels vous souhaitez envoyer les courriers électroniques.
+
Vous devez également spécifier les adresses e-mail de l'expéditeur et du destinataire, ainsi que l'objet de l'e-mail.

. Consultez le résumé, puis cliquez sur *Terminer*.
. Vous pouvez afficher l’état du travail en développant le panneau Activité en bas de la page.
+

NOTE: L'opération de réamorçage n'est pas prise en charge si la copie passive de la base de données réside sur un stockage non NetApp .


