---
permalink: protect-scw/reference_prepare_storage_system_for_snapmirror_and_snapvault.html 
sidebar: sidebar 
keywords: requirements 
summary: 'Vous pouvez utiliser un plug-in SnapCenter avec la technologie ONTAP SnapMirror pour créer des copies miroir de jeux de sauvegarde sur un autre volume et avec la technologie ONTAP SnapVault pour effectuer une réplication de sauvegarde de disque à disque à des fins de conformité aux normes et à d"autres fins liées à la gouvernance.  Avant d’effectuer ces tâches, vous devez configurer une relation de protection des données entre les volumes source et de destination et initialiser la relation.' 
---
= Préparer les systèmes de stockage pour la réplication SnapMirror et SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser un plug-in SnapCenter avec la technologie ONTAP SnapMirror pour créer des copies miroir de jeux de sauvegarde sur un autre volume et avec la technologie ONTAP SnapVault pour effectuer une réplication de sauvegarde de disque à disque à des fins de conformité aux normes et à d'autres fins liées à la gouvernance.  Avant d’effectuer ces tâches, vous devez configurer une relation de protection des données entre les volumes source et de destination et initialiser la relation.

SnapCenter exécute les mises à jour de SnapMirror et SnapVault une fois l'opération Snapshot terminée. Les mises à jour de SnapMirror et SnapVault sont effectuées dans le cadre du travail SnapCenter . Si vous utilisez la synchronisation active SnapMirror , utilisez les planifications SnapMirror ou SnapVault par défaut pour la synchronisation active SnapMirror et les relations asynchrones.


NOTE: Si vous accédez à SnapCenter à partir d'un produit NetApp SnapManager et que vous êtes satisfait des relations de protection des données que vous avez configurées, vous pouvez ignorer cette section.

Une relation de protection des données réplique les données du stockage principal (le volume source) vers le stockage secondaire (le volume de destination).  Lorsque vous initialisez la relation, ONTAP transfère les blocs de données référencés sur le volume source vers le volume de destination.


NOTE: SnapCenter ne prend pas en charge les relations en cascade entre les volumes SnapMirror et SnapVault (*Primaire* > *Miroir* > *Vault*).  Vous devez utiliser des relations en éventail.

SnapCenter prend en charge la gestion des relations SnapMirror flexibles en termes de version.  Pour plus de détails sur les relations SnapMirror flexibles en fonction des versions et sur la façon de les configurer, consultez le http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.ic-base%2Fresources%2Fhome.html["Documentation ONTAP"^] .
