---
permalink: protect-scw/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: 'Vous devez créer une connexion à une machine virtuelle de stockage (SVM) et des informations d’identification avant d’utiliser les applets de commande PowerShell pour effectuer des opérations de protection des données.' 
---
= Créer une connexion au système de stockage et des informations d'identification à l'aide des applets de commande PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer une connexion à une machine virtuelle de stockage (SVM) et des informations d’identification avant d’utiliser les applets de commande PowerShell pour effectuer des opérations de protection des données.

.Avant de commencer
* Vous devez avoir préparé l’environnement PowerShell pour exécuter les applets de commande PowerShell.
* Vous devez disposer des autorisations requises dans le rôle d’administrateur d’infrastructure pour créer des connexions de stockage.
* Vous devez vous assurer que les installations de plug-ins ne sont pas en cours.
+
Les installations de plug-ins hôtes ne doivent pas être en cours lors de l'ajout d'une connexion au système de stockage, car le cache hôte peut ne pas être mis à jour et l'état des bases de données peut s'afficher dans l'interface graphique SnapCenter comme « Non disponible pour la sauvegarde » ou « Pas sur le stockage NetApp ».

* Les noms des systèmes de stockage doivent être uniques.
+
SnapCenter ne prend pas en charge plusieurs systèmes de stockage portant le même nom sur différents clusters.  Chaque système de stockage pris en charge par SnapCenter doit avoir un nom unique et une adresse IP LIF de gestion unique.



.Étapes
. Lancez une session de connexion PowerShell Core à l’aide de l’applet de commande Open-SmConnection.
+
Cet exemple ouvre une session PowerShell :

+
[listing]
----
PS C:\> Open-SmConnection
----
. Créez une nouvelle connexion au système de stockage à l’aide de l’applet de commande Add-SmStorageConnection.
+
Cet exemple crée une nouvelle connexion au système de stockage :

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Créez de nouvelles informations d’identification à l’aide de l’applet de commande Add-SmCredential.
+
Cet exemple crée une nouvelle information d’identification nommée FinanceAdmin avec les informations d’identification Windows :

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .
