---
permalink: protect-scw/task_install_the_snapcenter_plug_in_for_windows_silently_from_the_command_line.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: 'Vous pouvez installer le plug-in SnapCenter pour Microsoft Windows localement sur un hôte Windows si vous ne parvenez pas à installer le plug-in à distance à partir de l"interface graphique SnapCenter .  Vous pouvez exécuter le programme d’installation du plug-in SnapCenter pour Microsoft Windows sans surveillance, en mode silencieux, à partir de la ligne de commande Windows.' 
---
= Installez le plug-in SnapCenter pour Microsoft Windows en mode silencieux à partir de la ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez installer le plug-in SnapCenter pour Microsoft Windows localement sur un hôte Windows si vous ne parvenez pas à installer le plug-in à distance à partir de l'interface graphique SnapCenter .  Vous pouvez exécuter le programme d’installation du plug-in SnapCenter pour Microsoft Windows sans surveillance, en mode silencieux, à partir de la ligne de commande Windows.

.Avant de commencer
* Vous devez avoir installé le bundle d'hébergement ASP.NET Core Runtime 8.0.12 (et tous les correctifs 8.0.x ultérieurs).
* Vous devez avoir installé PowerShell 7.4.2 ou une version ultérieure.
* Vous devez être un administrateur local sur l'hôte.


.Étapes
. Téléchargez le plug-in SnapCenter pour Microsoft Windows à partir de votre emplacement d’installation.
+
Par exemple, le chemin d'installation par défaut est C:\ProgramData\ NetApp\ SnapCenter\Package Repository.

+
Ce chemin est accessible depuis l’hôte sur lequel le serveur SnapCenter est installé.

. Copiez le fichier d’installation sur l’hôte sur lequel vous souhaitez installer le plug-in.
. À partir de l’invite de commande, accédez au répertoire dans lequel vous avez téléchargé le fichier d’installation.
. Saisissez la commande suivante en remplaçant les variables par vos données :
+
`"snapcenter_windows_host_plugin.exe"/silent / debuglog"" /log"" BI_SNAPCENTER_PORT= SUITE_INSTALLDIR="" BI_SERVICEACCOUNT= BI_SERVICEPWD= ISFeatureInstall=SCW`

+
Par exemple:

+
 `"C:\ProgramData\NetApp\SnapCenter\Package Repository \snapcenter_windows_host_plugin.exe"/silent /debuglog"C: \HPPW_SCW_Install.log" /log"C:\" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C: \Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW`
+

NOTE: Tous les paramètres transmis lors de l'installation du Plug-in pour Windows sont sensibles à la casse.

+
Saisissez les valeurs des variables suivantes :

+
|===
| Variable | Valeur 


 a| 
_/debuglog"<Chemin_du_journal_de_débogage>_
 a| 
Spécifiez le nom et l'emplacement du fichier journal du programme d'installation de la suite, comme dans l'exemple suivant : Setup.exe /debuglog"C:\PathToLog\setupexe.log".



 a| 
BI_SNAPCENTER_PORT
 a| 
Spécifiez le port sur lequel SnapCenter communique avec SMCore.



 a| 
SUITE_INSTALLDIR
 a| 
Spécifiez le répertoire d'installation du package du plug-in hôte.



 a| 
BI_SERVICEACCOUNT
 a| 
Spécifiez le plug-in SnapCenter pour le compte de service Web Microsoft Windows.



 a| 
BI_SERVICEPWD
 a| 
Spécifiez le mot de passe du compte de service Web SnapCenter Plug-in pour Microsoft Windows.



 a| 
Installation de la fonctionnalité ISFeature
 a| 
Spécifiez la solution à déployer par SnapCenter sur l'hôte distant.

|===
+
Le paramètre _debuglog_ inclut le chemin du fichier journal pour SnapCenter.  L'écriture dans ce fichier journal est la méthode préférée pour obtenir des informations de dépannage, car le fichier contient les résultats des vérifications effectuées par l'installation pour les prérequis du plug-in.

+
Si nécessaire, vous pouvez trouver des informations de dépannage supplémentaires dans le fichier journal du package SnapCenter pour Windows.  Les fichiers journaux du package sont répertoriés (du plus ancien au plus ancien) dans le dossier _%Temp%_, par exemple, _C:\temp\_.

+

NOTE: L'installation du plug-in pour Windows enregistre le plug-in sur l'hôte et non sur le serveur SnapCenter .  Vous pouvez enregistrer le plug-in sur le serveur SnapCenter en ajoutant l’hôte à l’aide de l’interface graphique SnapCenter ou de l’applet de commande PowerShell.  Une fois l’hôte ajouté, le plug-in est automatiquement découvert.


