---
permalink: protect-scw/task_add_hosts_and_install_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: installing 
summary: 'Vous pouvez utiliser la page Ajouter un hôte de SnapCenter pour ajouter des hôtes Windows.  Le plug-in SnapCenter pour Microsoft Windows est automatiquement installé sur l"hôte spécifié.  Il s’agit de la méthode recommandée pour l’installation des plug-ins.  Vous pouvez ajouter un hôte et installer un plug-in pour un hôte individuel ou un cluster.' 
---
= Ajoutez des hôtes et installez le plug-in SnapCenter pour Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la page Ajouter un hôte de SnapCenter pour ajouter des hôtes Windows.  Le plug-in SnapCenter pour Microsoft Windows est automatiquement installé sur l'hôte spécifié.  Il s’agit de la méthode recommandée pour l’installation des plug-ins.  Vous pouvez ajouter un hôte et installer un plug-in pour un hôte individuel ou un cluster.

.Avant de commencer
* Si le système d'exploitation de l'hôte SnapCenter Server est Windows 2019 et que le système d'exploitation de l'hôte du plug-in est Windows 2022, vous devez effectuer les opérations suivantes :
+
** Mise à niveau vers Windows Server 2019 (build du système d'exploitation 17763.5936) ou version ultérieure
** Mise à niveau vers Windows Server 2022 (build du système d'exploitation 20348.2402) ou version ultérieure


* Vous devez être un utilisateur affecté à un rôle disposant des autorisations d'installation et de désinstallation de plug-in, tel que le rôle Administrateur SnapCenter .
* Lors de l'installation d'un plug-in sur un hôte Windows, si vous spécifiez des informations d'identification qui ne sont pas intégrées ou si l'utilisateur appartient à un utilisateur de groupe de travail local, vous devez désactiver l'UAC sur l'hôte.
* L'utilisateur SnapCenter doit être ajouté au rôle « Se connecter en tant que service » du serveur Windows.
* Vous devez vous assurer que le service de mise en file d'attente des messages est en cours d'exécution.
* Si vous utilisez un compte de service géré de groupe (gMSA), vous devez configurer gMSA avec des privilèges administratifs.
+
link:task_configure_gMSA_on_windows_server_2012_or_later.html["Configurer un compte de service géré de groupe sur Windows Server 2016 ou version ultérieure pour le système de fichiers Windows"]



.À propos de cette tâche
* Vous ne pouvez pas ajouter un serveur SnapCenter en tant qu’hôte de plug-in à un autre serveur SnapCenter .
* Plugins Windows
+
** Microsoft Windows
** Serveur Microsoft Exchange
** Microsoft SQL Server
** SAP HANA


* Installation de plug-ins sur un cluster
+
Si vous installez des plug-ins sur un cluster (WSFC, Oracle RAC ou Exchange DAG), ils sont installés sur tous les nœuds du cluster.

* Stockage de la série E
+
Vous ne pouvez pas installer le plug-in pour Windows sur un hôte Windows connecté au stockage de la série E.




NOTE: SnapCenter ne prend pas en charge l'ajout du même hôte (hôte plug-in) à SnapCenter si l'hôte fait déjà partie d'un groupe de travail et a été modifié vers un autre domaine ou vice versa.  Si vous souhaitez ajouter le même hôte, vous devez supprimer l’hôte de SnapCenter et l’ajouter à nouveau.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Hôtes*.
. Assurez-vous que *Hôtes gérés* est sélectionné en haut.
. Cliquez sur *Ajouter*.
. Dans la page Hôtes, procédez comme suit :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Type d'hôte
 a| 
Sélectionnez le type d'hôte *Windows*.

SnapCenter Server ajoute l'hôte, puis installe le plug-in pour Windows s'il n'est pas déjà installé sur l'hôte.



 a| 
Nom d'hôte
 a| 
Saisissez le nom de domaine complet (FQDN) ou l'adresse IP de l'hôte.

SnapCenter dépend de la configuration appropriée du DNS.  Par conséquent, la meilleure pratique consiste à saisir le nom de domaine complet (FQDN).

Vous pouvez saisir les adresses IP ou le FQDN de l'un des éléments suivants :

** Hôte autonome
** Clustering de basculement Windows Server (WSFC)
+
Si vous ajoutez un hôte à l’aide de SnapCenter et qu’il fait partie d’un sous-domaine, vous devez fournir le nom de domaine complet.





 a| 
Informations d'identification
 a| 
Sélectionnez le nom des informations d’identification que vous avez créées ou créez les nouvelles informations d’identification.

L'identifiant doit disposer de droits administratifs sur l'hôte distant.  Pour plus de détails, consultez les informations sur la création d'informations d'identification.

Les détails sur les informations d'identification, y compris le nom d'utilisateur, le domaine et le type d'hôte, s'affichent en plaçant votre curseur sur le nom d'informations d'identification que vous avez fourni.


NOTE: Le mode d’authentification est déterminé par le type d’hôte que vous spécifiez dans l’assistant Ajouter un hôte.

|===
. Dans la section Sélectionner les plug-ins à installer, sélectionnez les plug-ins à installer.
+
Pour les nouveaux déploiements, aucun package de plug-in n'est répertorié.

. (Facultatif) Cliquez sur *Plus d'options*.
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Port
 a| 
Conservez le numéro de port par défaut ou spécifiez le numéro de port.

Le numéro de port par défaut est 8145.  Si le serveur SnapCenter a été installé sur un port personnalisé, ce numéro de port sera affiché comme port par défaut.


NOTE: Si vous avez installé manuellement les plug-ins et spécifié un port personnalisé, vous devez spécifier le même port.  Sinon, l’opération échoue.



 a| 
Chemin d'installation
 a| 
Le chemin par défaut est C:\Program Files\ NetApp\ SnapCenter.

Vous pouvez éventuellement personnaliser le chemin.  Pour le package de plug-ins SnapCenter pour Windows, le chemin par défaut est C:\Program Files\ NetApp\ SnapCenter.  Cependant, si vous le souhaitez, vous pouvez personnaliser le chemin par défaut.



 a| 
Ajouter tous les hôtes du cluster
 a| 
Cochez cette case pour ajouter tous les nœuds de cluster dans un WSFC.



 a| 
Ignorer les vérifications de préinstallation
 a| 
Cochez cette case si vous avez déjà installé les plug-ins manuellement et que vous ne souhaitez pas valider si l'hôte répond aux exigences d'installation du plug-in.



 a| 
Utiliser un compte de service géré de groupe (gMSA) pour exécuter les services du plug-in
 a| 
Cochez cette case si vous souhaitez utiliser un compte de service géré de groupe (gMSA) pour exécuter les services de plug-in.

Fournissez le nom gMSA au format suivant : _domainName\accountName$_.


NOTE: gMSA sera utilisé comme compte de service de connexion uniquement pour le service SnapCenter Plug-in pour Windows.

|===
. Cliquez sur *Soumettre*.
+
Si vous n'avez pas coché la case « Ignorer les pré-vérifications », l'hôte est validé afin de vérifier s'il répond aux exigences d'installation du plug-in. L'espace disque, la RAM, la version de PowerShell, la version .NET et l'emplacement sont vérifiés par rapport aux exigences minimales.  Si les exigences minimales ne sont pas respectées, des messages d’erreur ou d’avertissement appropriés s’affichent.

+
Si l'erreur est liée à l'espace disque ou à la RAM, vous pouvez mettre à jour le fichier web.config situé à l'adresse `C:\Program Files\NetApp\SnapCenter` WebApp pour modifier les valeurs par défaut.  Si l’erreur est liée à d’autres paramètres, vous devez résoudre le problème.

+

NOTE: Dans une configuration HA, si vous mettez à jour le fichier web.config, vous devez mettre à jour le fichier sur les deux nœuds.

. Surveiller la progression de l'installation.

