---
permalink: protect-scw/task_determine_resource_availability_for_windows_file_systems.html 
sidebar: sidebar 
keywords: availability 
summary: 'Les ressources sont les LUN et les composants similaires de votre système de fichiers qui sont gérés par les plug-ins que vous avez installés.  Vous pouvez ajouter ces ressources à des groupes de ressources afin de pouvoir effectuer des tâches de protection des données sur plusieurs ressources, mais vous devez d"abord identifier les ressources dont vous disposez.  La découverte des ressources disponibles vérifie également que l’installation du plug-in a été effectuée avec succès.' 
---
= Déterminer la disponibilité des ressources pour les systèmes de fichiers Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les ressources sont les LUN et les composants similaires de votre système de fichiers qui sont gérés par les plug-ins que vous avez installés.  Vous pouvez ajouter ces ressources à des groupes de ressources afin de pouvoir effectuer des tâches de protection des données sur plusieurs ressources, mais vous devez d'abord identifier les ressources dont vous disposez.  La découverte des ressources disponibles vérifie également que l’installation du plug-in a été effectuée avec succès.

.Avant de commencer
* Vous devez déjà avoir effectué des tâches telles que l’installation de SnapCenter Server, l’ajout d’hôtes, la création de connexions à une machine virtuelle de stockage (SVM) et l’ajout d’informations d’identification.
* Si les fichiers résident sur des LUN VMware RDM ou des VMDK, vous devez déployer le SnapCenter Plug-in for VMware vSphere et enregistrer le plug-in auprès de SnapCenter. Pour plus d'informations, consultez la section  https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["Documentation du SnapCenter Plug-in for VMware vSphere"^] .


.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Ressources*, puis sélectionnez le plug-in approprié dans la liste.
. Dans la page Ressources, sélectionnez *Systèmes de fichiers* dans la liste.
. Sélectionnez l'hôte pour filtrer la liste des ressources, puis cliquez sur *Actualiser les ressources*.
+
Les systèmes de fichiers nouvellement ajoutés, renommés ou supprimés sont mis à jour dans l'inventaire du serveur SnapCenter .

+

IMPORTANT: Vous devez actualiser les ressources si les bases de données sont renommées en dehors de SnapCenter.


