---
permalink: upgrade/task_configure_snapcenter_to_check_for_available_updates.html 
sidebar: sidebar 
keywords: configure, snapcenter server, updates, software updates 
summary: 'SnapCenter communique périodiquement avec le site de support NetApp pour vous informer des mises à jour logicielles disponibles.  Vous pouvez également créer un calendrier pour spécifier l"intervalle dans lequel vous souhaitez recevoir des informations sur les mises à jour disponibles.' 
---
= Configurer SnapCenter pour vérifier les mises à jour disponibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter communique périodiquement avec le site de support NetApp pour vous informer des mises à jour logicielles disponibles.  Vous pouvez également créer un calendrier pour spécifier l'intervalle dans lequel vous souhaitez recevoir des informations sur les mises à jour disponibles.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page *Paramètres*, cliquez sur *Logiciel*.
+
La page Logiciels disponibles affiche les packages de plug-ins disponibles, les versions disponibles et leur état d'installation.

. Cliquez sur *Vérifier les mises à jour* pour voir si des versions plus récentes des packages de plug-ins sont disponibles.
. Cliquez sur *Planifier les mises à jour* pour créer une planification afin de spécifier l'intervalle dans lequel vous souhaitez recevoir des informations sur les mises à jour disponibles :
+
.. Sélectionnez l'intervalle dans *Vérifier les mises à jour*.
.. Sélectionnez les informations d'identification Windows de l'administrateur du serveur SnapCenter et cliquez sur *OK*.



