---
permalink: protect-hana/reference_types_of_restore_strategies_supported_for_auto_discovered_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Databases 
summary: 'Vous devez définir une stratégie avant de pouvoir effectuer avec succès des opérations de restauration à l"aide de SnapCenter.  Il existe deux types de stratégies de restauration pour les bases de données SAP HANA découvertes automatiquement.' 
---
= Types de stratégies de restauration prises en charge pour les bases de données SAP HANA découvertes automatiquement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez définir une stratégie avant de pouvoir effectuer avec succès des opérations de restauration à l'aide de SnapCenter.  Il existe deux types de stratégies de restauration pour les bases de données SAP HANA découvertes automatiquement.



== Restauration complète des ressources

* Restaure tous les volumes, qtrees et LUN d'une ressource
+
** L'option *Rétablir le volume* doit être sélectionnée pour restaurer l'intégralité du volume.
+

NOTE: Si la ressource contient des volumes ou des qtrees, les instantanés pris après l'instantané sélectionné pour la restauration sur ces volumes ou qtrees sont supprimés et ne peuvent pas être récupérés.  De plus, si une autre ressource est hébergée sur les mêmes volumes ou qtrees, cette ressource est également supprimée.







== Base de données des locataires

* Restaure la base de données du locataire


Si l'option *Base de données des locataires* est sélectionnée, les scripts de récupération HANA Studio ou HANA externes à SnapCenter doivent être utilisés pour effectuer l'opération de récupération.
