---
permalink: protect-hana/reference_prerequisites_for_using_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: Credentials,SnapCenter Plug-in for SAP HANA Database 
summary: 'Avant d"utiliser SnapCenter Plug-in pour SAP HANA Database, l"administrateur SnapCenter doit installer et configurer le serveur SnapCenter et effectuer les tâches préalables.' 
---
= Conditions préalables à l'utilisation du plug-in SnapCenter pour la base de données SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser SnapCenter Plug-in pour SAP HANA Database, l'administrateur SnapCenter doit installer et configurer le serveur SnapCenter et effectuer les tâches préalables.

* Installer et configurer SnapCenter Server.
* Connectez-vous au serveur SnapCenter .
* Configurez l’environnement SnapCenter en ajoutant des connexions au système de stockage et en créant des informations d’identification, le cas échéant.
* Installez Java 11 sur votre hôte Linux ou Windows.
+
Vous devez définir le chemin Java dans la variable de chemin d’environnement de la machine hôte.

* Configurez SnapMirror et SnapVault si vous souhaitez une réplication de sauvegarde.
* Installez le client HDBSQL sur l’hôte où vous installerez le plug-in pour la base de données SAP HANA.
+
Configurez les clés du magasin d’utilisateurs pour les nœuds SAP HANA que vous gérerez via cet hôte.

* Pour la base de données SAP HANA 2.0 SPS05, si vous utilisez un compte utilisateur de base de données SAP HANA, assurez-vous que vous disposez des autorisations suivantes pour effectuer des opérations de sauvegarde, de restauration et de clonage dans SnapCenter Server :
+
** Administrateur de sauvegarde
** Catalogue lu
** Administrateur de sauvegarde de base de données
** Opérateur de récupération de base de données



