---
permalink: protect-hana/reference_host_requirements_to_install_snapcenter_plug_in_package_for_windows_hana.html 
sidebar: sidebar 
keywords: SAP HANA, plug-ins 
summary: 'Avant d"installer le package de plug-ins SnapCenter pour Windows, vous devez vous familiariser avec certaines exigences de base en matière d"espace et de taille du système hôte.' 
---
= Configuration requise pour l'installation du package de plug-ins SnapCenter pour Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer le package de plug-ins SnapCenter pour Windows, vous devez vous familiariser avec certaines exigences de base en matière d'espace et de taille du système hôte.

|===
| Article | Exigences 


 a| 
Systèmes d'exploitation
 a| 
Microsoft Windows

Pour obtenir les dernières informations sur les versions prises en charge, consultez le https://imt.netapp.com/imt/imt.jsp?components=134502;&solution=1258&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp"^] .



 a| 
RAM minimale pour le plug-in SnapCenter sur l'hôte
 a| 
1 Go



 a| 
Espace minimum d'installation et de journalisation pour le plug-in SnapCenter sur l'hôte
 a| 
5 Go


NOTE: Vous devez allouer suffisamment d’espace disque et surveiller la consommation de stockage par le dossier des journaux.  L'espace journal requis varie en fonction du nombre d'entités à protéger et de la fréquence des opérations de protection des données.  S'il n'y a pas suffisamment d'espace disque, les journaux ne seront pas créés pour les opérations récemment exécutées.



 a| 
Logiciels requis
 a| 
* Pack d'hébergement ASP.NET Core Runtime 8.0.12 (et tous les correctifs 8.0.x ultérieurs)
* PowerShell Core 7.4.2
* Java 11 Oracle Java et OpenJDK
+
Java 11 Oracle Java et OpenJDK sont requis uniquement pour SAP HANA, IBM Db2, PostgreSQL, MySQL, les plug-ins pris en charge par NetApp et d'autres applications personnalisées qui peuvent être installées sur l'hôte Windows.



Pour obtenir les dernières informations sur les versions prises en charge, consultez le https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp"^] .

Pour obtenir des informations de dépannage spécifiques à .NET, consultez https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["La mise à niveau ou l’installation de SnapCenter échoue pour les systèmes hérités qui ne disposent pas de connectivité Internet."]

|===