---
permalink: protect-hana/task_prepare_multitenant_database_containers_for_data_protection.html 
sidebar: sidebar 
keywords: multitenant database containers 
summary: 'Pour les hôtes SAP HANA directement enregistrés dans SnapCenter, l"installation ou la mise à niveau du plug-in SnapCenter pour la base de données SAP HANA déclenchera une découverte automatique des ressources sur l"hôte.  Après l"installation ou la mise à niveau du plug-in, pour chaque ressource de conteneur de base de données multilocataire (MDC) située sur l"hôte du plug-in, une autre ressource MDC sera automatiquement découverte avec un format GUID différent et enregistrée dans SnapCenter.  La nouvelle ressource sera dans l’état « verrouillé ».' 
---
= Préparer des conteneurs de bases de données multilocataires pour la protection des données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour les hôtes SAP HANA directement enregistrés dans SnapCenter, l'installation ou la mise à niveau du plug-in SnapCenter pour la base de données SAP HANA déclenchera une découverte automatique des ressources sur l'hôte.  Après l'installation ou la mise à niveau du plug-in, pour chaque ressource de conteneur de base de données multilocataire (MDC) située sur l'hôte du plug-in, une autre ressource MDC sera automatiquement découverte avec un format GUID différent et enregistrée dans SnapCenter.  La nouvelle ressource sera dans l'état « verrouillé ».

.À propos de cette tâche
Par exemple, dans SnapCenter 4.2, si la ressource E90 MDC était située sur l'hôte du plug-in et enregistrée manuellement, après la mise à niveau vers SnapCenter 4.3, une autre ressource E90 MDC avec un GUID différent sera découverte et enregistrée dans SnapCenter.


NOTE: Les sauvegardes associées à la ressource de SnapCenter 4.2 et des versions antérieures doivent être conservées jusqu'à l'expiration de la période de conservation.  Une fois la période de conservation expirée, vous pouvez supprimer l’ancienne ressource MDC et continuer à gérer la nouvelle ressource MDC découverte automatiquement.

`Old MDC resource`est la ressource MDC pour un hôte de plug-in qui a été ajouté manuellement dans SnapCenter 4.2 ou les versions antérieures.

Procédez comme suit pour commencer à utiliser la nouvelle ressource découverte dans SnapCenter 4.3 pour les opérations de protection des données :

.Étapes
. Dans la page Ressources, sélectionnez l'ancienne ressource MDC avec les sauvegardes ajoutées à la version antérieure de SnapCenter et placez-la en « mode maintenance » à partir de la page Topologie.
+
Si la ressource fait partie d'un groupe de ressources, placez le groupe de ressources en « mode maintenance ».

. Configurez la nouvelle ressource MDC découverte après la mise à niveau vers SnapCenter 4.3 en sélectionnant la nouvelle ressource sur la page Ressources.
+
« Nouvelle ressource MDC » est la ressource MDC nouvellement découverte une fois que le serveur SnapCenter et l'hôte du plug-in ont été mis à niveau vers la version 4.3.  La nouvelle ressource MDC peut être identifiée comme une ressource avec le même SID que l'ancienne ressource MDC, pour un hôte donné, et avec une icône de cadenas rouge à côté d'elle dans la page Ressources.

. Protégez la nouvelle ressource MDC découverte après la mise à niveau vers SnapCenter 4.3 en sélectionnant des stratégies de protection, des planifications et des paramètres de notification.
. Supprimez les sauvegardes effectuées dans SnapCenter 4.2 ou les versions antérieures en fonction des paramètres de conservation.
. Supprimez le groupe de ressources de la page Topologie.
. Supprimez l’ancienne ressource MDC de la page Ressources.
+
Par exemple, si la période de conservation des snapshots principaux est de 7 jours et celle des snapshots secondaires de 45 jours, une fois les 45 jours écoulés et toutes les sauvegardes supprimées, vous devez supprimer le groupe de ressources et l'ancienne ressource MDC.



.Informations connexes
link:task_configure_hdb_user_store_key_and_hdbsql_os_user_for_the_sap_hana_database.html["Configurer la clé du magasin d'utilisateurs HDB et l'utilisateur du système d'exploitation HDBSQL pour la base de données SAP HANA"]

link:task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Afficher les sauvegardes et les clones de la base de données SAP HANA dans la page Topologie"]
