---
permalink: sc-automation/task_how to_access_rest_apis_using_the_swagger_api_web_page.html 
sidebar: sidebar 
keywords: REST API, Swagger 
summary: 'Les API REST sont exposées via la page Web Swagger.  Vous pouvez accéder à la page Web Swagger pour afficher les API REST de SnapCenter Server, ainsi que pour émettre manuellement un appel d"API.  Vous pouvez utiliser les API REST pour vous aider à gérer votre serveur SnapCenter ou pour effectuer des opérations de protection des données.' 
---
= Comment accéder aux API REST à l'aide de la page Web de l'API Swagger
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les API REST sont exposées via la page Web Swagger.  Vous pouvez accéder à la page Web Swagger pour afficher les API REST de SnapCenter Server, ainsi que pour émettre manuellement un appel d'API.  Vous pouvez utiliser les API REST pour vous aider à gérer votre serveur SnapCenter ou pour effectuer des opérations de protection des données.

Vous devez connaître l’adresse IP de gestion ou le nom de domaine du serveur SnapCenter sur lequel vous souhaitez exécuter les API REST.

Vous n’avez pas besoin d’autorisations spéciales pour exécuter le client REST API.  Tout utilisateur peut accéder à la page Web Swagger.  Les autorisations respectives sur les objets accessibles via l'API REST sont basées sur l'utilisateur qui génère le jeton pour se connecter à l'API REST.

.Étapes
. À partir d'un navigateur, saisissez l'URL pour accéder à la page Web Swagger au format _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/swagger/_.
+

NOTE: Assurez-vous que l'URL de l'API REST ne contient pas les caractères suivants : +, ., %, et &.

. Dans le champ *Swagger Explore*, si la documentation de l'API Swagger ne s'affiche pas automatiquement, saisissez : _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/Content/swagger/ SnapCenter.yaml_
. Cliquez sur *Explorer*.
+
Une liste de types ou de catégories de ressources API s'affiche.

. Cliquez sur un type de ressource API pour afficher les API de ce type de ressource.


Si vous rencontrez un comportement inattendu lors de l’exécution des API REST SnapCenter , vous pouvez utiliser les fichiers journaux pour identifier la cause et résoudre le problème.  Vous pouvez télécharger les fichiers journaux depuis l'interface utilisateur de SnapCenter en cliquant sur *Surveiller* > *Journaux* > *Télécharger*.
