= 
:allow-uri-read: 


Vous pouvez utiliser l’applet de commande Remove-SmBackup pour nettoyer le nombre de sauvegardes pour les sauvegardes secondaires qui n’ont pas d’instantané.  Vous souhaiterez peut-être utiliser cette applet de commande lorsque le nombre total d’instantanés affichés dans la topologie Gérer les copies ne correspond pas au paramètre de conservation des instantanés de stockage secondaire.

Vous devez avoir préparé l’environnement PowerShell pour exécuter les applets de commande PowerShell.

Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .

.Étapes
. Lancez une session de connexion avec le serveur SnapCenter pour un utilisateur spécifié à l’aide de l’applet de commande Open-SmConnection.
+
[listing]
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----
. Nettoyez le nombre de sauvegardes secondaires à l'aide du paramètre -CleanupSecondaryBackups.
+
Cet exemple nettoie le nombre de sauvegardes pour les sauvegardes secondaires sans instantanés :

+
[listing]
----
Remove-SmBackup -CleanupSecondaryBackups
Remove-SmBackup
Are you sure want to remove the backup(s).
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
----

