= Gérer le mot de passe du magasin de clés du plug-in et l'alias de la paire de clés signée par l'autorité de certification en cours d'utilisation
:allow-uri-read: 


Vous devez gérer le mot de passe du magasin de clés des plug-ins et son certificat, configurer le certificat de l'autorité de certification, configurer les certificats racine ou intermédiaires dans le magasin de clés de confiance des plug-ins et configurer la paire de clés signée par l'autorité de certification dans le magasin de clés de confiance des plug-ins avec le service de plug-ins SnapCenter pour activer le certificat numérique installé.

Les plug-ins utilisent le fichier _keystore.jks_, qui se trouve dans _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_ à la fois comme magasin de confiance et comme magasin de clés.



== Gérer le mot de passe du magasin de clés du plug-in et l'alias de la paire de clés signée par l'autorité de certification en cours d'utilisation

.Étapes
. Vous pouvez récupérer le mot de passe par défaut du magasin de clés du plug-in à partir du fichier de propriétés de l'agent du plug-in.
+
Il s'agit de la valeur correspondant à la clé _KEYSTORE_PASS_.

. Modifier le mot de passe du keystore :
+
_keytool -storepasswd -keystore magasin de clés.jks_

+

NOTE: Si la commande « keytool » n’est pas reconnue sur l’invite de commande Windows, remplacez la commande keytool par son chemin complet.

+
_C:\Program Files\Java\<version_jdk>\bin\keytool.exe" -storepasswd -keystore keystore.jks_

. Modifiez le mot de passe de tous les alias des entrées de clés privées dans le magasin de clés avec le même mot de passe que celui utilisé pour le magasin de clés :
+
_keytool -keypasswd -alias "nom_d'alias_dans_cert" -keystore keystore.jks_

+
Mettez à jour la même chose pour la clé KEYSTORE_PASS dans le fichier _agent.properties_.

. Redémarrez le service après avoir modifié le mot de passe.
+

NOTE: Le mot de passe du magasin de clés du plug-in et de tous les mots de passe d'alias associés à la clé privée doivent être identiques.





== Configurer les certificats racine ou intermédiaires pour le plug-in trust-store

Vous devez configurer les certificats racine ou intermédiaires sans la clé privée pour connecter le trust-store.

.Étapes
. Accédez au dossier contenant le keystore du plug-in _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_
. Localisez le fichier « keystore.jks ».
. Répertoriez les certificats ajoutés dans le keystore :
+
_keytool -list -v -keystore keystore.jks_

. Ajouter un certificat racine ou intermédiaire :
+
_keytool -import -trustcacerts -alias myRootCA -fichier /root/USERTrustRSA_Root.cer -keystore keystore.jks_

. Redémarrez le service après avoir configuré les certificats racine ou intermédiaires pour connecter le magasin de confiance.



NOTE: Vous devez ajouter le certificat CA racine, puis les certificats CA intermédiaires.



== Configurer la paire de clés signée par l'autorité de certification pour le plug-in trust-store

Vous devez configurer la paire de clés signée par l'autorité de certification dans le magasin de clés de confiance du plug-in.

.Étapes
. Accédez au dossier contenant le keystore du plug-in _C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\etc_
. Localisez le fichier _keystore.jks_.
. Répertoriez les certificats ajoutés dans le keystore :
+
_keytool -list -v -keystore keystore.jks_

. Ajoutez le certificat CA contenant à la fois une clé privée et une clé publique.
+
_keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS_

. Répertoriez les certificats ajoutés dans le keystore.
+
_keytool -list -v -keystore keystore.jks_

. Vérifiez que le magasin de clés contient l’alias correspondant au nouveau certificat CA, qui a été ajouté au magasin de clés.
. Remplacez le mot de passe de la clé privée ajoutée pour le certificat CA par le mot de passe du magasin de clés.
+
Le mot de passe par défaut du magasin de clés du plug-in est la valeur de la clé KEYSTORE_PASS dans le fichier agent.properties.

+
_keytool -keypasswd -alias "nom_d'alias_dans_CA_cert" -keystore keystore.jks_

. Configurez le nom d’alias à partir du certificat CA dans le fichier _agent.properties_.
+
Mettez à jour cette valeur par rapport à la clé SCC_CERTIFICATE_ALIAS.

. Redémarrez le service après avoir configuré la paire de clés signée par l'autorité de certification pour le plug-in trust-store.




== Configurer la liste de révocation des certificats (CRL) pour les plug-ins SnapCenter

.À propos de cette tâche
* Pour télécharger le dernier fichier CRL pour le certificat CA associé, voir https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_update_certificate_revocation_list_file_in_SnapCenter_CA_Certificate["Comment mettre à jour le fichier de liste de révocation de certificats dans SnapCenter CA Certificate"] .
* Les plug-ins SnapCenter rechercheront les fichiers CRL dans un répertoire préconfiguré.
* Le répertoire par défaut des fichiers CRL pour les plug-ins SnapCenter est _'C:\Program Files\ NetApp\ SnapCenter\Snapcenter Plug-in Creator\ etc\crl'_.


.Étapes
. Vous pouvez modifier et mettre à jour le répertoire par défaut dans le fichier _agent.properties_ par rapport à la clé CRL_PATH.
. Vous pouvez placer plusieurs fichiers CRL dans ce répertoire.
+
Les certificats entrants seront vérifiés par rapport à chaque CRL.


