---
permalink: protect-azure/add-sap-hana-database.html 
sidebar: sidebar 
keywords: add, add SAP HANA database, manual discovery, automatic discovery 
summary: Ajoutez les bases de données SAP HANA. 
---
= Ajouter une base de données SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez ajouter la base de données SAP HANA manuellement.

.À propos de cette tâche
Les ressources doivent être ajoutées manuellement si le plug-in est installé sur un serveur centralisé.  Si le plug-in SAP HANA est installé sur l'hôte de la base de données HANA, le système HANA est détecté automatiquement.


NOTE: La découverte automatique n'est pas prise en charge pour la configuration multi-hôtes HANA ; elles doivent être ajoutées uniquement via un plug-in centralisé.

.Étapes
. Dans le volet de navigation de gauche, sélectionnez le plug-in SnapCenter pour la base de données SAP HANA dans la liste déroulante, puis cliquez sur *Ressources*.
. Sur la page Ressources, cliquez sur *Ajouter une base de données SAP HANA*.
. Dans la page Fournir les détails des ressources, effectuez les actions suivantes :
+
.. Saisissez le type de ressource : Conteneur unique, Conteneur de base de données multilocataire ou Volume sans données.
.. Saisissez le nom du système SAP HANA.
.. Entrez l'ID du système (SID).
.. Sélectionnez l'hôte du plug-in.
.. Saisissez la clé pour vous connecter au système SAP HANA.
.. Saisissez le nom d’utilisateur pour lequel la clé de stockage d’utilisateurs sécurisés HDB est configurée.


. Sur la page Fournir l’empreinte de stockage, sélectionnez * Azure NetApp Files* comme type de stockage.
+
.. Sélectionnez le compte Azure NetApp .
.. Sélectionnez le pool de capacité et les volumes associés.
.. Cliquez sur *Enregistrer*.


. Consultez le résumé, puis cliquez sur *Terminer*.

