---
permalink: protect-azure/add-hosts-install-plugin-for-oracle.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, oracle, database 
summary: Ajoutez des hôtes, puis installez les packages de plug-ins. 
---
= Ajoutez des hôtes et installez le plug-in SnapCenter pour la base de données Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la page Ajouter un hôte pour ajouter des hôtes, puis installer le package de plug-ins SnapCenter pour Linux ou le package de plug-ins SnapCenter pour AIX.  Les plug-ins sont automatiquement installés sur les hôtes distants.

Vous pouvez ajouter un hôte et installer des packages de plug-ins soit pour un hôte individuel, soit pour un cluster.  Si vous installez le plug-in sur un cluster (Oracle RAC), le plug-in est installé sur tous les nœuds du cluster.  Pour Oracle RAC One Node, vous devez installer le plug-in sur les nœuds actifs et passifs.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Hôtes*.
. Vérifiez que l’onglet *Hôtes gérés* est sélectionné.
. Cliquez sur *Ajouter*.
. Dans la page Hôtes, effectuez les actions suivantes :
+
.. Dans le champ Type d’hôte, sélectionnez le type d’hôte.
.. Dans le champ Nom d’hôte, saisissez le nom de domaine complet (FQDN) ou l’adresse IP de l’hôte.
.. Dans le champ Informations d’identification, saisissez les informations d’identification que vous avez créées.


. Dans la section Sélectionner les plug-ins à installer, sélectionnez les plug-ins à installer.
. (Facultatif) Cliquez sur *Plus d'options* et spécifiez les détails.
. Cliquez sur *Soumettre*.
. Vérifiez l’empreinte digitale, puis cliquez sur *Confirmer et soumettre*.
+
Dans une configuration de cluster, vous devez vérifier l’empreinte digitale de chacun des nœuds du cluster.

. Surveiller la progression de l'installation.

