---
permalink: protect-azure/add-hosts-install-plugin-for-sql.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SQL 
summary: Ajoutez des hôtes, puis installez les packages de plug-ins. 
---
= Ajouter des hôtes et installer le plug-in SnapCenter pour la base de données SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter prend en charge la protection des données des instances SQL sur les partages SMB sur Azure NetApp Files.  Les configurations autonomes et de groupe de disponibilité (AG) sont prises en charge.

Vous devez utiliser la page Ajouter un hôte de SnapCenter pour ajouter des hôtes, puis installer le package de plug-ins.  Les plug-ins sont automatiquement installés sur les hôtes distants.

.Avant de commencer
* Vous devez être un utilisateur affecté à un rôle disposant des autorisations d'installation et de désinstallation de plug-in, tel que le rôle Administrateur SnapCenter .
* Lors de l'installation d'un plug-in sur un hôte Windows, si vous spécifiez des informations d'identification qui ne sont pas intégrées ou si l'utilisateur appartient à un utilisateur de groupe de travail local, vous devez désactiver l'UAC sur l'hôte.


.Étapes
. Dans le volet de navigation de gauche, sélectionnez *Hôtes*.
. Vérifiez que l’onglet *Hôtes gérés* est sélectionné en haut.
. Sélectionnez *Ajouter*.
. Dans la page Hôtes, procédez comme suit :
+
.. Dans le champ Type d’hôte, sélectionnez le type d’hôte.
.. Dans le champ Nom d’hôte, saisissez le nom de domaine complet (FQDN) ou l’adresse IP de l’hôte.
.. Dans le champ Informations d’identification, saisissez les informations d’identification que vous avez créées.


. Dans la section *Sélectionner les plug-ins à installer*, sélectionnez les plug-ins à installer.
. (Facultatif) Cliquez sur *Plus d'options* et spécifiez les détails.
. Sélectionnez *Soumettre*.
. Sélectionnez *Configurer le répertoire des journaux* et dans la page Configurer le répertoire des journaux de l'hôte, entrez le chemin SMB du répertoire des journaux de l'hôte, puis cliquez sur *Enregistrer*.
. Cliquez sur *Soumettre* et surveillez la progression de l'installation.

