---
permalink: protect-azure/backup-sql-resource-groups.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SQL Server Database, back up, resource groups 
summary: Un groupe de ressources est un ensemble de ressources sur un hôte.  Une opération de sauvegarde sur le groupe de ressources est effectuée sur toutes les ressources définies dans le groupe de ressources. 
---
= Sauvegarder les groupes de ressources SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder les groupes de ressources constitués de plusieurs ressources.  Une opération de sauvegarde sur le groupe de ressources est effectuée sur toutes les ressources définies dans le groupe de ressources.

.Étapes
. Dans le volet de navigation de gauche, sélectionnez *Ressources*, puis sélectionnez le plug-in approprié dans la liste.
. Dans la page Ressources, sélectionnez *Groupe de ressources* dans la liste *Affichage*.
. Dans la page Groupes de ressources, sélectionnez le groupe de ressources que vous souhaitez sauvegarder, puis sélectionnez *Sauvegarder maintenant*.
. Dans la page Sauvegarde, effectuez les étapes suivantes :
+
.. Si plusieurs stratégies sont associées au groupe de ressources, dans la liste déroulante *Stratégie*, sélectionnez la stratégie que vous souhaitez utiliser pour la sauvegarde.
.. Après la sauvegarde, sélectionnez *Vérifier* pour vérifier la sauvegarde à la demande.
.. Sélectionnez *Sauvegarde*.


. Surveillez la progression de l’opération en sélectionnant *Surveillance* > *Tâches*.

