---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: Créez les informations d’identification Azure dans SnapCenter pour accéder au compte Azure NetApp . 
---
= Créer les informations d'identification Azure dans SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer les informations d’identification Azure dans SnapCenter pour accéder au compte Azure NetApp .

.Avant de commencer
* Assurez-vous d’avoir créé le principal de service dans Azure.
* Assurez-vous que vous disposez de l'ID de locataire, de l'ID client et de la clé secrète associée au principal de service.
+
** L’ID de locataire se trouve dans le portail Azure sur la page Présentation de l’ID Entra.
** L'ID client est également connu sous le nom d'ID d'application pour le principal de l'application/du service d'entreprise.  Vous pouvez le trouver dans le portail Azure sur la page Présentation de l’application d’entreprise que vous avez créée pour agir en tant que principal de service pour SnapCenter.
** La clé secrète du client est également connue sous le nom de valeur secrète.  Vous pouvez créer ce secret client dans le portail Azure en accédant à *Inscriptions d’applications* sous Entra ID.  Après avoir sélectionné l'application d'entreprise que vous avez créée, accédez à *Certificats et secrets*, puis à *Nouveau secret client*.
+

NOTE: La valeur secrète n'est accessible qu'au moment de sa création.  Vous ne pourrez pas y accéder ultérieurement.

** Des autorisations doivent être accordées au principal du service.  Le rôle de contributeur permettra au principal du service d’effectuer les actions requises dans Azure.  Cela peut être accordé à partir de la page Contrôle d'accès (IAM) dans la page Abonnement.




.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Informations d'identification*.
. Cliquez sur *Nouveau*.
. Dans la page Informations d’identification, spécifiez les informations suivantes requises pour créer les informations d’identification.
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Nom d'identification
 a| 
Saisissez un nom pour l’identifiant.



 a| 
Mode d'authentification
 a| 
Sélectionnez *Azure Credential* dans la liste déroulante.



 a| 
ID du locataire
 a| 
Entrez l'ID du locataire.



 a| 
ID client
 a| 
Entrez l'ID client.



 a| 
Clé secrète du client
 a| 
Entrez la clé secrète du client.

|===
. Cliquez sur *OK*.

