---
permalink: protect-azure/create-credential-add-plugin-host.html 
sidebar: sidebar 
keywords: snapcenter, azure, credential, plug-in host 
summary: Créez les informations d’identification pour ajouter l’hôte du plug-in. 
---
= Créez les informations d'identification pour ajouter l'hôte du plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilise des informations d’identification pour authentifier les utilisateurs pour les opérations SnapCenter .

Vous devez créer des informations d’identification pour l’installation des plug-ins SnapCenter et des informations d’identification supplémentaires pour effectuer des opérations de protection des données.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Informations d'identification*.
. Cliquez sur *Nouveau*.
. Dans la page Informations d’identification, spécifiez les informations suivantes requises pour créer les informations d’identification.
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Nom d'identification
 a| 
Saisissez un nom pour l’identifiant.



 a| 
Mode d'authentification
 a| 
Sélectionnez le mode d’authentification dans la liste déroulante.



 a| 
Type d'authentification
 a| 
Sélectionnez *Basé sur un mot de passe* ou *Basé sur une clé SSH* (uniquement pour l'hôte Linux).



 a| 
Nom d'utilisateur
 a| 
Spécifiez le nom d'utilisateur.



 a| 
Mot de passe
 a| 
Si vous avez sélectionné l’authentification par mot de passe, spécifiez le mot de passe.



 a| 
Clé privée SSH
 a| 
Si vous avez sélectionné l’authentification basée sur la clé SSH, spécifiez la clé privée.



 a| 
Utiliser les privilèges sudo
 a| 
Cochez la case Utiliser les privilèges sudo si vous créez des informations d’identification pour un utilisateur non root.


NOTE: Ceci s'applique uniquement aux utilisateurs Linux.

|===
. Cliquez sur *OK*.

