---
permalink: tech-refresh/task_tech_refresh_server_host.html 
sidebar: sidebar 
keywords: tech refresh, SnapCenter Server, cmdlet, APIs, F5, rollback, decommission, disaster recovery, standalone 
summary: 'Installez la même version de SnapCenter Server sur le nouvel hôte, puis exécutez les API ou exécutez les applets de commande pour sauvegarder SnapCenter à partir de l"ancien serveur et le restaurer sur le nouveau serveur.' 
---
= Mise à jour technique de l'hôte SnapCenter Server
:allow-uri-read: 


[role="lead"]
Lorsque l'hôte SnapCenter Server nécessite une actualisation, vous pouvez installer la même version de SnapCenter Server sur le nouvel hôte, puis exécuter les API pour sauvegarder SnapCenter à partir de l'ancien serveur et le restaurer sur le nouveau serveur.

.Étapes
. Déployez le nouvel hôte et effectuez les tâches suivantes :
+
.. Installez la même version du serveur SnapCenter .
.. (Facultatif) Configurez les certificats CA et activez le SSL bidirectionnel.  Pour plus d'informations, reportez-vous à https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html["Configurer le certificat CA"] et https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html["Configurer et activer le SSL bidirectionnel"] .
.. (Facultatif) Configurez l’authentification multifacteur. Pour plus d'informations, consultez  https://docs.netapp.com/us-en/snapcenter/install/enable_multifactor_authentication.html["Activer l'authentification multifacteur"] .


. Connectez-vous en tant qu’utilisateur administrateur SnapCenter .
. Créez une sauvegarde du serveur SnapCenter sur l'ancien hôte à l'aide de l'API : `/<snapcenter_version>/server/backup` ou l'applet de commande : _New-SmServerBackup_.
+

NOTE: Avant d’effectuer la sauvegarde, suspendez toutes les tâches planifiées et assurez-vous qu’aucune tâche n’est en cours d’exécution.

+

IMPORTANT: Si vous souhaitez restaurer la sauvegarde sur le serveur SnapCenter exécuté sur un nouveau domaine, avant d'effectuer une sauvegarde, vous devez ajouter le nouvel utilisateur de domaine dans l'ancien hôte SnapCenter et attribuer le rôle d'administrateur SnapCenter .

. Copiez la sauvegarde de l’ancien hôte vers le nouvel hôte.
. Restaurez la sauvegarde du serveur SnapCenter sur le nouvel hôte à l'aide de l'API : `/<snapcenter_version>/server/restore` ou l'applet de commande : _Restore-SmServerBackup_.
+
La restauration mettra à jour la nouvelle URL du serveur SnapCenter dans tous les hôtes par défaut.  Si vous souhaitez ignorer la mise à jour, utilisez l'attribut _-SkipSMSURLInHosts_ et mettez à jour séparément l'URL du serveur en exécutant à l'aide de l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.

+

NOTE: Si l'hôte du plug-in n'est pas en mesure de résoudre le nom d'hôte du serveur, connectez-vous à chaque hôte du plug-in et ajoutez l'entrée _etc/host_ pour la nouvelle IP au format <Nouvelle IP> SC_Server_Name.

+

NOTE: Les entrées du serveur _etc/host_ ne seront pas restaurées.  Vous pouvez le restaurer manuellement à partir de l'ancien serveur.

+
Si la sauvegarde est restaurée sur le serveur SnapCenter qui s'exécute sur un nouveau domaine et si vous souhaitez continuer à utiliser les anciens utilisateurs du domaine, vous devez enregistrer l'ancien domaine sur le nouveau serveur SnapCenter .

+

NOTE: Si vous avez mis à jour manuellement le fichier web.config dans l'ancien hôte SnapCenter , les mises à jour ne seront pas copiées sur le nouvel hôte.  Vous devez effectuer manuellement les mêmes modifications dans le fichier web.config du nouvel hôte.

. Si vous avez ignoré la mise à jour de l'URL du serveur SnapCenter ou si l'un des hôtes était en panne pendant le processus de restauration, mettez à jour le nouveau nom du serveur dans tous les hôtes ou les hôtes spécifiés qui sont gérés par SnapCenter à l'aide de l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.
. Activez les tâches planifiées sur tous les hôtes du nouveau serveur SnapCenter .




== Mise à jour technique d'un nœud du cluster F5

Vous pouvez effectuer une actualisation technique de n'importe quel nœud du cluster F5 en supprimant le nœud et en ajoutant le nouveau nœud.  Si le nœud qui doit être actualisé est actif, définissez un autre nœud du cluster comme actif, puis supprimez le nœud.

Pour plus d'informations sur la façon d'ajouter un nœud au cluster F5, reportez-vous à https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Configurer les serveurs SnapCenter pour une haute disponibilité à l'aide de F5"] .


NOTE: Si l'URL du cluster F5 change, l'URL peut être mise à jour dans tous les hôtes à l'aide de l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.



== Mise hors service de l'ancien hôte SnapCenter Server

Vous pouvez supprimer l'ancien hôte SnapCenter Server après avoir vérifié que le nouveau SnapCenter Server est opérationnel et que tous les hôtes de plug-in sont capables de communiquer avec le nouvel hôte SnapCenter Server.



== Retour à l'ancien hôte SnapCenter Server

En cas de problème, vous pouvez restaurer l'ancien hôte SnapCenter Server en mettant à jour l'URL du serveur SnapCenter dans tous les hôtes à l'aide de l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.



== Reprise après sinistre



=== Récupération après sinistre d'un hôte SnapCenter autonome

Vous pouvez effectuer une récupération après sinistre en restaurant la sauvegarde du serveur sur le nouvel hôte.

.Avant de commencer
Assurez-vous de disposer d’une sauvegarde de l’ancien serveur SnapCenter .

.Étapes
. Déployez le nouvel hôte et effectuez les tâches suivantes :
+
.. Installez la même version du serveur SnapCenter .
.. Configurez les certificats CA et activez le SSL bidirectionnel.  Pour plus d'informations, reportez-vous à https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html["Configurer le certificat CA"] et https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html["Configurer et activer le SSL bidirectionnel"] .


. Copiez l’ancienne sauvegarde du serveur SnapCenter sur le nouvel hôte.
. Connectez-vous en tant qu’utilisateur administrateur SnapCenter .
. Restaurez la sauvegarde du serveur SnapCenter sur le nouvel hôte à l'aide de l'API : `/<snapcenter_version>/server/restore` ou l'applet de commande : _Restore-SmServerBackup_.
+
La restauration mettra à jour la nouvelle URL du serveur SnapCenter dans tous les hôtes par défaut.  Si vous souhaitez ignorer la mise à jour, utilisez l'attribut _-SkipSMSURLInHosts_ et mettez à jour séparément l'URL du serveur en utilisant l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.

+

NOTE: Si l'hôte du plug-in n'est pas en mesure de résoudre le nom d'hôte du serveur, connectez-vous à chaque hôte du plug-in et ajoutez l'entrée _etc/host_ pour la nouvelle IP au format <Nouvelle IP> SC_Server_Name.

+

NOTE: Les entrées du serveur _etc/host_ ne seront pas restaurées.  Vous pouvez le restaurer manuellement à partir de l'ancien serveur.

. Si vous avez ignoré la mise à jour de l'URL ou si l'un des hôtes était en panne pendant le processus de restauration, mettez à jour le nouveau nom du serveur dans tous les hôtes ou les hôtes spécifiés qui sont gérés par SnapCenter à l'aide de l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.




=== Reprise après sinistre du cluster SnapCenter F5

Vous pouvez effectuer une récupération après sinistre en restaurant la sauvegarde du serveur sur le nouvel hôte, puis en convertissant l'hôte autonome en cluster.

.Avant de commencer
Assurez-vous de disposer d’une sauvegarde de l’ancien serveur SnapCenter .

.Étapes
. Déployez le nouvel hôte et effectuez les tâches suivantes :
+
.. Installez la même version du serveur SnapCenter .
.. Configurez les certificats CA et activez le SSL bidirectionnel.  Pour plus d'informations, reportez-vous à https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html["Configurer le certificat CA"] et https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html["Configurer et activer le SSL bidirectionnel"] .


. Copiez l’ancienne sauvegarde du serveur SnapCenter sur le nouvel hôte.
. Connectez-vous en tant qu’utilisateur administrateur SnapCenter .
. Restaurez la sauvegarde du serveur SnapCenter sur le nouvel hôte à l'aide de l'API : `/<snapcenter_version>/server/restore` ou l'applet de commande : _Restore-SmServerBackup_.
+
La restauration mettra à jour la nouvelle URL du serveur SnapCenter dans tous les hôtes par défaut.  Si vous souhaitez ignorer la mise à jour, utilisez l'attribut _-SkipSMSURLInHosts_ et mettez à jour séparément l'URL du serveur en utilisant l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.

+

NOTE: Si l'hôte du plug-in n'est pas en mesure de résoudre le nom d'hôte du serveur, connectez-vous à chaque hôte du plug-in et ajoutez l'entrée _etc/host_ pour la nouvelle IP au format <Nouvelle IP> SC_Server_Name.

+

NOTE: Les entrées du serveur _etc/host_ ne seront pas restaurées.  Vous pouvez le restaurer manuellement à partir de l'ancien serveur.

. Si vous avez ignoré la mise à jour de l'URL ou si l'un des hôtes était en panne pendant le processus de restauration, mettez à jour le nouveau nom du serveur dans tous les hôtes ou les hôtes spécifiés qui sont gérés par SnapCenter à l'aide de l'API : `/<snapcenter_version>/server/configureurl` ou l'applet de commande : _Set-SmServerConfig_.
. Convertissez l'hôte autonome en cluster F5.
+
Pour plus d'informations sur la configuration de F5, reportez-vous à https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html["Configurer les serveurs SnapCenter pour une haute disponibilité à l'aide de F5"] .



.Informations connexes
Pour plus d'informations sur les API, vous devez accéder à la page Swagger. voirlink:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["Comment accéder aux API REST à l'aide de la page Web de l'API Swagger"] .

Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_.  Alternativement, vous pouvez également vous référer au https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .
