---
permalink: tech-refresh/task_tech_refresh_plugin_host.html 
sidebar: sidebar 
keywords: tech refresh, plug-in host, supported plug-ins, prerequisites to refresh plug-in hosts, application hosts, limitations for tech refresh of plug-in hosts 
summary: 'Déplacez les ressources de l"ancien hôte vers le nouvel hôte pour effectuer une actualisation technique des hôtes du plug-in.' 
---
= Mise à jour technique des hôtes de plug-ins SnapCenter
:allow-uri-read: 


[role="lead"]
Lorsque les hôtes du plug-in SnapCenter nécessitent une actualisation, vous devez déplacer les ressources de l'ancien hôte vers le nouvel hôte.  Lorsque le nouvel hôte est ajouté à SnapCenter, il découvrira toutes les ressources mais sera traité comme de nouvelles ressources.

.À propos de cette tâche
Vous devez exécuter l’API ou l’applet de commande qui prendra l’ancien nom d’hôte et le nouveau nom d’hôte comme entrée, comparera les ressources par nom et reliera les objets des ressources correspondantes de l’ancien hôte au nouvel hôte.  Les ressources correspondantes seront marquées comme protégées.

* Le paramètre _IsDryRun_ est défini sur True par défaut et identifie les ressources correspondantes de l'ancien et du nouvel hôte.
+
Après avoir vérifié les ressources correspondantes, vous devez définir le paramètre _IsDryRun_ sur False pour relier les objets des ressources correspondantes de l'ancien hôte au nouvel hôte.

* Le paramètre _AutoMigrateManuallyAddedResources_ est défini sur True par défaut et cela copie automatiquement les ressources ajoutées manuellement de l'ancien hôte vers le nouvel hôte.
+
Le paramètre _AutoMigrateManuallyAddedResources_ s'applique uniquement aux ressources Oracle et SAP HANA.

* Le paramètre _SQLInstanceMapping_ doit être utilisé si le nom de l'instance est différent entre l'ancien hôte et le nouvel hôte.  S'il s'agit d'une instance par défaut, utilisez _default_instance_ comme nom d'instance.


L'actualisation technique est prise en charge pour les plug-ins SnapCenter suivants :

* Plug-in SnapCenter pour Microsoft SQL Server
+
** Si les bases de données SQL sont protégées au niveau de l'instance et que dans le cadre de l'actualisation technique de l'hôte, seules des ressources partielles sont déplacées vers le nouvel hôte, la protection au niveau de l'instance existante sera convertie en protection du groupe de ressources et les instances des deux hôtes seront ajoutées au groupe de ressources.
** Si un hôte SQL (par exemple host1) est utilisé comme planificateur ou serveur de vérification pour les ressources d'un autre hôte (par exemple host2), alors lors de l'exécution de l'actualisation technique sur host1, la planification ou les détails de vérification ne seront pas migrés et continueront de s'exécuter sur host1.  Si vous devez apporter des modifications, vous devez le faire manuellement dans les hôtes respectifs.
** Si vous utilisez la configuration des instances de cluster de basculement SQL (FCI), vous pouvez effectuer l'actualisation technique en ajoutant le nouveau nœud au cluster FCI et en actualisant l'hôte du plug-in dans SnapCenter.
** Si vous utilisez la configuration du groupe de disponibilité SQL (AG), l'actualisation technique n'est pas requise.  Vous pouvez ajouter le nouveau nœud à AG et actualiser l'hôte dans SnapCenter.


* Plug-in SnapCenter pour Windows
* Plug-in SnapCenter pour base de données Oracle
+
Si vous utilisez la configuration Oracle Real Application Cluster (RAC), vous pouvez effectuer l'actualisation technique en ajoutant le nouveau nœud au cluster RAC et en actualisant l'hôte du plug-in dans SnapCenter.

* Plug-in SnapCenter pour la base de données SAP HANA


Les cas d'utilisation pris en charge sont :

* Migration des ressources d’un hôte vers un autre.
* Migration de ressources de plusieurs hôtes vers un ou plusieurs hôtes.
* Migration des ressources d'un hôte vers plusieurs hôtes.


Les scénarios pris en charge sont :

* Le nouvel hôte a un nom différent de l'ancien hôte
* L'hôte existant a été renommé


.Avant de commencer
Comme ce flux de travail modifie les données du référentiel SnapCenter , il est recommandé de sauvegarder le référentiel SnapCenter .  En cas de problème de données, le référentiel SnapCenter peut être rétabli à l'ancien état à l'aide de la sauvegarde.

Pour plus d'informations, consultez  https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["Sauvegarder le référentiel SnapCenter"] .

.Étapes
. Déployez le nouvel hôte et installez l’application.
. Suspendre les horaires de l'ancien hôte.
. Déplacez les ressources requises de l’ancien hôte vers le nouvel hôte.
+
.. Importez les bases de données requises dans le nouvel hôte à partir du même stockage.
+
*** Assurez-vous que le stockage est mappé sur le même lecteur ou le même chemin de montage que celui de l'ancien hôte.  Si le stockage n'est pas mappé correctement, les sauvegardes créées sur l'ancien hôte ne peuvent pas être utilisées pour la restauration.
+

NOTE: Par défaut, Windows attribue automatiquement le prochain lecteur disponible.

*** Si le stockage DR est activé, le stockage correspondant doit être monté sur le nouvel hôte.


.. Vérifiez la compatibilité en cas de changement de version de l'application.
.. Uniquement pour l'hôte du plug-in Oracle, assurez-vous que les UID et GID d'Oracle et de ses utilisateurs de groupe sont identiques à ceux de l'ancien hôte.
+
Pour plus d'informations, consultez :

+
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_SQL_host_tech_refresh["Comment migrer une base de données SQL d'un ancien hôte vers un nouvel hôte"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Oracle_host_tech_refresh["Comment migrer une base de données Oracle d'un ancien hôte vers un nouvel hôte"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Hana_host_tech_refresh["Comment transférer la base de données SAP HANA sur un nouvel hôte"]




. Ajoutez le nouvel hôte à SnapCenter.
. Vérifiez si toutes les ressources sont découvertes.
. Exécutez l’API d’actualisation de l’hôte : `/<snapcenter_version>/techrefresh/host` ou l'applet de commande : _Invoke-SmTechRefreshHost_.
+

NOTE: L'exécution à sec est activée par défaut et les ressources correspondantes à relier sont identifiées.  Vous pouvez vérifier les ressources en exécutant l'API : '/jobs/{jobid}' ou l'applet de commande _Get-SmJobSummaryReport_.

+
Si vous avez migré les ressources à partir de plusieurs hôtes, vous devez exécuter l’API ou l’applet de commande pour tous les hôtes.  Si le lecteur ou le chemin de montage du nouvel hôte n’est pas le même que celui de l’ancien hôte, les opérations de restauration suivantes échoueront :

+
** La restauration SQL sur place échouera.  Cependant, la fonctionnalité RTAL peut être exploitée.
** La restauration des bases de données Oracle et SAP HANA échouera.
+
Si vous souhaitez migrer vers plusieurs hôtes, vous devez effectuer toutes les étapes de l’étape 1 pour tous les hôtes.

+

NOTE: Vous pouvez exécuter l'API ou l'applet de commande sur le même hôte plusieurs fois. Elle ne sera reliée que si une nouvelle ressource est identifiée.



. (Facultatif) Supprimez l'ancien ou les anciens hôtes de SnapCenter.


.Informations connexes
Pour plus d'informations sur les API, vous devez accéder à la page Swagger. voirlink:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["Comment accéder aux API REST à l'aide de la page Web de l'API Swagger"] .

Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_.  Alternativement, vous pouvez également vous référer au https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .
