---
permalink: admin/concept_manage_the_snapcenter_server_repository.html 
sidebar: sidebar 
keywords: SnapCenter Server 
summary: Les informations relatives aux différentes opérations effectuées à partir de SnapCenter sont stockées dans le référentiel de base de données SnapCenter Server.  Vous devez créer des sauvegardes du référentiel pour protéger le serveur SnapCenter contre la perte de données. 
---
= Gérer le référentiel SnapCenter Server
:allow-uri-read: 


[role="lead"]
Les informations relatives aux différentes opérations effectuées à partir de SnapCenter sont stockées dans le référentiel de base de données SnapCenter Server.  Vous devez créer des sauvegardes du référentiel pour protéger le serveur SnapCenter contre la perte de données.

Le référentiel SnapCenter Server est parfois appelé base de données NSM.



== Conditions préalables à la protection du référentiel SnapCenter

Votre environnement doit répondre à certaines conditions préalables pour protéger le référentiel SnapCenter .

* Gestion des connexions aux machines virtuelles de stockage (SVM)
+
Vous devez configurer les informations d’identification de stockage.

* Provisionnement des hôtes
+
Au moins un disque de stockage NetApp doit être présent sur l’hôte du référentiel SnapCenter .  Si aucun disque NetApp n’est présent sur l’hôte du référentiel SnapCenter , vous devez en créer un.

+
Pour plus de détails sur l'ajout d'hôtes, la configuration des connexions SVM et le provisionnement des hôtes, consultez les instructions d'installation.

* Provisionnement d'un LUN iSCSI ou d'un VMDK
+
Pour une configuration haute disponibilité (HA), vous pouvez provisionner un LUN iSCSI ou un VMDK dans l'un des serveurs SnapCenter .





== Sauvegarder le référentiel SnapCenter

La sauvegarde du référentiel SnapCenter Server permet de le protéger contre la perte de données.  Vous pouvez sauvegarder le référentiel en exécutant l'applet de commande _Protect-SmRepository_.

*À propos de cette tâche*

L'applet de commande _Protect-SmRepository_ accomplit les tâches suivantes :

* Crée un groupe de ressources et une politique
* Crée une planification de sauvegarde pour le référentiel SnapCenter


*Mesures*

. Lancez PowerShell.
. Sur l’hôte SnapCenter Server, établissez une session à l’aide de l’applet de commande _Open-SmConnection_, puis entrez vos informations d’identification.
. Sauvegardez le référentiel à l’aide de l’applet de commande _Protect-SmRepository_ et des paramètres requis.




== Afficher les sauvegardes du référentiel SnapCenter

Vous pouvez afficher une liste des sauvegardes du référentiel de base de données SnapCenter Server en exécutant l'applet de commande _Get-SmRepositoryBackups_.

Les sauvegardes du référentiel sont créées selon la planification spécifiée dans l'applet de commande _Protect-SmRepository_.

*Mesures*

. Lancez PowerShell.
. À partir de l'invite de commande, entrez l'applet de commande suivante, puis fournissez les informations d'identification pour vous connecter au serveur SnapCenter : _Open-SMConnection_
. Répertoriez toutes les sauvegardes de base de données SnapCenter disponibles à l’aide de l’applet de commande _Get-SmRepositoryBackups_.




== Restaurer le référentiel de base de données SnapCenter

Vous pouvez restaurer le référentiel SnapCenter en exécutant l'applet de commande _Restore-SmRepositoryBackup_.

Lorsque vous restaurez le référentiel SnapCenter , les autres opérations SnapCenter en cours d'exécution seront affectées car pendant l'opération de restauration, la base de données du référentiel n'est pas accessible.

*Mesures*

. Lancez PowerShell.
. À partir de l'invite de commande, entrez l'applet de commande suivante, puis fournissez les informations d'identification pour vous connecter au serveur SnapCenter : _Open-SMConnection_
. Restaurez la sauvegarde du référentiel à l’aide de l’applet de commande _Restore-SmRepositoryBackup_.
+
L'applet de commande suivante restaure le référentiel de base de données SnapCenter MySQL à partir des sauvegardes existantes sur iSCSI LUN ou VMDK :

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445
----
+
L'applet de commande suivante restaure la base de données SnapCenter MySQL lorsque les fichiers de sauvegarde sont supprimés accidentellement dans le LUN iSCSI.  Pour VMDK, restaurez manuellement la sauvegarde à partir des snapshots ONTAP .

+
[listing]
----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445 -RestoreFileSystem
----



NOTE: La sauvegarde utilisée pour effectuer l'opération de restauration du référentiel ne sera pas répertoriée lorsque les sauvegardes du référentiel seront récupérées après l'exécution de l'opération de restauration.



== Migrer le référentiel SnapCenter

Vous pouvez migrer le référentiel de base de données SnapCenter Server de l'emplacement par défaut vers un autre disque.  Vous pouvez migrer le référentiel lorsque vous souhaitez le déplacer vers un disque avec plus d'espace.

*Mesures*

. Arrêtez le service MYSQL57 sous Windows.
. Localisez le répertoire de données MySQL.
+
Vous pouvez généralement trouver le répertoire de données dans C:\ProgramData\MySQL\MySQL Server 5.7\Data.

. Copiez le répertoire de données MySQL vers le nouvel emplacement, par exemple, E:\Data\nsm.
. Cliquez avec le bouton droit sur le nouveau répertoire, puis sélectionnez *Propriétés* > *Sécurité* pour ajouter le compte de serveur local du service réseau au nouveau répertoire, puis attribuez au compte le contrôle total.
. Renommez le répertoire de base de données d'origine, par exemple, nsm_copy.
. À partir d’une invite de commande Windows, créez un lien de répertoire symbolique à l’aide de la commande _mklink_.
+
`"mklink /d "C:\ProgramData\MySQL\MySQL Server 5.7\Data\nsm" "E:\Data\nsm" "`

. Démarrez le service MYSQL57 sous Windows.
. Vérifiez que le changement d'emplacement de la base de données a réussi en vous connectant à SnapCenter et en vérifiant les entrées du référentiel, ou en vous connectant à l'utilitaire MySQL et en vous connectant au nouveau référentiel.
. Supprimez le répertoire de référentiel de base de données d'origine renommé (nsm_copy).




== Réinitialiser le mot de passe du référentiel SnapCenter

Le mot de passe de la base de données du référentiel MySQL Server est généré automatiquement lors de l'installation de SnapCenter Server à partir de SnapCenter 4.2.  Ce mot de passe généré automatiquement n'est à aucun moment connu de l'utilisateur de SnapCenter .  Si vous souhaitez accéder à la base de données du référentiel, vous devez réinitialiser le mot de passe.

.Avant de commencer
Vous devez disposer des privilèges d’administrateur SnapCenter pour réinitialiser le mot de passe.

*Mesures*

. Lancez PowerShell.
. À partir de l'invite de commande, entrez la commande suivante, puis fournissez les informations d'identification pour vous connecter au serveur SnapCenter : _Open-SMConnection_
. Réinitialiser le mot de passe du référentiel : _Set-SmRepositoryPassword_
+
La commande suivante réinitialise le mot de passe du référentiel :

+
[listing]
----

Set-SmRepositoryPassword at command pipeline position 1
Supply values for the following parameters:
NewPassword: ********
ConfirmPassword: ********
Successfully updated the MySQL server password.
----


.Informations connexes
Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .
