---
permalink: admin/task_request_reports_of_the_protection_status_from_the_dashboard.html 
sidebar: sidebar 
keywords: dashboard 
summary: 'Vous pouvez demander des détails de protection pour les ressources gérées par des plug-ins spécifiques à l"aide du tableau de bord.' 
---
= Demander des rapports sur l'état de protection à partir du tableau de bord
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez demander des détails de protection pour les ressources gérées par des plug-ins spécifiques à l'aide du tableau de bord.  Seules les sauvegardes de données sont prises en compte pour le résumé de la protection des données.

*Mesures*

. Dans le volet de navigation de gauche, cliquez sur *Tableau de bord*.
. Localisez la mosaïque Résumé de la dernière protection dans le tableau de bord et utilisez le menu déroulant pour sélectionner un plug-in.
+
Le tableau de bord affiche un graphique en anneau pour les ressources sauvegardées sur le stockage principal et, si applicable au plug-in, un graphique en anneau pour les ressources sauvegardées sur le stockage secondaire.

+

NOTE: Les rapports de protection des données ne sont disponibles que pour des types de plug-ins spécifiques.  La spécification de *Tous les plug-ins* n'est pas prise en charge.

. Cliquez sur la tranche de beignet représentant le statut pour lequel vous souhaitez un rapport.
+
Lorsque vous cliquez sur le graphique en anneau, vous êtes redirigé de la page Tableau de bord vers les rapports, puis vers la page Plug-in.  Le rapport affiche uniquement l’état du plug-in que vous avez sélectionné.  Vous pouvez consulter le rapport ou le télécharger sur votre système local.

+

NOTE: La redirection vers la page Rapports pour le graphique en anneau SnapMirror et la sauvegarde SAP HANA basée sur des fichiers n'est pas prise en charge.


