---
permalink: protect-postgresql/add-hosts-and-install-plug-in-packages-on-remote-hosts-postgresql.html 
sidebar: sidebar 
keywords: credentials 
summary: Vous devez utiliser la page Ajouter un hôte de SnapCenter pour ajouter des hôtes, puis installer les packages de plug-ins.  Les plug-ins sont automatiquement installés sur les hôtes distants.  Vous pouvez ajouter un hôte et installer des packages de plug-ins soit pour un hôte individuel, soit pour un cluster. 
---
= Ajouter des hôtes et installer des packages de plug-ins sur des hôtes distants
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez utiliser la page Ajouter un hôte de SnapCenter pour ajouter des hôtes, puis installer les packages de plug-ins.  Les plug-ins sont automatiquement installés sur les hôtes distants.  Vous pouvez ajouter l'hôte et installer des packages de plug-ins pour un hôte individuel.

.Avant de commencer
* Si le système d'exploitation de l'hôte SnapCenter Server est Windows 2019 et que le système d'exploitation de l'hôte du plug-in est Windows 2022, vous devez effectuer les opérations suivantes :
+
** Mise à niveau vers Windows Server 2019 (build du système d'exploitation 17763.5936) ou version ultérieure
** Mise à niveau vers Windows Server 2022 (build du système d'exploitation 20348.2402) ou version ultérieure


* Vous devez être un utilisateur affecté à un rôle disposant des autorisations d'installation et de désinstallation de plug-in, tel que le rôle Administrateur SnapCenter .
* Lors de l'installation d'un plug-in sur un hôte Windows, si vous spécifiez des informations d'identification qui ne sont pas intégrées ou si l'utilisateur appartient à un utilisateur de groupe de travail local, vous devez désactiver l'UAC sur l'hôte.
* Vous devez vous assurer que le service de mise en file d’attente des messages est en cours d’exécution.
* La documentation d'administration contient des informations sur la gestion des hôtes.
* Si vous utilisez un compte de service géré de groupe (gMSA), vous devez configurer gMSA avec des privilèges administratifs.
+
link:../protect-postgresql/configure-gMSA-on-windows-server-2012-or-later.html["Configurer un compte de service géré de groupe sur Windows Server 2016 ou version ultérieure pour PostgreSQL"]



.À propos de cette tâche
* Vous ne pouvez pas ajouter un serveur SnapCenter en tant qu’hôte de plug-in à un autre serveur SnapCenter .


.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Hôtes*.
. Vérifiez que l’onglet *Hôtes gérés* est sélectionné en haut.
. Cliquez sur *Ajouter*.
. Dans la page Hôtes, effectuez les actions suivantes :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Type d'hôte
 a| 
Sélectionnez le type d'hôte :

** Windows
** Linux
+

NOTE: Le plug-in pour PostgreSQL est installé sur l'hôte client PostgreSQL, et cet hôte peut être sur un système Windows ou un système Linux.





 a| 
Nom d'hôte
 a| 
Entrez le nom de l'hôte de communication.  Saisissez le nom de domaine complet (FQDN) ou l'adresse IP de l'hôte.  SnapCenter dépend de la configuration appropriée du DNS.  Par conséquent, la meilleure pratique consiste à saisir le FQDN.



 a| 
Informations d'identification
 a| 
Sélectionnez le nom des informations d’identification que vous avez créées ou créez de nouvelles informations d’identification.  L'identifiant doit disposer de droits administratifs sur l'hôte distant.  Pour plus de détails, consultez les informations sur la création d'informations d'identification.

Vous pouvez afficher les détails des informations d’identification en positionnant votre curseur sur le nom des informations d’identification que vous avez fournies.


NOTE: Le mode d’authentification des informations d’identification est déterminé par le type d’hôte que vous spécifiez dans l’assistant Ajouter un hôte.

|===
. Dans la section Sélectionner les plug-ins à installer, sélectionnez les plug-ins à installer.
+
Lors de l'utilisation de l'API REST pour installer le plug-in pour PostgreSQL, vous devez transmettre la version 3.0.  Par exemple, PostgreSQL:3.0

. (Facultatif) Cliquez sur *Plus d'options*.
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Port
 a| 
Conservez le numéro de port par défaut ou spécifiez le numéro de port.  Le numéro de port par défaut est 8145.  Si le serveur SnapCenter a été installé sur un port personnalisé, ce numéro de port sera affiché comme port par défaut.


NOTE: Si vous avez installé manuellement les plug-ins et spécifié un port personnalisé, vous devez spécifier le même port.  Sinon, l’opération échoue.



 a| 
Chemin d'installation
 a| 
Le plug-in pour PostgreSQL est installé sur l'hôte client PostgreSQL, et cet hôte peut être sur un système Windows ou un système Linux.

** Pour le package de plug-ins SnapCenter pour Windows, le chemin par défaut est C:\Program Files\ NetApp\ SnapCenter.  En option, vous pouvez personnaliser le chemin.
** Pour le package de plug-ins SnapCenter pour Linux, le chemin par défaut est /opt/ NetApp/snapcenter.  En option, vous pouvez personnaliser le chemin.




 a| 
Ignorer les vérifications de préinstallation
 a| 
Cochez cette case si vous avez déjà installé les plug-ins manuellement et que vous ne souhaitez pas valider si l'hôte répond aux exigences d'installation du plug-in.



 a| 
Ajouter tous les hôtes du cluster
 a| 
Cochez cette case pour ajouter tous les nœuds du cluster.



 a| 
Utiliser un compte de service géré de groupe (gMSA) pour exécuter les services du plug-in
 a| 
Pour l’hôte Windows, cochez cette case si vous souhaitez utiliser un compte de service géré de groupe (gMSA) pour exécuter les services de plug-in.


NOTE: Fournissez le nom gMSA au format suivant : domainName\accountName$.


NOTE: gMSA sera utilisé comme compte de service de connexion uniquement pour le service SnapCenter Plug-in pour Windows.

|===
. Cliquez sur *Soumettre*.
+
Si vous n'avez pas coché la case « Ignorer les pré-vérifications », l'hôte est validé afin de vérifier s'il répond aux exigences d'installation du plug-in. L'espace disque, la RAM, la version de PowerShell, la version de .NET, l'emplacement (pour les plug-ins Windows) et la version de Java (pour les plug-ins Linux) sont validés par rapport à la configuration minimale requise.  Si les exigences minimales ne sont pas respectées, des messages d’erreur ou d’avertissement appropriés s’affichent.

+
Si l'erreur est liée à l'espace disque ou à la RAM, vous pouvez mettre à jour le fichier web.config situé dans C:\Program Files\ NetApp\ SnapCenter WebApp pour modifier les valeurs par défaut.  Si l’erreur est liée à d’autres paramètres, vous devez résoudre le problème.

+

NOTE: Dans une configuration HA, si vous mettez à jour le fichier web.config, vous devez mettre à jour le fichier sur les deux nœuds.

. Si le type d’hôte est Linux, vérifiez l’empreinte digitale, puis cliquez sur *Confirmer et soumettre*.
+
Dans une configuration de cluster, vous devez vérifier l’empreinte digitale de chacun des nœuds du cluster.

+

NOTE: La vérification des empreintes digitales est obligatoire même si le même hôte a été ajouté précédemment à SnapCenter et que l'empreinte digitale a été confirmée.

. Surveiller la progression de l'installation.
+
** Pour le plug-in Windows, les journaux d'installation et de mise à niveau se trouvent à : _C:\Windows\ SnapCenter plugin\Install_<JOBID>\_
** Pour le plug-in Linux, les journaux d'installation se trouvent à : _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Install_<JOBID>.log_ et les journaux de mise à niveau se trouvent à : _/var/opt/snapcenter/logs/SnapCenter_Linux_Host_Plug-in_Upgrade_<JOBID>.log_



