---
permalink: protect-postgresql/snapcenter-plug-in-for-postgresql-features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for postgresql 
summary: 'SnapCenter s"intègre à l"application plug-in et aux technologies NetApp sur le système de stockage.  Pour travailler avec le plug-in pour le cluster postgresql, vous utilisez l"interface utilisateur graphique SnapCenter .' 
---
= Fonctionnalités du plug-in SnapCenter pour PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter s'intègre à l'application plug-in et aux technologies NetApp sur le système de stockage.  Pour travailler avec le plug-in pour le cluster PostgreSQL, vous utilisez l'interface utilisateur graphique SnapCenter .

* *Interface utilisateur graphique unifiée*
+
L'interface SnapCenter assure la standardisation et la cohérence entre les plug-ins et les environnements.  L'interface SnapCenter vous permet d'effectuer des opérations de sauvegarde, de restauration et de clonage cohérentes sur tous les plug-ins, d'utiliser des rapports centralisés, d'utiliser des vues de tableau de bord en un coup d'œil, de configurer le contrôle d'accès basé sur les rôles (RBAC) et de surveiller les tâches sur tous les plug-ins.

* *Administration centrale automatisée*
+
Vous pouvez planifier des opérations de sauvegarde, configurer la conservation des sauvegardes basée sur des politiques et effectuer des opérations de restauration.  Vous pouvez également surveiller de manière proactive votre environnement en configurant SnapCenter pour envoyer des alertes par e-mail.

* *Technologie de copie instantanée NetApp non perturbatrice*
+
SnapCenter utilise la technologie de snapshot NetApp avec le plug-in pour cluster PostgreSQL pour sauvegarder les ressources.



L'utilisation du plug-in pour PostgreSQL offre également les avantages suivants :

* Prise en charge des flux de travail de sauvegarde, de restauration et de clonage
* Sécurité prise en charge par RBAC et délégation de rôles centralisée
+
Vous pouvez également définir les informations d’identification afin que les utilisateurs SnapCenter autorisés disposent d’autorisations au niveau de l’application.

* Création de copies de ressources à faible encombrement et ponctuelles pour les tests ou l'extraction de données à l'aide de la technologie NetApp FlexClone
+
Une licence FlexClone est requise sur le système de stockage sur lequel vous souhaitez créer le clone.

* Prise en charge de la fonctionnalité de snapshot du groupe de cohérence (CG) d' ONTAP dans le cadre de la création de sauvegardes.
* Capacité à exécuter plusieurs sauvegardes simultanément sur plusieurs hôtes de ressources
+
En une seule opération, les snapshots sont consolidés lorsque les ressources d'un seul hôte partagent le même volume.

* Capacité à créer des instantanés à l'aide de commandes externes.
* Prise en charge de Linux LVM sur le système de fichiers XFS.

