---
permalink: install/concept_configure_secured_mysql_connections_with_snapcenter_server.html 
sidebar: sidebar 
keywords: Secure Sockets Layer, secure MYSQL connections, standalone configuration, HA configuration, SSL 
summary: 'Vous pouvez générer des certificats Secure Sockets Layer (SSL) et des fichiers de clés si vous souhaitez sécuriser la communication entre SnapCenter Server et MySQL Server dans des configurations autonomes ou des configurations d"équilibrage de charge réseau (NLB).' 
---
= Configurer des connexions MySQL sécurisées avec SnapCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez générer des certificats Secure Sockets Layer (SSL) et des fichiers de clés si vous souhaitez sécuriser la communication entre SnapCenter Server et MySQL Server dans des configurations autonomes ou des configurations d'équilibrage de charge réseau (NLB).



== Configurer des connexions MySQL sécurisées pour les configurations SnapCenter Server autonomes

Vous pouvez générer des certificats et des fichiers de clés Secure Sockets Layer (SSL) si vous souhaitez sécuriser la communication entre SnapCenter Server et MySQL Server.  Vous devez configurer les certificats et les fichiers de clés dans le serveur MySQL et le serveur SnapCenter .

Les certificats suivants sont générés :

* Certificat CA
* Certificat public du serveur et fichier de clé privée
* Certificat public client et fichier de clé privée


*Mesures*

. Configurez les certificats SSL et les fichiers de clés pour les serveurs et clients MySQL sous Windows à l'aide de la commande openssl.
+
Pour plus d'informations, voir https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-files-using-openssl.html["MySQL version 5.7 : Création de certificats et de clés SSL avec OpenSSL"^]

+

NOTE: La valeur du nom commun utilisée pour le certificat du serveur, le certificat client et les fichiers de clés doit être différente de la valeur du nom commun utilisée pour le certificat de l'autorité de certification.  Si les valeurs de nom commun sont les mêmes, les fichiers de certificat et de clé échouent pour les serveurs compilés à l'aide d'OpenSSL.

+
|===


| *Meilleure pratique :* vous devez utiliser le nom de domaine complet (FQDN) du serveur comme nom commun pour le certificat du serveur. 
|===
. Copiez les certificats SSL et les fichiers clés dans le dossier MySQL Data.
+
Le chemin d'accès par défaut du dossier de données MySQL est `C:\ProgramData\NetApp\SnapCenter\MySQL Data\Data\` .

. Mettez à jour les chemins d'accès au certificat CA, au certificat public du serveur, au certificat public du client, à la clé privée du serveur et à la clé privée du client dans le fichier de configuration du serveur MySQL (my.ini).
+
Le chemin par défaut du fichier de configuration du serveur MySQL (my.ini) est `C:\ProgramData\NetApp\SnapCenter\MySQL Data\my.ini` .

+

NOTE: Vous devez spécifier les chemins d'accès au certificat CA, au certificat public du serveur et à la clé privée du serveur dans la section [mysqld] du fichier de configuration du serveur MySQL (my.ini).

+
Vous devez spécifier les chemins d'accès au certificat CA, au certificat public client et à la clé privée client dans la section [client] du fichier de configuration du serveur MySQL (my.ini).

+
L'exemple suivant montre les certificats et les fichiers de clés copiés dans la section [mysqld] du fichier my.ini dans le dossier par défaut `C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data` .

+
[listing]
----
ssl-ca="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem"
----
+
[listing]
----
ssl-cert="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-cert.pem"
----
+
[listing]
----
ssl-key="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-key.pem"
----
+
L'exemple suivant montre les chemins mis à jour dans la section [client] du fichier my.ini.

+
[listing]
----
ssl-ca="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem"
----
+
[listing]
----
ssl-cert="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-cert.pem"
----
+
[listing]
----
ssl-key="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-key.pem"
----
. Arrêtez l’application Web SnapCenter Server dans Internet Information Server (IIS).
. Redémarrez le service MySQL.
. Mettez à jour la valeur de la clé MySQLProtocol dans le fichier SnapManager.Web.UI.dll.config.
+
L'exemple suivant montre la valeur de la clé MySQLProtocol mise à jour dans le fichier SnapManager.Web.UI.dll.config.

+
[listing]
----
<add key="MySQLProtocol" value="SSL" />
----
. Mettez à jour le fichier SnapManager.Web.UI.dll.config avec les chemins fournis dans la section [client] du fichier my.ini.
+
L'exemple suivant montre les chemins mis à jour dans la section [client] du fichier my.ini.

+
[listing]
----
<add key="ssl-client-cert" value="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-cert.pem" />
----
+
[listing]
----
<add key="ssl-client-key" value="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-key.pem" />
----
+
[listing]
----
<add key="ssl-ca" value="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem" />
----
. Démarrez l’application Web SnapCenter Server dans IIS.




== Configurer des connexions MySQL sécurisées pour les configurations HA

Vous pouvez générer des certificats Secure Sockets Layer (SSL) et des fichiers de clés pour les deux nœuds haute disponibilité (HA) si vous souhaitez sécuriser la communication entre SnapCenter Server et les serveurs MySQL.  Vous devez configurer les certificats et les fichiers de clés dans les serveurs MySQL et sur les nœuds HA.

Les certificats suivants sont générés :

* Certificat CA
+
Un certificat CA est généré sur l’un des nœuds HA et ce certificat CA est copié sur l’autre nœud HA.

* Fichiers de certificat public et de clé privée du serveur pour les deux nœuds HA
* Fichiers de certificat public client et de clé privée client pour les deux nœuds HA


*Mesures*

. Pour le premier nœud HA, configurez les certificats SSL et les fichiers de clés pour les serveurs et clients MySQL sous Windows à l'aide de la commande openssl.
+
Pour plus d'informations, voir https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-files-using-openssl.html["MySQL version 5.7 : Création de certificats et de clés SSL avec OpenSSL"^]

+

NOTE: La valeur du nom commun utilisée pour le certificat du serveur, le certificat client et les fichiers de clés doit être différente de la valeur du nom commun utilisée pour le certificat de l'autorité de certification.  Si les valeurs de nom commun sont les mêmes, les fichiers de certificat et de clé échouent pour les serveurs compilés à l'aide d'OpenSSL.

+
|===


| *Meilleure pratique :* vous devez utiliser le nom de domaine complet (FQDN) du serveur comme nom commun pour le certificat du serveur. 
|===
. Copiez les certificats SSL et les fichiers clés dans le dossier MySQL Data.
+
Le chemin d'accès par défaut au dossier de données MySQL est C:\ProgramData\ NetApp\ SnapCenter\MySQL Data\Data\.

. Mettez à jour les chemins d'accès au certificat CA, au certificat public du serveur, au certificat public du client, à la clé privée du serveur et à la clé privée du client dans le fichier de configuration du serveur MySQL (my.ini).
+
Le chemin d'accès par défaut du fichier de configuration du serveur MySQL (my.ini) est C:\ProgramData\ NetApp\ SnapCenter\MySQL Data\my.ini.

+

NOTE: Vous devez spécifier les chemins d'accès au certificat CA, au certificat public du serveur et à la clé privée du serveur dans la section [mysqld] du fichier de configuration du serveur MySQL (my.ini).

+
Vous devez spécifier les chemins d'accès au certificat CA, au certificat public client et à la clé privée client dans la section [client] du fichier de configuration du serveur MySQL (my.ini).

+
L'exemple suivant montre les certificats et les fichiers de clés copiés dans la section [mysqld] du fichier my.ini dans le dossier par défaut C:/ProgramData/ NetApp/ SnapCenter/MySQL Data/Data.

+
[listing]
----
ssl-ca="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem"
----
+
[listing]
----
ssl-cert="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-cert.pem"
----
+
[listing]
----
ssl-key="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-key.pem"
----
+
L'exemple suivant montre les chemins mis à jour dans la section [client] du fichier my.ini.

+
[listing]
----
ssl-ca="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem"
----
+
[listing]
----
ssl-cert="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-cert.pem"
----
+
[listing]
----
ssl-key="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-key.pem"
----
. Pour le deuxième nœud HA, copiez le certificat CA et générez le certificat public du serveur, les fichiers de clé privée du serveur, le certificat public du client et les fichiers de clé privée du client. Procédez comme suit :
+
.. Copiez le certificat CA généré sur le premier nœud HA dans le dossier MySQL Data du deuxième nœud NLB.
+
Le chemin d'accès par défaut au dossier de données MySQL est C:\ProgramData\ NetApp\ SnapCenter\MySQL Data\Data\.

+

NOTE: Vous ne devez pas créer à nouveau un certificat CA.  Vous devez créer uniquement le certificat public du serveur, le certificat public du client, le fichier de clé privée du serveur et le fichier de clé privée du client.

.. Pour le premier nœud HA, configurez les certificats SSL et les fichiers de clés pour les serveurs et clients MySQL sous Windows à l'aide de la commande openssl.
+
https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-files-using-openssl.html["MySQL version 5.7 : Création de certificats et de clés SSL avec OpenSSL"]

+

NOTE: La valeur du nom commun utilisée pour le certificat du serveur, le certificat client et les fichiers de clés doit être différente de la valeur du nom commun utilisée pour le certificat de l'autorité de certification.  Si les valeurs de nom commun sont les mêmes, les fichiers de certificat et de clé échouent pour les serveurs compilés à l'aide d'OpenSSL.

+
Il est recommandé d'utiliser le nom de domaine complet du serveur comme nom commun pour le certificat du serveur.

.. Copiez les certificats SSL et les fichiers clés dans le dossier MySQL Data.
.. Mettez à jour les chemins d'accès au certificat CA, au certificat public du serveur, au certificat public du client, à la clé privée du serveur et à la clé privée du client dans le fichier de configuration du serveur MySQL (my.ini).
+

NOTE: Vous devez spécifier les chemins d'accès au certificat CA, au certificat public du serveur et à la clé privée du serveur dans la section [mysqld] du fichier de configuration du serveur MySQL (my.ini).

+
Vous devez spécifier les chemins d'accès au certificat CA, au certificat public client et à la clé privée client dans la section [client] du fichier de configuration du serveur MySQL (my.ini).

+
L'exemple suivant montre les certificats et les fichiers de clés copiés dans la section [mysqld] du fichier my.ini dans le dossier par défaut C:/ProgramData/ NetApp/ SnapCenter/MySQL Data/Data.

+
[listing]
----
ssl-ca="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem"
----
+
[listing]
----
ssl-cert="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-cert.pem"
----
+
[listing]
----
ssl-key="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-key.pem"
----
+
L'exemple suivant montre les chemins mis à jour dans la section [client] du fichier my.ini.

+
[listing]
----
ssl-ca="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem"
----
+
[listing]
----
ssl-cert="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-cert.pem"
----
+
[listing]
----
ssl-key="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/server-key.pem"
----


. Arrêtez l’application Web SnapCenter Server dans Internet Information Server (IIS) sur les deux nœuds HA.
. Redémarrez le service MySQL sur les deux nœuds HA.
. Mettez à jour la valeur de la clé MySQLProtocol dans le fichier SnapManager.Web.UI.dll.config pour les deux nœuds HA.
+
L'exemple suivant montre la valeur de la clé MySQLProtocol mise à jour dans le fichier SnapManager.Web.UI.dll.config.

+
[listing]
----
<add key="MySQLProtocol" value="SSL" />
----
. Mettez à jour le fichier SnapManager.Web.UI.dll.config avec les chemins que vous avez spécifiés dans la section [client] du fichier my.ini pour les deux nœuds HA.
+
L'exemple suivant montre les chemins mis à jour dans la section [client] des fichiers my.ini.

+
[listing]
----
<add key="ssl-client-cert" value="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-cert.pem" />
----
+
[listing]
----
<add key="ssl-client-key" value="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/client-key.pem" />
----
+
[listing]
----
<add key="ssl-ca" value="C:/ProgramData/NetApp/SnapCenter/MySQL Data/Data/ca.pem" />
----
. Démarrez l’application Web SnapCenter Server dans IIS sur les deux nœuds HA.
. Utilisez l’applet de commande PowerShell Set-SmRepositoryConfig -RebuildSlave -Force avec l’option -Force sur l’un des nœuds HA pour établir une réplication MySQL sécurisée sur les deux nœuds HA.
+
Même si l'état de réplication est sain, l'option -Force vous permet de reconstruire le référentiel esclave.


