---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: Avant d’effectuer des opérations de protection des données, vous devez configurer les connexions de stockage et ajouter les informations d’identification que le serveur SnapCenter et les plug-ins SnapCenter utiliseront. 
---
= Connexions de stockage et informations d'identification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d’effectuer des opérations de protection des données, vous devez configurer les connexions de stockage et ajouter les informations d’identification que le serveur SnapCenter et les plug-ins SnapCenter utiliseront.



== Connexions de stockage

Les connexions de stockage donnent au serveur SnapCenter et aux plug-ins SnapCenter accès au stockage ONTAP .  La configuration de ces connexions implique également la configuration des fonctionnalités AutoSupport et du système de gestion des événements (EMS).



== Informations d'identification

* Administrateur de domaine ou tout membre du groupe d'administrateurs
+
Indiquez l'administrateur du domaine ou tout membre du groupe d'administrateurs du système sur lequel vous installez le plug-in SnapCenter . Les formats valides pour le champ Nom d'utilisateur sont :

+
** _NetBIOS\Nom d'utilisateur_
** _Domaine FQDN\Nom d'utilisateur_
** _Nom d'utilisateur@upn_


* Administrateur local (pour les groupes de travail uniquement)
+
Pour les systèmes appartenant à un groupe de travail, spécifiez l'administrateur local intégré du système sur lequel vous installez le plug-in SnapCenter . Vous pouvez spécifier un compte utilisateur local appartenant au groupe des administrateurs locaux si ce compte dispose de privilèges élevés ou si la fonctionnalité de contrôle d'accès utilisateur est désactivée sur le système hôte.

+
Le format valide pour le champ Nom d'utilisateur est : _UserName_

* Informations d'identification pour les groupes de ressources individuels
+
Si vous configurez des informations d'identification pour des groupes de ressources individuels et que le nom d'utilisateur ne dispose pas de privilèges d'administrateur complets, vous devez attribuer au moins les privilèges de groupe de ressources et de sauvegarde au nom d'utilisateur.


