---
permalink: install/install_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: install, snapcenter software, install, linux host 
summary: Vous pouvez installer le serveur SnapCenter sur l’hôte Linux. 
---
= Installer le serveur SnapCenter sur un hôte Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez exécuter l’exécutable du programme d’installation de SnapCenter Server pour installer SnapCenter Server.

.Avant de commencer
* Si vous souhaitez installer le serveur SnapCenter à l'aide d'un utilisateur non root qui ne dispose pas de privilèges suffisants pour installer SnapCenter, récupérez le fichier de somme de contrôle sudoers à partir du site de support NetApp .  Vous devez utiliser un fichier de somme de contrôle approprié en fonction de la version Linux.
* Si le package sudo n'est pas disponible dans SUSE Linux, installez le package sudo pour éviter l'échec de l'authentification.
* Pour SUSE Linux, configurez le nom d’hôte pour éviter l’échec de l’installation.
* Vérifiez l’état sécurisé de Linux en exécutant la commande `sestatus` .  Si l'état _SELinux_ est « activé » et que le _mode actuel_ est « en vigueur », procédez comme suit :
+
** Exécutez la commande : `sudo semanage port -a -t http_port_t -p tcp <WEBAPP_EXTERNAL_PORT_>`
+
La valeur par défaut de _WEBAPP_EXTERNAL_PORT_ est 8146

** Si le pare-feu bloque le port, exécutez `sudo firewall-cmd --add-port <WEBAPP_EXTERNAL_PORT_>/tcp`
+
La valeur par défaut de _WEBAPP_EXTERNAL_PORT_ est 8146

** Exécutez les commandes suivantes à partir du répertoire dans lequel vous disposez des autorisations de lecture et d’écriture :
+
*** `sudo ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
+
Si la commande renvoie « rien à faire », réexécutez la commande après avoir installé SnapCenter Server.

*** Si la commande crée _my-nginx.pp_, exécutez la commande pour rendre le package de stratégie actif : `sudo semodule -i my-nginx.pp`


** Le chemin utilisé pour le répertoire MySQL PID est _/var/opt/mysqld_.  Exécutez les commandes suivantes pour définir les autorisations pour l’installation de MySQL.
+
*** `mkdir /var/opt/mysqld`
*** `sudo semanage fcontext -a -t mysqld_var_run_t "/var/opt/mysqld(/.*)?"`
*** `sudo restorecon -Rv /var/opt/mysqld`


** Le chemin utilisé pour le répertoire de données MySQL est _/INSTALL_DIR/ NetApp/snapcenter/SnapManagerWeb/Repository/MySQL/_.  Exécutez les commandes suivantes pour définir les autorisations pour le répertoire de données MySQL.
+
*** `mkdir -p /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`
*** `sudo semanage fcontext -a -t mysqld_db_t "/INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL(/.*)?"`
*** `sudo restorecon -Rv /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`






.À propos de cette tâche
* Lorsque SnapCenter Server est installé sur l'hôte Linux, des services tiers tels que MySQL, RabbitMq, Errlang sont installés.  Vous ne devez pas les désinstaller.
* Le serveur SnapCenter installé sur l'hôte Linux ne prend pas en charge :
+
** Haute disponibilité
** Plugins Windows
** Active Directory (prend en charge uniquement les utilisateurs locaux, à la fois les utilisateurs root et non root avec des informations d'identification)
** Authentification par clé pour se connecter à SnapCenter


* Lors de l'installation de .NET Runtime, si l'installation ne parvient pas à résoudre les dépendances de la bibliothèque _libicu_, installez _libicu_ en exécutant la commande : `yum install -y libicu`
* Si l'installation de SnapCenter Server échoue en raison de la non-disponibilité de _Perl_, installez _Perl_ en exécutant la commande : `yum install -y perl`


.Étapes
. Téléchargez les éléments suivants à partir de https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["Site de support NetApp"^] vers le répertoire _/home_.
+
** Paquet d'installation du serveur SnapCenter - *snapcenter-linux-server-(el8/el9/sles15).bin*
** Fichier de clé publique - *snapcenter_public_key.pub*
** Fichier de signature respectif - *snapcenter-linux-server-(el8/el9/sles15).bin.sig*


. Valider le fichier de signature.
`$openssl dgst -sha256 -verify snapcenter_public_key.pub -signature <path to signature file> <path to bin file>`
. Pour une installation par un utilisateur non root, ajoutez le contenu visudo spécifié dans *snapcenter_server_checksum_(el8/el9/sles15).txt* disponible avec le programme d'installation .bin.
. Attribuer l’autorisation d’exécution pour le programme d’installation .bin.
`chmod +x snapcenter-linux-server-(el8/el9/sles15).bin`
. Effectuez l’une des actions pour installer SnapCenter Server.
+
|===
| Si vous voulez jouer... | Fais ceci... 


 a| 
Installation interactive
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

Vous serez invité à saisir les informations suivantes :

** Le port externe de l'application Web utilisé pour accéder à SnapCenter Server en dehors de l'hôte Linux.  La valeur par défaut est 8146.
** L'utilisateur de SnapCenter Server qui installera SnapCenter Server.
** Le répertoire d'installation où les packages seront installés.




 a| 
Installation non interactive
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DWEBAPP_EXTERNAL_PORT=<port> -DWEBAPP_INTERNAL_PORT=<port> -DSMCORE_PORT=<port> -DSCHEDULER_PORT=<port>  -DSNAPCENTER_SERVER_USER=<user> -DUSER_INSTALL_DIR=<dir> -DINSTALL_LOG_NAME=<filename>`

Exemple : sudo ./snapcenter_linux_server.bin -i silent -DWEBAPP_EXTERNAL_PORT=8146 -DSNAPCENTER_SERVER_USER=root -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=InstallerLog.log

Les journaux seront stockés dans _/var/opt/snapcenter/logs_.

Paramètres à transmettre pour l'installation de SnapCenter Server :

** DWEBAPP_EXTERNAL_PORT : port externe de l'application Web utilisé pour accéder à SnapCenter Server en dehors de l'hôte Linux.  La valeur par défaut est 8146.
** DWEBAPP_INTERNAL_PORT : port interne de l'application Web utilisé pour accéder à SnapCenter Server au sein de l'hôte Linux.  La valeur par défaut est 8147.
** DSMCORE_PORT : port SMCore sur lequel les services smcore sont exécutés.  La valeur par défaut est 8145.
** DSCHEDULER_PORT : port du planificateur sur lequel les services du planificateur s'exécutent.  La valeur par défaut est 8154.
** DSNAPCENTER_SERVER_USER : utilisateur de SnapCenter Server qui installera SnapCenter Server.  Pour _DSNAPCENTER_SERVER_USER_, la valeur par défaut est l'utilisateur exécutant le programme d'installation.
** DUSER_INSTALL_DIR : Répertoire d'installation où les packages seront installés.  Pour _DUSER_INSTALL_DIR_, le répertoire d'installation par défaut est _/opt_.
** DINSTALL_LOG_NAME : Nom du fichier journal dans lequel les journaux d'installation seront stockés.  Il s'agit d'un paramètre facultatif et s'il est spécifié, aucun journal ne sera affiché sur la console. Si vous ne spécifiez pas ce paramètre, les journaux seront affichés sur la console et également stockés dans le fichier journal par défaut.
** DSELINUX : Si le _statut SELinux_ est « activé », le _mode actuel_ est « en vigueur » et que vous avez exécuté les commandes mentionnées dans la section Avant de commencer, vous devez spécifier ce paramètre et lui attribuer la valeur 1.  La valeur par défaut est 0.
** DUPGRADE : La valeur par défaut est 0.  Spécifiez ce paramètre et sa valeur comme n'importe quel entier autre que 0 pour mettre à niveau le serveur SnapCenter .


|===


.Quelle est la prochaine étape ?
* Si le statut _SELinux_ est « activé » et le mode _actuel_ est « en vigueur », le service *nginx* ne parvient pas à démarrer.  Vous devez exécuter les commandes suivantes :
+
.. Accéder au répertoire personnel.
.. Exécutez la commande : `journalctl -x|grep nginx` .
.. Si le port interne de l'application Web (8147) n'est pas autorisé à écouter, exécutez les commandes suivantes :
+
*** `ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
*** `semodule -i my-nginx.pp`


.. Courir `setsebool -P httpd_can_network_connect on`






== Fonctionnalités activées sur l'hôte Linux lors de l'installation

Le serveur SnapCenter installe les packages logiciels ci-dessous qui peuvent aider au dépannage et à la maintenance du système hôte.

* Lapinmq
* Erlang

