---
permalink: install/reference_provision_storage_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: Provision storage, snapcenter 
summary: Si vous ne souhaitez pas utiliser l’interface utilisateur graphique SnapCenter pour effectuer des tâches de provisionnement d’hôte et de récupération d’espace, vous pouvez utiliser les applets de commande PowerShell fournies par SnapCenter Plug-in pour Microsoft Windows.  Vous pouvez utiliser les applets de commande directement ou les ajouter aux scripts. 
---
= Provisionner le stockage à l'aide des applets de commande PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous ne souhaitez pas utiliser l’interface graphique utilisateur SnapCenter pour effectuer des tâches de provisionnement d’hôte et de récupération d’espace, vous pouvez utiliser les applets de commande PowerShell.  Vous pouvez utiliser les applets de commande directement ou les ajouter aux scripts.

Si vous exécutez les applets de commande sur un hôte de plug-in distant, vous devez exécuter l’applet de commande SnapCenter Open-SMConnection pour ouvrir une connexion au serveur SnapCenter .

Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .

Si les applets de commande SnapCenter PowerShell sont endommagées en raison de la suppression de SnapDrive pour Windows du serveur, reportez-vous à https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_cmdlets_broken_when_SnapDrive_for_Windows_is_uninstalled["Les applets de commande SnapCenter sont défectueuses lors de la désinstallation de SnapDrive pour Windows"^] .
