---
permalink: install/task_enable_two_way_ssl.html 
sidebar: sidebar 
keywords: security,disable two-way SSL,enable two-way SSL, windows host 
summary: 'Vous pouvez activer la communication SSL bidirectionnelle pour sécuriser la communication mutuelle entre SnapCenter Server sur l"hôte Windows et les plug-ins à l"aide de commandes PowerShell.' 
---
= Activer la communication SSL bidirectionnelle sur l'hôte Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer la communication SSL bidirectionnelle pour sécuriser la communication mutuelle entre SnapCenter Server sur l'hôte Windows et les plug-ins à l'aide de commandes PowerShell.

*Avant de commencer*

Exécutez d’abord les commandes pour tous les plug-ins et l’agent SMCore, puis pour le serveur.

*Mesures*

. Pour activer la communication SSL bidirectionnelle, exécutez les commandes suivantes sur le serveur SnapCenter pour les plug-ins, le serveur et pour chacun des agents pour lesquels la communication SSL bidirectionnelle est requise.
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName <Plugin_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="true"}`

. Exécutez l’opération de recyclage du pool d’applications IIS SnapCenter à l’aide de la commande suivante.
`> Restart-WebAppPool -Name "SnapCenter"`
. Pour les plug-ins Windows, redémarrez le service SMCore en exécutant la commande PowerShell suivante :
+
`> Restart-Service -Name SnapManagerCoreService`





== Désactiver la communication SSL bidirectionnelle

Vous pouvez désactiver la communication SSL bidirectionnelle à l’aide des commandes PowerShell.

*À propos de cette tâche*

* Exécutez d’abord les commandes pour tous les plug-ins et l’agent SMCore, puis pour le serveur.
* Lorsque vous désactivez la communication SSL bidirectionnelle, le certificat CA et sa configuration ne sont pas supprimés.
* Pour ajouter un nouvel hôte à SnapCenter Server, vous devez désactiver le SSL bidirectionnel pour tous les hôtes de plug-in.
* NLB et F5 ne sont pas pris en charge.


*Mesures*

. Pour désactiver la communication SSL bidirectionnelle, exécutez les commandes suivantes sur SnapCenter Server pour tous les hôtes de plug-in et l'hôte SnapCenter .
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName <Agent_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="false"}`

. Exécutez l’opération de recyclage du pool d’applications IIS SnapCenter à l’aide de la commande suivante.
`> Restart-WebAppPool -Name "SnapCenter"`
. Pour les plug-ins Windows, redémarrez le service SMCore en exécutant la commande PowerShell suivante :
+
`> Restart-Service -Name SnapManagerCoreService`


