---
permalink: install/task_get_the_CA_certificate_thumbprint.html 
sidebar: sidebar 
keywords: SnapCenter, certificate thumbprint 
summary: Une empreinte de certificat est une chaîne hexadécimale qui identifie un certificat.  Une empreinte numérique est calculée à partir du contenu du certificat à l’aide d’un algorithme d’empreinte numérique. 
---
= Obtenir l'empreinte numérique du certificat CA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une empreinte de certificat est une chaîne hexadécimale qui identifie un certificat.  Une empreinte numérique est calculée à partir du contenu du certificat à l’aide d’un algorithme d’empreinte numérique.

.Étapes
. Effectuez les opérations suivantes sur l’interface graphique :
+
.. Double-cliquez sur le certificat.
.. Dans la boîte de dialogue Certificat, cliquez sur l’onglet *Détails*.
.. Faites défiler la liste des champs et cliquez sur *Empreinte digitale*.
.. Copiez les caractères hexadécimaux de la boîte.
.. Supprimez les espaces entre les nombres hexadécimaux.
+
Par exemple, si l'empreinte digitale est : « a9 09 50 2d d8 2a e4 14 33 e6 f8 38 86 b0 0d 42 77 a3 2a 7b », après avoir supprimé les espaces, elle sera : « a909502dd82ae41433e6f83886b00d4277a32a7b ».



. Effectuez les opérations suivantes à partir de PowerShell :
+
.. Exécutez la commande suivante pour répertorier l’empreinte numérique du certificat installé et identifier le certificat récemment installé par le nom du sujet.
+
_Get-ChildItem -Chemin Cert:\LocalMachine\Mon_

.. Copiez l'empreinte digitale.



