---
permalink: install/task_add_storage_systems.html 
sidebar: sidebar 
keywords: add, storage system, SVM, ASA r2 systems 
summary: 'Vous devez configurer le système de stockage qui donne à SnapCenter l"accès au stockage ONTAP pour effectuer des opérations de protection et de provisionnement des données.  Vous pouvez ajouter un SVM autonome ou un cluster comprenant plusieurs SVM.' 
---
= Ajouter des systèmes de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer le système de stockage qui donne à SnapCenter l'accès au stockage ONTAP , aux systèmes ASA r2 ou à Amazon FSx for NetApp ONTAP pour effectuer des opérations de protection et de provisionnement des données.

Vous pouvez ajouter un SVM autonome ou un cluster comprenant plusieurs SVM.  Si vous utilisez Amazon FSx for NetApp ONTAP, vous pouvez soit ajouter un LIF d'administration FSx comprenant plusieurs SVM à l'aide du compte fsxadmin, soit ajouter un SVM FSx dans SnapCenter.

.Avant de commencer
* Vous devez disposer des autorisations requises dans le rôle d’administrateur d’infrastructure pour créer des connexions de stockage.
* Vous devez vous assurer que les installations de plug-ins ne sont pas en cours.
+
Les installations de plug-ins hôtes ne doivent pas être en cours lors de l'ajout d'une connexion au système de stockage, car le cache hôte peut ne pas être mis à jour et l'état des bases de données peut s'afficher dans l'interface graphique SnapCenter comme « Non disponible pour la sauvegarde » ou « Pas sur le stockage NetApp ».

* Les noms des systèmes de stockage doivent être uniques.
+
SnapCenter ne prend pas en charge plusieurs systèmes de stockage portant le même nom sur différents clusters.  Chaque système de stockage pris en charge par SnapCenter doit avoir un nom unique et une adresse IP LIF de données unique.



*À propos de cette tâche*

* Lorsque vous configurez des systèmes de stockage, vous pouvez également activer les fonctionnalités du système de gestion des événements (EMS) et AutoSupport .  L'outil AutoSupport collecte des données sur l'état de votre système et envoie automatiquement les données au support technique NetApp , leur permettant de dépanner votre système.
+
Si vous activez ces fonctionnalités, SnapCenter envoie des informations AutoSupport au système de stockage et des messages EMS au syslog du système de stockage lorsqu'une ressource est protégée, qu'une opération de restauration ou de clonage se termine avec succès ou qu'une opération échoue.

* Si vous prévoyez de répliquer des snapshots vers une destination SnapMirror ou SnapVault , vous devez configurer des connexions au système de stockage pour le SVM ou le cluster de destination ainsi que pour le SVM ou le cluster source.



NOTE: Si vous modifiez le mot de passe du système de stockage, les tâches planifiées, les sauvegardes à la demande et les opérations de restauration peuvent échouer.  Après avoir modifié le mot de passe du système de stockage, vous pouvez mettre à jour le mot de passe en cliquant sur *Modifier* dans l'onglet Stockage.

*Mesures*

. Dans le volet de navigation de gauche, cliquez sur *Systèmes de stockage*.
. Dans la page Systèmes de stockage, cliquez sur *Nouveau*.
. Sur la page Ajouter un système de stockage, fournissez les informations suivantes :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Système de stockage
 a| 
Saisissez le nom du système de stockage ou l’adresse IP.


NOTE: Les noms des systèmes de stockage, à l'exclusion du nom de domaine, doivent comporter 15 caractères ou moins et doivent pouvoir être résolus.  Pour créer des connexions au système de stockage avec des noms comportant plus de 15 caractères, vous pouvez utiliser l’applet de commande Add-SmStorageConnectionPowerShell.


NOTE: Pour les systèmes de stockage avec configuration MetroCluster (MCC), il est recommandé d'enregistrer les clusters locaux et homologues pour des opérations sans interruption.

SnapCenter ne prend pas en charge plusieurs SVM portant le même nom sur différents clusters.  Chaque SVM pris en charge par SnapCenter doit avoir un nom unique.


NOTE: Après avoir ajouté la connexion de stockage à SnapCenter, vous ne devez pas renommer le SVM ou le cluster à l'aide d' ONTAP.


NOTE: Si SVM est ajouté avec un nom court ou un nom de domaine complet, il doit pouvoir être résolu à la fois depuis SnapCenter et depuis l'hôte du plug-in.



 a| 
Nom d'utilisateur/Mot de passe
 a| 
Saisissez les informations d’identification de l’utilisateur de stockage disposant des privilèges requis pour accéder au système de stockage.



 a| 
Système de gestion des événements (EMS) et paramètres AutoSupport
 a| 
Si vous souhaitez envoyer des messages EMS au syslog du système de stockage ou si vous souhaitez que les messages AutoSupport soient envoyés au système de stockage pour la protection appliquée, les opérations de restauration terminées ou les opérations ayant échoué, cochez la case appropriée.

Lorsque vous sélectionnez la case à cocher *Envoyer une notification AutoSupport pour les opérations ayant échoué au système de stockage*, la case à cocher *Consigner les événements SnapCenter Server dans syslog* est également sélectionnée, car la messagerie EMS est requise pour activer les notifications AutoSupport .

|===
. Cliquez sur *Plus d'options* si vous souhaitez modifier les valeurs par défaut attribuées à la plateforme, au protocole, au port et au délai d'expiration.
+
.. Dans Plateforme, sélectionnez l’une des options dans la liste déroulante.
+
Si le SVM est le système de stockage secondaire dans une relation de sauvegarde, cochez la case *Secondaire*.  Lorsque l'option *Secondaire* est sélectionnée, SnapCenter n'effectue pas de vérification de licence immédiatement.

+
Si vous avez ajouté SVM dans SnapCenter , l'utilisateur doit sélectionner manuellement le type de plate-forme dans la liste déroulante.

.. Dans Protocole, sélectionnez le protocole qui a été configuré lors de la configuration de SVM ou du cluster, généralement HTTPS.
.. Entrez le port accepté par le système de stockage.
+
Le port par défaut 443 fonctionne généralement.

.. Saisissez le temps en secondes qui doit s'écouler avant que les tentatives de communication ne soient interrompues.
+
La valeur par défaut est de 60 secondes.

.. Si le SVM dispose de plusieurs interfaces de gestion, cochez la case *IP préférée*, puis saisissez l'adresse IP préférée pour les connexions SVM.
.. Cliquez sur *Enregistrer*.


. Cliquez sur *Soumettre*.


*Résultat*

Dans la page Systèmes de stockage, à partir de la liste déroulante *Type*, effectuez l'une des actions suivantes :

* Sélectionnez * ONTAP SVMs* si vous souhaitez afficher tous les SVM qui ont été ajoutés.
+
Si vous avez ajouté des SVM FSx, les SVM FSx sont répertoriés ici.

* Sélectionnez * Clusters ONTAP * si vous souhaitez afficher tous les clusters qui ont été ajoutés.
+
Si vous avez ajouté des clusters FSx à l'aide de fsxadmin, les clusters FSx sont répertoriés ici.

+
Lorsque vous cliquez sur le nom du cluster, toutes les SVM qui font partie du cluster s'affichent dans la section Machines virtuelles de stockage.

+
Si une nouvelle SVM est ajoutée au cluster ONTAP à l'aide de l'interface graphique utilisateur ONTAP , cliquez sur *Redécouvrir* pour afficher la SVM nouvellement ajoutée.



*Après avoir fini*

Un administrateur de cluster doit activer AutoSupport sur chaque nœud de système de stockage pour envoyer des notifications par e-mail à partir de tous les systèmes de stockage auxquels SnapCenter a accès, en exécutant la commande suivante à partir de la ligne de commande du système de stockage :

`autosupport trigger modify -node nodename -autosupport-message client.app.info -to enable -noteto enable`


NOTE: L'administrateur de la machine virtuelle de stockage (SVM) n'a pas accès à AutoSupport.
