---
permalink: protect-scu/concept_overview_snapcenter_plug_in_for_UNIX_file_systems.html 
sidebar: sidebar 
keywords: overview, unix file system, plug-in for unix file system, backup, restore, clone 
summary: Le plug-in pour les systèmes de fichiers Unix prend en charge la sauvegarde, la restauration et le clonage des systèmes de fichiers Unix. 
---
= Ce que vous pouvez faire avec le plug-in SnapCenter pour les systèmes de fichiers Unix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque le plug-in pour les systèmes de fichiers Unix est installé dans votre environnement, vous pouvez utiliser SnapCenter pour sauvegarder, restaurer et cloner des systèmes de fichiers Unix.  Vous pouvez également effectuer des tâches prenant en charge ces opérations.

* Découvrir les ressources
* Sauvegarder les systèmes de fichiers Unix
* Planifier des opérations de sauvegarde
* Restaurer les sauvegardes du système de fichiers
* Cloner les sauvegardes du système de fichiers
* Surveiller les opérations de sauvegarde, de restauration et de clonage




== Configurations prises en charge

|===
| Article | Configuration prise en charge 


 a| 
Environnements
 a| 
* Serveur physique
* Serveur virtuel
+
Banques de données vVol sur NFS et SAN. La banque de données vVol ne peut être provisionnée qu'avec ONTAP Tools pour VMware vSphere.





 a| 
Systèmes d'exploitation
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* Serveur d'entreprise SUSE Linux (SLES)




 a| 
Systèmes de fichiers
 a| 
* SAN:
+
** Systèmes de fichiers basés et non basés sur LVM
** LVM sur VMDK ext3, ext4 et xfs


* NFS : NFS v3, NFS v4.x




 a| 
Protocoles
 a| 
* FC
* FCoE
* iSCSI
* NFS




 a| 
Trajets multiples
 a| 
Oui

|===


== Limites

* La combinaison de RDM et de disques virtuels dans un groupe de volumes n'est pas prise en charge.
* La restauration au niveau des fichiers n'est pas prise en charge.
+
Cependant, vous pouvez effectuer manuellement une restauration au niveau des fichiers en clonant la sauvegarde, puis en copiant les fichiers manuellement.

* Le mélange de systèmes de fichiers répartis sur des VMDK provenant à la fois de banques de données NFS et VMFS n'est pas pris en charge.
* NVMe n'est pas pris en charge.
* Le provisionnement n'est pas pris en charge.




== Caractéristiques

* Permet au plug-in pour Oracle Database d'effectuer des opérations de protection des données sur les bases de données Oracle en gérant la pile de stockage hôte sous-jacente sur les systèmes Linux ou AIX
* Prend en charge les protocoles Network File System (NFS) et Storage Area Network (SAN) sur un système de stockage exécutant ONTAP.
* Pour les systèmes Linux, les bases de données Oracle sur les LUN VMDK et RDM sont prises en charge lorsque vous déployez le SnapCenter Plug-in for VMware vSphere et enregistrez le plug-in auprès de SnapCenter.
* Prend en charge Mount Guard pour AIX sur les systèmes de fichiers SAN et la disposition LVM.
* Prend en charge le système de fichiers journalisé amélioré (JFS2) avec journalisation en ligne sur les systèmes de fichiers SAN et la disposition LVM pour les systèmes AIX uniquement.
+
Les périphériques SAN natifs, les systèmes de fichiers et les dispositions LVM créés sur des périphériques SAN sont pris en charge.

* Automatise les opérations de sauvegarde, de restauration et de clonage prenant en charge les applications pour les systèmes de fichiers UNIX dans votre environnement SnapCenter

