---
permalink: protect-scu/task_determine_whether_unix_file_systems_are_available_for_backup.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for UNIX file systems, discovery,file systems, UNIX, Unix file systems 
summary: 'Après l"installation du plug-in pour les systèmes de fichiers Unix, les systèmes de fichiers sur l"hôte sont automatiquement découverts et affichés dans la page Ressources.' 
---
= Découvrez les systèmes de fichiers UNIX disponibles pour la sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après l’installation du plug-in, tous les systèmes de fichiers sur cet hôte sont automatiquement découverts et affichés dans la page Ressources.  Vous pouvez ajouter ces systèmes de fichiers à des groupes de ressources pour effectuer des opérations de protection des données.

.Avant de commencer
* Vous devez avoir effectué des tâches telles que l’installation du serveur SnapCenter , l’ajout d’hôtes et la création de connexions au système de stockage.
* Si les systèmes de fichiers résident sur un disque de machine virtuelle (VMDK) ou un mappage de périphériques bruts (RDM), vous devez déployer le SnapCenter Plug-in for VMware vSphere et enregistrer le plug-in auprès de SnapCenter.
+
Pour plus d'informations, consultez la section  https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html["Déployer le SnapCenter Plug-in for VMware vSphere"^] .



.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Ressources*, puis sélectionnez le plug-in approprié dans la liste.
. Dans la page Ressources, sélectionnez *Chemin* dans la liste Affichage.
. Cliquez sur *Actualiser les ressources*.
+
Les systèmes de fichiers sont affichés avec des informations telles que le type, le nom d'hôte, les groupes de ressources et les politiques associés, ainsi que l'état.


