---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: Créez une politique de sauvegarde pour les systèmes de fichiers Unix que vous souhaitez sauvegarder. 
---
= Créer des politiques de sauvegarde pour les systèmes de fichiers Unix
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser SnapCenter pour sauvegarder des systèmes de fichiers Unix, vous devez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources que vous souhaitez sauvegarder.  Une politique de sauvegarde est un ensemble de règles qui régissent la manière dont vous gérez, planifiez et conservez les sauvegardes.  Vous pouvez également spécifier les paramètres de réplication, de script et de type de sauvegarde.  La création d’une politique permet de gagner du temps lorsque vous souhaitez réutiliser la politique sur une autre ressource ou un autre groupe de ressources.

.Avant de commencer
* Vous devez vous préparer à la protection des données en effectuant des tâches telles que l'installation de SnapCenter, l'ajout d'hôtes, la découverte des systèmes de fichiers et la création de connexions au système de stockage.
* Si vous répliquez des snapshots vers un stockage secondaire miroir ou coffre, l'administrateur SnapCenter doit vous avoir attribué les SVM pour les volumes source et de destination.
* Consultez les conditions préalables et les limitations spécifiques à la synchronisation active de SnapMirror . Pour plus d'informations, reportez-vous à https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limites d'objets pour la synchronisation active de SnapMirror"] .


.À propos de cette tâche
* SnapLock
+
** Si l'option « Conserver les copies de sauvegarde pendant un nombre de jours spécifique » est sélectionnée, la période de conservation de SnapLock doit être inférieure ou égale aux jours de conservation mentionnés.
+
La spécification d'une période de verrouillage des instantanés empêche la suppression des instantanés jusqu'à l'expiration de la période de conservation. Cela pourrait conduire à conserver un nombre d’instantanés supérieur au nombre spécifié dans la politique.

+
Pour ONTAP 9.12.1 et les versions antérieures, les clones créés à partir des instantanés SnapLock Vault dans le cadre de la restauration hériteront du délai d'expiration de SnapLock Vault. L'administrateur de stockage doit nettoyer manuellement les clones après l'expiration de SnapLock .





.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Politiques*.
. Sélectionnez *Systèmes de fichiers Unix* dans la liste déroulante.
. Cliquez sur *Nouveau*.
. Dans la page Nom, saisissez le nom et les détails de la politique.
. Dans la page Sauvegarde et réplication, effectuez les actions suivantes :
+
.. Spécifiez les paramètres de sauvegarde.
.. Spécifiez la fréquence de planification en sélectionnant *À la demande*, *Toutes les heures*, *Quotidien*, *Hebdomadaire* ou *Mensuel*.
.. Dans la section Sélectionner les options de réplication secondaire, sélectionnez l’une ou les deux options de réplication secondaire suivantes :


+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Mettre à jour SnapMirror après avoir créé une copie Snapshot locale
 a| 
Sélectionnez ce champ pour créer des copies miroir des jeux de sauvegarde sur un autre volume (réplication SnapMirror ).

Cette option doit être activée pour la synchronisation active de SnapMirror .



 a| 
Mettre à jour SnapVault après avoir créé une copie Snapshot locale
 a| 
Sélectionnez cette option pour effectuer une réplication de sauvegarde de disque à disque (sauvegardes SnapVault ).



 a| 
Nombre de tentatives d'erreur
 a| 
Saisissez le nombre maximal de tentatives de réplication pouvant être autorisées avant l’arrêt de l’opération.

|===
. Dans la page Rétention, spécifiez les paramètres de rétention pour le type de sauvegarde et le type de planification sélectionné dans la page Sauvegarde et réplication :
+
|===


| Si vous voulez... | Alors... 


 a| 
Conserver un certain nombre de clichés
 a| 
Sélectionnez *Copies à conserver*, puis spécifiez le nombre d’instantanés que vous souhaitez conserver.

Si le nombre d'instantanés dépasse le nombre spécifié, les instantanés sont supprimés, les copies les plus anciennes étant supprimées en premier.


NOTE: La valeur de rétention maximale est de 1018. Les sauvegardes échoueront si la rétention est définie sur une valeur supérieure à celle prise en charge par la version ONTAP sous-jacente.


IMPORTANT: Vous devez définir le nombre de rétention sur 2 ou plus si vous prévoyez d'activer la réplication SnapVault .  Si vous définissez le nombre de rétention sur 1, l'opération de rétention peut échouer car le premier instantané est l'instantané de référence pour la relation SnapVault jusqu'à ce qu'un instantané plus récent soit répliqué sur la cible.



 a| 
Conservez les instantanés pendant un certain nombre de jours
 a| 
Sélectionnez *Conserver les copies pendant*, puis spécifiez le nombre de jours pendant lesquels vous souhaitez conserver les instantanés avant de les supprimer.



 a| 
Période de verrouillage de la copie instantanée
 a| 
Sélectionnez *Période de verrouillage de la copie instantanée* et spécifiez la durée en jours, mois ou années.

La période de rétention du Snaplock doit être inférieure à 100 ans.

|===
. Sélectionnez l'étiquette de la politique.
+

NOTE: Vous pouvez attribuer des étiquettes SnapMirror aux snapshots principaux pour la réplication à distance, permettant ainsi aux snapshots principaux de décharger l'opération de réplication de snapshot de SnapCenter vers les systèmes secondaires ONTAP . Cela peut être fait sans activer l’option SnapMirror ou SnapVault dans la page de politique.

. Dans la page Script, entrez le chemin et les arguments du prescript ou du postscript que vous souhaitez exécuter respectivement avant ou après l'opération de sauvegarde.
+

NOTE: Vous devez vérifier si les commandes existent dans la liste de commandes disponible sur l'hôte du plug-in à partir du chemin _ /opt/ NetApp/snapcenter/scc/etc/allowed_commands.config_.

+
Vous pouvez également spécifier la valeur du délai d’expiration du script. La valeur par défaut est de 60 secondes.

. Consultez le résumé, puis cliquez sur *Terminer*.

