---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'Avant d"utiliser SnapCenter pour sauvegarder les ressources de base de données IBM Db2, vous devez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources que vous souhaitez sauvegarder.  Une politique de sauvegarde est un ensemble de règles qui régissent la manière dont vous gérez, planifiez et conservez les sauvegardes.' 
---
= Créer des politiques de sauvegarde pour IBM Db2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser SnapCenter pour sauvegarder les ressources IBM Db2, vous devez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources que vous souhaitez sauvegarder.  Une politique de sauvegarde est un ensemble de règles qui régissent la manière dont vous gérez, planifiez et conservez les sauvegardes.

.Avant de commencer
* Vous devez avoir défini votre stratégie de sauvegarde.
+
Pour plus de détails, consultez les informations sur la définition d'une stratégie de protection des données pour les bases de données IBM Db2.

* Vous devez vous préparer à la protection des données en effectuant des tâches telles que l'installation de SnapCenter, l'ajout d'hôtes, la configuration des connexions au système de stockage et l'ajout de ressources.
* L'administrateur SnapCenter doit vous avoir attribué les SVM pour les volumes source et de destination si vous répliquez des snapshots vers un miroir ou un coffre.
+
En outre, vous pouvez spécifier les paramètres de réplication, de script et d’application dans la politique.  Ces options permettent de gagner du temps lorsque vous souhaitez réutiliser la politique pour un autre groupe de ressources.



.À propos de cette tâche
* SnapLock
+
** Si l'option « Conserver les copies de sauvegarde pendant un nombre de jours spécifique » est sélectionnée, la période de conservation de SnapLock doit être inférieure ou égale aux jours de conservation mentionnés.
** La spécification d'une période de verrouillage des instantanés empêche la suppression des instantanés jusqu'à l'expiration de la période de conservation.  Cela pourrait conduire à conserver un nombre d’instantanés supérieur au nombre spécifié dans la politique.
** Pour ONTAP 9.12.1 et les versions antérieures, les clones créés à partir des snapshots SnapLock Vault dans le cadre de la restauration hériteront du délai d'expiration de SnapLock Vault. L'administrateur de stockage doit nettoyer manuellement les clones après l'expiration de SnapLock .




.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Politiques*.
. Cliquez sur *Nouveau*.
. Dans la page Nom, saisissez le nom et les détails de la politique.
. Dans la page Type de politique, procédez comme suit :
+
.. Sélectionnez le type de stockage.
.. Dans la section *Paramètres de sauvegarde personnalisés*, indiquez tous les paramètres de sauvegarde spécifiques qui doivent être transmis au plug-in au format clé-valeur.
+
Vous pouvez fournir plusieurs clés-valeurs à transmettre au plug-in.



. Dans la page Instantané et réplication, effectuez les actions suivantes.
+
.. Spécifiez la fréquence de planification en sélectionnant *À la demande*, *Toutes les heures*, *Quotidien*, *Hebdomadaire* ou *Mensuel*.
+

NOTE: Vous pouvez spécifier la planification (date de début, date de fin et fréquence) de l'opération de sauvegarde lors de la création d'un groupe de ressources.  Cela vous permet de créer des groupes de ressources qui partagent la même politique et la même fréquence de sauvegarde, mais vous permet également d'attribuer des planifications de sauvegarde différentes à chaque politique.

+

NOTE: Si vous avez programmé à 2 h 00 du matin, la planification ne sera pas déclenchée pendant l'heure d'été (DST).

.. Dans la section Paramètres d’instantané, effectuez les actions suivantes :
+
|===
| Si vous voulez... | Alors... 


 a| 
Conserver un certain nombre d'instantanés
 a| 
Sélectionnez *Copies à conserver*, puis spécifiez le nombre d’instantanés que vous souhaitez conserver.

Si le nombre d'instantanés dépasse le nombre spécifié, les instantanés sont supprimés, les copies les plus anciennes étant supprimées en premier.



 a| 
Conservez les instantanés pendant un certain nombre de jours
 a| 
Sélectionnez *Conserver les copies pendant*, puis spécifiez le nombre de jours pendant lesquels vous souhaitez conserver les instantanés avant de les supprimer.



 a| 
Période de verrouillage de la copie instantanée
 a| 
Sélectionnez *Période de verrouillage de la copie instantanée* et spécifiez les jours, les mois ou les années.

La période de rétention du Snaplock doit être inférieure à 100 ans.

|===
+

IMPORTANT: Pour les sauvegardes basées sur des copies Snapshot, vous devez définir le nombre de rétention sur 2 ou plus si vous prévoyez d'activer la réplication SnapVault .  Si vous définissez le nombre de rétention sur 1, l'opération de rétention peut échouer car le premier instantané est l'instantané de référence pour la relation SnapVault jusqu'à ce qu'un instantané plus récent soit répliqué sur la cible.

.. Spécifiez l’étiquette de la politique.
+
Vous pouvez attribuer des étiquettes SnapMirror aux snapshots principaux pour la réplication à distance, permettant ainsi aux snapshots principaux de décharger l'opération de réplication de snapshot de SnapCenter vers les systèmes secondaires ONTAP . Cela peut être fait sans activer l’option SnapMirror ou SnapVault dans la page de politique.



. Dans la section Sélectionner les options de réplication secondaire, sélectionnez l’une ou les deux options de réplication secondaire suivantes :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Mettre à jour SnapMirror après avoir créé une copie Snapshot locale
 a| 
Sélectionnez ce champ pour créer des copies miroir des jeux de sauvegarde sur un autre volume (réplication SnapMirror ).

Cette option doit être activée pour la synchronisation active de SnapMirror .



 a| 
Mettre à jour SnapVault après avoir créé une copie Snapshot locale
 a| 
Sélectionnez cette option pour effectuer une réplication de sauvegarde de disque à disque (sauvegardes SnapVault ).



 a| 
Nombre de tentatives d'erreur
 a| 
Saisissez le nombre maximal de tentatives de réplication pouvant être autorisées avant l’arrêt de l’opération.

|===
+

NOTE: Vous devez configurer la stratégie de rétention SnapMirror dans ONTAP pour le stockage secondaire afin d’éviter d’atteindre la limite maximale de snapshots sur le stockage secondaire.

. Consultez le résumé, puis cliquez sur *Terminer*.

