---
permalink: protect-nsp/backup_schedules_of_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: NetApp supported plug-in 
summary: 'Le facteur le plus critique dans la détermination d’un calendrier de sauvegarde est le taux de changement de la ressource.  Plus vous sauvegardez souvent vos ressources, moins SnapCenter doit utiliser de journaux d"archive pour la restauration, ce qui peut entraîner des opérations de restauration plus rapides.' 
---
= Planifications de sauvegarde des ressources de plug-in prises en charge par NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le facteur le plus critique dans la détermination d’un calendrier de sauvegarde est le taux de changement de la ressource.  Plus vous sauvegardez souvent vos ressources, moins SnapCenter doit utiliser de journaux d'archive pour la restauration, ce qui peut entraîner des opérations de restauration plus rapides.

Vous pouvez sauvegarder une ressource très utilisée toutes les heures, tandis que vous pouvez sauvegarder une ressource rarement utilisée une fois par jour.  D’autres facteurs incluent l’importance de la ressource pour votre organisation, votre contrat de niveau de service (SLA) et votre objectif de point de récupération (RPO).

Le SLA définit le niveau de service attendu et aborde de nombreux problèmes liés au service, notamment la disponibilité et les performances du service.  Le RPO définit la stratégie relative à l'âge des fichiers qui doivent être récupérés à partir du stockage de sauvegarde pour que les opérations régulières reprennent après une panne.  SLA et RPO contribuent à la stratégie de protection des données.

Les planifications de sauvegarde comportent deux parties, comme suit :

* Fréquence de sauvegarde
+
La fréquence de sauvegarde (la fréquence à laquelle les sauvegardes doivent être effectuées), également appelée type de planification pour certains plug-ins, fait partie d'une configuration de politique.  Par exemple, vous pouvez configurer la fréquence de sauvegarde sur une base horaire, quotidienne, hebdomadaire ou mensuelle.  Vous pouvez accéder aux politiques dans l'interface graphique SnapCenter en cliquant sur *Paramètres* > *Politiques*.

* Planifications de sauvegarde
+
Les planifications de sauvegarde (le moment exact où les sauvegardes doivent être effectuées) font partie d'une configuration de ressource ou de groupe de ressources.  Par exemple, si vous disposez d'un groupe de ressources avec une politique configurée pour des sauvegardes hebdomadaires, vous pouvez configurer la planification pour effectuer une sauvegarde tous les jeudis à 22h00. Vous pouvez accéder aux planifications des groupes de ressources dans l'interface utilisateur graphique de SnapCenter en cliquant sur *Ressources*, puis en sélectionnant le plug-in approprié et en cliquant sur *Affichage* > *Groupe de ressources*.


