---
permalink: protect-nsp/create_policies_for_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: create policies, NetApp supported plug-in 
summary: 'Avant d"utiliser SnapCenter pour sauvegarder des ressources spécifiques aux plug-ins pris en charge par NetApp , vous devez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources que vous souhaitez sauvegarder.' 
---
= Créer des politiques pour les ressources de plug-in prises en charge par NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser SnapCenter pour sauvegarder des ressources spécifiques aux plug-ins pris en charge par NetApp , vous devez créer une stratégie de sauvegarde pour la ressource ou le groupe de ressources que vous souhaitez sauvegarder.

.Avant de commencer
* Vous devriez avoir défini votre stratégie de sauvegarde.
+
Pour plus de détails, consultez les informations sur la définition d'une stratégie de protection des données pour les plug-ins pris en charge par NetApp .

* Vous auriez dû vous préparer à la protection des données.
+
La préparation de la protection des données comprend des tâches telles que l’installation de SnapCenter, l’ajout d’hôtes, la création de connexions au système de stockage et l’ajout de ressources.

* Les machines virtuelles de stockage (SVM) doivent vous être attribuées pour les opérations de mise en miroir ou de coffre-fort.
+
L'administrateur SnapCenter doit vous avoir attribué les SVM pour les volumes source et de destination si vous répliquez des snapshots vers un miroir ou un coffre.

* Vous auriez dû ajouter manuellement les ressources que vous souhaitez protéger.


.À propos de cette tâche
* Une politique de sauvegarde est un ensemble de règles qui régissent la manière dont vous gérez, planifiez et conservez les sauvegardes.  De plus, vous pouvez spécifier les paramètres de réplication, de script et d'application.
* La spécification d’options dans une stratégie permet de gagner du temps lorsque vous souhaitez réutiliser la stratégie pour un autre groupe de ressources.
* SnapLock
+
** Si l'option « Conserver les copies de sauvegarde pendant un nombre de jours spécifique » est sélectionnée, la période de conservation de SnapLock doit être inférieure ou égale aux jours de conservation mentionnés.
** La spécification d'une période de verrouillage des instantanés empêche la suppression des instantanés jusqu'à l'expiration de la période de conservation. Cela pourrait conduire à conserver un nombre d’instantanés supérieur au nombre spécifié dans la politique.
** Pour ONTAP 9.12.1 et les versions antérieures, les clones créés à partir des instantanés SnapLock Vault dans le cadre de la restauration hériteront du délai d'expiration de SnapLock Vault. L'administrateur de stockage doit nettoyer manuellement les clones après l'expiration de SnapLock .





NOTE: Les paramètres SnapLock principaux sont gérés dans la politique de sauvegarde SnapCenter et les paramètres SnapLock secondaires sont gérés par ONTAP.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Politiques*.
. Cliquez sur *Nouveau*.
. Dans la page Nom, saisissez le nom et les détails de la politique.
. Dans la page Type de politique, procédez comme suit :
+
.. Sélectionnez le type de stockage.
.. Dans la section Paramètres de sauvegarde personnalisés, indiquez tous les paramètres de sauvegarde spécifiques qui doivent être transmis au plug-in au format clé-valeur.
+
Vous pouvez fournir plusieurs clés-valeurs à transmettre au plug-in.



. Dans la page Instantané et réplication, effectuez les étapes suivantes :
+
.. Spécifiez le type de planification en sélectionnant *À la demande*, *Toutes les heures*, *Quotidien*, *Hebdomadaire* ou *Mensuel*.
+

NOTE: Vous pouvez spécifier la planification (date de début, date de fin et fréquence) de l'opération de sauvegarde lors de la création d'un groupe de ressources.  Cela vous permet de créer des groupes de ressources qui partagent la même politique et la même fréquence de sauvegarde, mais vous permet d'attribuer des planifications de sauvegarde différentes à chaque politique.

+

NOTE: Si vous avez programmé à 2 h 00 du matin, la planification ne sera pas déclenchée pendant l'heure d'été (DST).

.. Dans la section Paramètres d'instantané, spécifiez les paramètres de conservation pour le type de sauvegarde et le type de planification sélectionné dans la page *Type de sauvegarde* :
+
|===
| Si vous voulez... | Alors... 


 a| 
Conserver un certain nombre de clichés
 a| 
Sélectionnez *Copies à conserver*, puis spécifiez le nombre d’instantanés que vous souhaitez conserver.

Si le nombre d'instantanés dépasse le nombre spécifié, les instantanés sont supprimés, les copies les plus anciennes étant supprimées en premier.


NOTE: Vous devez définir le nombre de rétention sur 2 ou plus si vous prévoyez d'activer la réplication SnapVault .  Si vous définissez le nombre de rétention sur 1, l'opération de rétention peut échouer car le premier instantané est l'instantané de référence pour la relation SnapVault jusqu'à ce qu'un instantané plus récent soit répliqué sur la cible.


NOTE: La valeur de rétention maximale est de 1018. Les sauvegardes échoueront si la rétention est définie sur une valeur supérieure à celle prise en charge par la version ONTAP sous-jacente.



 a| 
Conservez les instantanés pendant un certain nombre de jours
 a| 
Sélectionnez *Conserver les copies pendant*, puis spécifiez le nombre de jours pendant lesquels vous souhaitez conserver les instantanés avant de les supprimer.



 a| 
Période de verrouillage de la copie instantanée
 a| 
Sélectionnez *Période de verrouillage de la copie instantanée* et spécifiez les jours, les mois ou les années.

La période de conservation de SnapLock doit être inférieure à 100 ans.

|===
.. Sélectionnez une étiquette de politique.
+

NOTE: Vous pouvez attribuer des étiquettes SnapMirror aux snapshots principaux pour la réplication à distance, permettant ainsi aux snapshots principaux de décharger l'opération de réplication de snapshot de SnapCenter vers les systèmes secondaires ONTAP . Cela peut être fait sans activer l’option SnapMirror ou SnapVault dans la page de politique.



. Dans la section Sélectionner les options de réplication secondaire, sélectionnez l’une ou les deux options de réplication secondaire suivantes :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
*Mettre à jour SnapMirror après avoir créé une copie Snapshot locale*
 a| 
Sélectionnez ce champ pour créer des copies miroir des jeux de sauvegarde sur un autre volume (réplication SnapMirror ).

Si la relation de protection dans ONTAP est de type Miroir et Coffre-fort et si vous sélectionnez uniquement cette option, le snapshot créé sur le primaire ne sera pas transféré vers la destination, mais sera répertorié dans la destination.  Si cet instantané est sélectionné à partir de la destination pour effectuer une opération de restauration, le message d'erreur suivant s'affiche : L'emplacement secondaire n'est pas disponible pour la sauvegarde en miroir/en coffre sélectionnée.

Lors de la réplication secondaire, l’heure d’expiration de SnapLock charge l’heure d’expiration de SnapLock principale.

Cliquer sur le bouton *Actualiser* dans la page Topologie actualise l'heure d'expiration du SnapLock secondaire et principal récupérée à partir d' ONTAP.

Voir link:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["Afficher les sauvegardes et les clones liés aux ressources des plug-ins pris en charge par NetApp dans la page Topologie"] .



 a| 
*Mettre à jour SnapVault après avoir créé une copie Snapshot locale*
 a| 
Sélectionnez cette option pour effectuer une réplication de sauvegarde de disque à disque (sauvegardes SnapVault ).

Lors de la réplication secondaire, l’heure d’expiration de SnapLock charge l’heure d’expiration de SnapLock principale.  Cliquer sur le bouton *Actualiser* dans la page Topologie actualise l'heure d'expiration du SnapLock secondaire et principal récupérée à partir d' ONTAP.

Lorsque SnapLock est configuré uniquement sur le secondaire d' ONTAP appelé SnapLock Vault, cliquer sur le bouton *Actualiser* dans la page Topologie actualise la période de verrouillage sur le secondaire récupéré à partir d' ONTAP.

Pour plus d'informations sur SnapLock Vault, consultez Valider les instantanés sur WORM sur une destination de coffre-fort.

Voir link:view_netapp_supported_plugins_resource_backups_and_clones_in_the_topology_page.html["Afficher les sauvegardes et les clones liés aux ressources des plug-ins pris en charge par NetApp dans la page Topologie"] .



 a| 
*Erreur lors du nombre de tentatives*
 a| 
Saisissez le nombre maximal de tentatives de réplication pouvant être autorisées avant l’arrêt de l’opération.

|===
+

NOTE: Vous devez configurer la stratégie de rétention SnapMirror dans ONTAP pour le stockage secondaire afin d’éviter d’atteindre la limite maximale de snapshots sur le stockage secondaire.

. Consultez le résumé, puis cliquez sur *Terminer*.

