---
permalink: protect-nsp/host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Vous devez vous assurer que l"hôte répond aux exigences avant d"installer le package de plug-ins SnapCenter pour Linux.' 
---
= Configuration requise pour l'installation du package de plug-ins SnapCenter pour Linux et AIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez vous assurer que l'hôte répond aux exigences avant d'installer le package de plug-ins SnapCenter pour Linux ou AIX.


NOTE: Les applications de stockage et Oracle sont prises en charge sur AIX.

|===
| Article | Exigences 


 a| 
Systèmes d'exploitation
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* Serveur d'entreprise SUSE Linux (SLES)




 a| 
RAM minimale pour le plug-in SnapCenter sur l'hôte
 a| 
1 Go



 a| 
Espace minimum d'installation et de journalisation pour le plug-in SnapCenter sur l'hôte
 a| 
2 Go


NOTE: Vous devez allouer suffisamment d’espace disque et surveiller la consommation de stockage par le dossier des journaux.  L'espace journal requis varie en fonction du nombre d'entités à protéger et de la fréquence des opérations de protection des données.  S'il n'y a pas suffisamment d'espace disque, les journaux ne seront pas créés pour les opérations récemment exécutées.



 a| 
Logiciels requis
 a| 
Java 11 Oracle Java ou OpenJDK

Si vous avez mis à niveau JAVA vers la dernière version, vous devez vous assurer que l'option JAVA_HOME située dans /var/opt/snapcenter/spl/etc/spl.properties est définie sur la version JAVA correcte et le chemin correct.

|===
Pour obtenir les dernières informations sur les versions prises en charge, consultez le https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Outil de matrice d'interopérabilité NetApp"]
