---
permalink: protect-nsp/prerequisites_for_using_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: Credentials 
summary: 'Avant d"utiliser les plug-ins pris en charge par SnapCenter NetApp , l"administrateur SnapCenter doit installer et configurer le serveur SnapCenter et effectuer les tâches préalables.' 
---
= Conditions préalables à l'utilisation des plug-ins pris en charge par NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser les plug-ins pris en charge par SnapCenter NetApp , l'administrateur SnapCenter doit installer et configurer le serveur SnapCenter et effectuer les tâches préalables.

* Installer et configurer SnapCenter Server.
* Connectez-vous au serveur SnapCenter .
* Configurez l’environnement SnapCenter en ajoutant des connexions au système de stockage et en créant des informations d’identification, le cas échéant.
* Ajoutez des hôtes, puis installez et téléchargez les plug-ins.
* Le cas échéant, installez Java 11 sur l’hôte du plug-in.
* Si vous disposez de plusieurs chemins de données (LIF) ou d'une configuration dNFS, vous pouvez effectuer les opérations suivantes à l'aide de la CLI SnapCenter sur l'hôte de la base de données :
+
** Par défaut, toutes les adresses IP de l'hôte de la base de données sont ajoutées à la stratégie d'exportation de stockage NFS dans la machine virtuelle de stockage (SVM) pour les volumes clonés.  Si vous souhaitez avoir une adresse IP spécifique ou vous limiter à un sous-ensemble d'adresses IP, exécutez la CLI Set-PreferredHostIPsInStorageExportPolicy.
** Si vous disposez de plusieurs chemins de données (LIF) dans les SVM, SnapCenter choisit le chemin de données approprié (LIF) pour monter le volume cloné NFS. Cependant, si vous souhaitez spécifier un chemin de données spécifique (LIF), vous devez exécuter l'interface de ligne de commande Set-SvmPreferredDataPath. Les informations concernant les paramètres pouvant être utilisés avec la commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guide de référence des commandes du logiciel SnapCenter"^] .


* Configurez SnapMirror et SnapVault si vous souhaitez une réplication de sauvegarde.
* Assurez-vous que le port 9090 n’est utilisé par aucune autre application sur l’hôte.
+
Le port 9090 doit être réservé à l'utilisation par les plug-ins pris en charge par NetApp en plus des autres ports requis par SnapCenter.


