---
permalink: protect-nsp/set_up_credentials_for_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter utilise des informations d’identification pour authentifier les utilisateurs pour les opérations SnapCenter .  Vous devez créer des informations d’identification pour l’installation des plug-ins SnapCenter et des informations d’identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données ou les systèmes de fichiers Windows. 
---
= Configurer les informations d'identification pour les plug-ins pris en charge par NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilise des informations d’identification pour authentifier les utilisateurs pour les opérations SnapCenter .  Vous devez créer des informations d’identification pour l’installation des plug-ins SnapCenter et des informations d’identification supplémentaires pour effectuer des opérations de protection des données sur les bases de données ou les systèmes de fichiers Windows.

.Avant de commencer
* Hôtes Linux ou AIX
+
Vous devez configurer les informations d’identification pour l’installation de plug-ins sur des hôtes Linux ou AIX.

+
Vous devez configurer les informations d'identification pour l'utilisateur root ou pour un utilisateur non root disposant de privilèges sudo pour installer et démarrer le processus du plug-in.

+
|===


| *Meilleure pratique :* bien que vous soyez autorisé à créer des informations d’identification pour Linux après avoir déployé des hôtes et installé des plug-ins, la meilleure pratique consiste à créer des informations d’identification après avoir ajouté des SVM, avant de déployer des hôtes et d’installer des plug-ins. 
|===
* hôtes Windows
+
Vous devez configurer les informations d’identification Windows avant d’installer les plug-ins.

+
Vous devez configurer les informations d’identification avec des privilèges d’administrateur, y compris des droits d’administrateur sur l’hôte distant.

* Applications plug-ins prises en charge par NetApp
+
Le plug-in utilise les informations d’identification sélectionnées ou créées lors de l’ajout d’une ressource.  Si une ressource ne nécessite pas d'informations d'identification pendant les opérations de protection des données, vous pouvez définir les informations d'identification sur *Aucune*.



.À propos de cette tâche
Si vous configurez des informations d'identification pour des groupes de ressources individuels et que le nom d'utilisateur ne dispose pas de privilèges d'administrateur complets, vous devez attribuer au moins les privilèges de groupe de ressources et de sauvegarde au nom d'utilisateur.

.Étapes
. Dans le volet de navigation de gauche, cliquez sur *Paramètres*.
. Dans la page Paramètres, cliquez sur *Informations d'identification*.
. Cliquez sur *Nouveau*.
. Dans la page *Informations d'identification*, spécifiez les informations requises pour la configuration des informations d'identification :
+
|===
| Pour ce domaine... | Fais ceci... 


 a| 
Nom d'identification
 a| 
Entrez un nom pour les informations d’identification.



 a| 
Nom d'utilisateur
 a| 
Saisissez le nom d’utilisateur et le mot de passe qui doivent être utilisés pour l’authentification.

** Administrateur de domaine ou tout membre du groupe d'administrateurs
+
Indiquez l'administrateur du domaine ou tout membre du groupe d'administrateurs du système sur lequel vous installez le plug-in SnapCenter . Les formats valides pour le champ Nom d'utilisateur sont :

+
*** _NetBIOS\Nom d'utilisateur_
*** _Domaine FQDN\Nom d'utilisateur_


** Administrateur local (pour les groupes de travail uniquement)
+
Pour les systèmes appartenant à un groupe de travail, spécifiez l'administrateur local intégré du système sur lequel vous installez le plug-in SnapCenter . Vous pouvez spécifier un compte utilisateur local appartenant au groupe des administrateurs locaux si ce compte dispose de privilèges élevés ou si la fonctionnalité de contrôle d'accès utilisateur est désactivée sur le système hôte.  Le format valide pour le champ Nom d'utilisateur est : _UserName_





 a| 
Mot de passe
 a| 
Entrez le mot de passe utilisé pour l'authentification.



 a| 
Type d'authentification
 a| 
Sélectionnez le type d’authentification que vous souhaitez utiliser.



 a| 
Utiliser les privilèges sudo
 a| 
Cochez la case *Utiliser les privilèges sudo* si vous créez des informations d’identification pour un utilisateur non root.


NOTE: Applicable uniquement aux utilisateurs Linux et AIX.

|===
. Cliquez sur *OK*.


Une fois que vous avez terminé de configurer les informations d’identification, vous souhaiterez peut-être attribuer la maintenance des informations d’identification à un utilisateur ou à un groupe d’utilisateurs sur la page Utilisateur et accès.
