---
permalink: get-started/concept_snapcenter_licenses.html 
sidebar: sidebar 
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery 
summary: SnapCenter nécessite plusieurs licences pour permettre les opérations de protection des données. Le type de licences SnapCenter que vous installez dépend de votre environnement de stockage et des fonctionnalités que vous souhaitez utiliser. 
---
= Licences requises par SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter nécessite plusieurs licences pour permettre la protection des données des applications, des bases de données, des systèmes de fichiers et des machines virtuelles. Le type de licences SnapCenter que vous installez dépend de votre environnement de stockage et des fonctionnalités que vous souhaitez utiliser.

|===
| Licence | Si nécessaire 


 a| 
Contrôleur standard SnapCenter
 a| 
Obligatoire pour FAS, AFF, ASA

La licence SnapCenter Standard est une licence basée sur un contrôleur et est incluse dans le cadre de NetApp ONTAP One.  Si vous disposez de la licence SnapManager Suite, vous bénéficiez également du droit de licence SnapCenter Standard.  Si vous souhaitez installer SnapCenter à titre d'essai avec le stockage FAS, AFF ou ASA , vous pouvez obtenir une licence d'évaluation NetApp ONTAP One en contactant le représentant commercial.

Pour plus d'informations sur les licences incluses avec NetApp ONTAP One, reportez-vous à https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licences incluses avec NetApp ONTAP One"] .


NOTE: SnapCenter est également proposé dans le cadre d'un pack de protection des données.  Si vous avez acheté l'A400 ou une version ultérieure, vous devez acheter le pack de protection des données.



 a| 
SnapMirror ou SnapVault
 a| 
ONTAP

Une licence SnapMirror ou SnapVault est requise si la réplication est activée dans SnapCenter.



 a| 
SnapRestore
 a| 
Nécessaire pour restaurer et vérifier les sauvegardes.

Sur les systèmes de stockage primaires

* Requis sur les systèmes de destination SnapVault pour effectuer une vérification à distance et restaurer à partir d'une sauvegarde.
* Requis sur les systèmes de destination SnapMirror pour effectuer une vérification à distance.




 a| 
FlexClone
 a| 
Nécessaire pour cloner des bases de données et des opérations de vérification.

Sur les systèmes de stockage primaires et secondaires

* Requis sur les systèmes de destination SnapVault pour créer des clones à partir d'une sauvegarde de coffre-fort secondaire.
* Requis sur les systèmes de destination SnapMirror pour créer des clones à partir d'une sauvegarde SnapMirror secondaire.




 a| 
Licences de protocole
 a| 
* Licence iSCSI ou FC pour les LUN
* Licence CIFS pour les actions SMB
* Licence NFS pour les VMDK de type NFS
* Licence iSCSI ou FC pour les VMDK de type VMFS


Requis sur les systèmes de destination SnapMirror pour diffuser des données si un volume source n'est pas disponible.



 a| 
Licences SnapCenter Standard (en option)
 a| 
Destinations secondaires


NOTE: Il est recommandé, mais pas obligatoire, d'ajouter des licences SnapCenter Standard aux destinations secondaires.  Si les licences SnapCenter Standard ne sont pas activées sur les destinations secondaires, vous ne pouvez pas utiliser SnapCenter pour sauvegarder les ressources sur la destination secondaire après avoir effectué une opération de basculement.  Cependant, une licence FlexClone est requise sur les destinations secondaires pour effectuer des opérations de clonage et de vérification.



 a| 
Licences de récupération de boîte aux lettres unique (SMBR)
 a| 
Si vous utilisez SnapCenter Plug-in pour Exchange pour gérer les bases de données Microsoft Exchange Server et Single Mailbox Recovery (SMBR), vous aurez besoin d'une licence supplémentaire pour SMBR qui doit être achetée séparément en fonction de la boîte aux lettres de l'utilisateur.

NetApp® Single Mailbox Recovery est arrivé en fin de disponibilité (EOA) le 12 mai 2023.  Pour plus d'informations, reportez-vous àlink:https://mysupport.netapp.com/info/communications/ECMLP2885729.html["CPC-00507"] .  NetApp continuera à prendre en charge les clients qui ont acheté la capacité, la maintenance et le support de la boîte aux lettres via les numéros de référence marketing introduits le 24 juin 2020, pendant toute la durée du droit de support.

NetApp Single Mailbox Recovery est un produit partenaire fourni par Ontrack.  Ontrack PowerControls offre des fonctionnalités similaires à celles de NetApp Single Mailbox Recovery.  Les clients peuvent se procurer de nouvelles licences logicielles Ontrack PowerControls et des renouvellements de maintenance et d'assistance Ontrack PowerControls auprès d'Ontrack (via licensingteam@ontrack.com) pour une récupération granulaire des boîtes aux lettres après la date EOA du 12 mai 2023.

|===

NOTE: Les licences SnapCenter Advanced et SnapCenter NAS File Services sont obsolètes et ne sont plus disponibles.  La licence standard et la licence basée sur la capacité ne sont plus requises pour Amazon FSx for NetApp ONTAP, ONTAP Select, Cloud Volumes ONTAP et Azure NetApp Files.

Vous devez installer une ou plusieurs licences SnapCenter .  Pour plus d'informations sur la façon d'ajouter des licences, voirlink:../install/concept_snapcenter_standard_controller_based_licenses.html["Ajouter des licences basées sur le contrôleur SnapCenter Standard"] .
