---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: Les informations d’identification utilisent différentes méthodes d’authentification selon l’application ou l’environnement.  Les informations d’identification authentifient les utilisateurs afin qu’ils puissent effectuer des opérations SnapCenter .  Vous devez créer un ensemble d’informations d’identification pour l’installation des plug-ins et un autre ensemble pour les opérations de protection des données. 
---
= Méthodes d'authentification pour les informations d'identification SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les informations d’identification utilisent différentes méthodes d’authentification selon l’application ou l’environnement.  Les informations d’identification authentifient les utilisateurs afin qu’ils puissent effectuer des opérations SnapCenter .  Vous devez créer un ensemble d’informations d’identification pour l’installation des plug-ins et un autre pour les opérations de protection des données.



== Authentification Windows

La méthode d’authentification Windows s’authentifie auprès d’Active Directory.  Pour l’authentification Windows, Active Directory est configuré en dehors de SnapCenter.  SnapCenter s'authentifie sans configuration supplémentaire.  Vous avez besoin d’informations d’identification Windows pour ajouter des hôtes, installer des packages de plug-ins et planifier des tâches.



== Authentification de domaine non fiable

SnapCenter permet aux utilisateurs et aux groupes appartenant à des domaines non approuvés de créer des informations d’identification Windows.  Pour que l'authentification réussisse, vous devez enregistrer les domaines non approuvés auprès de SnapCenter.



== Authentification du groupe de travail local

SnapCenter permet la création d'informations d'identification Windows avec des utilisateurs et des groupes de travail locaux.  L'authentification Windows pour les utilisateurs et les groupes de travail locaux ne se produit pas lors de la création des informations d'identification Windows, mais est différée jusqu'à ce que l'enregistrement de l'hôte et d'autres opérations de l'hôte soient effectués.



== Authentification SQL Server

La méthode d’authentification SQL s’authentifie auprès d’une instance SQL Server.  Cela signifie qu'une instance SQL Server doit être découverte dans SnapCenter.  Par conséquent, avant d’ajouter des informations d’identification SQL, vous devez ajouter un hôte, installer des packages de plug-in et actualiser les ressources.  Vous avez besoin de l’authentification SQL Server pour effectuer des opérations telles que la planification sur SQL Server ou la découverte de ressources.



== Authentification Linux

La méthode d’authentification Linux s’authentifie auprès d’un hôte Linux.  Vous avez besoin d’une authentification Linux lors de l’étape initiale d’ajout de l’hôte Linux et d’installation du package de plug-ins SnapCenter pour Linux à distance à partir de l’interface graphique SnapCenter .



== Authentification AIX

La méthode d’authentification AIX s’authentifie auprès d’un hôte AIX.  Vous avez besoin d’une authentification AIX lors de l’étape initiale d’ajout de l’hôte AIX et d’installation du package de plug-ins SnapCenter pour AIX à distance à partir de l’interface graphique SnapCenter .



== Authentification de la base de données Oracle

La méthode d’authentification de base de données Oracle s’authentifie auprès d’une base de données Oracle.  Vous avez besoin d'une authentification de base de données Oracle pour effectuer des opérations sur la base de données Oracle si l'authentification du système d'exploitation (OS) est désactivée sur l'hôte de la base de données.  Par conséquent, avant d'ajouter des informations d'identification de base de données Oracle, vous devez créer un utilisateur Oracle dans la base de données Oracle avec des privilèges sysdba.



== Authentification Oracle ASM

La méthode d'authentification Oracle ASM s'authentifie auprès d'une instance Oracle Automatic Storage Management (ASM).  L'authentification Oracle ASM est requise si vous devez accéder à une instance Oracle ASM et que l'authentification du système d'exploitation est désactivée sur l'hôte de la base de données.  Avant d’ajouter des informations d’identification Oracle ASM, créez un utilisateur Oracle avec des privilèges système dans l’instance ASM.



== Authentification du catalogue RMAN

La méthode d'authentification du catalogue RMAN s'authentifie auprès de la base de données du catalogue Oracle Recovery Manager (RMAN).  Si vous avez configuré un mécanisme de catalogue externe et enregistré votre base de données dans la base de données du catalogue, vous devez ajouter l'authentification du catalogue RMAN.
