---
permalink: protect-mysql/create-a-storage-system-connection-and-a-run-as-account-using-powershell-cmdlets-for-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: 'Vous devez créer une connexion à une machine virtuelle de stockage (SVM) et des informations d’identification avant d’utiliser les applets de commande PowerShell pour sauvegarder, restaurer ou cloner des bases de données MySQL.' 
---
= Créer une connexion au système de stockage et des informations d'identification à l'aide des applets de commande PowerShell pour MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer une connexion à une machine virtuelle de stockage (SVM) et des informations d’identification avant d’utiliser les applets de commande PowerShell pour sauvegarder, restaurer ou cloner des bases de données MySQL.

.Avant de commencer
* Vous devez avoir préparé l’environnement PowerShell pour exécuter les applets de commande PowerShell.
* Vous devez disposer des autorisations requises dans le rôle d’administrateur d’infrastructure pour créer des connexions de stockage.
* Vous devez vous assurer que les installations de plug-ins ne sont pas en cours.
+
Les installations de plug-ins hôtes ne doivent pas être en cours lors de l'ajout d'une connexion au système de stockage, car le cache hôte peut ne pas être mis à jour et l'état des bases de données peut s'afficher dans l'interface graphique SnapCenter comme « Non disponible pour la sauvegarde » ou « Pas sur le stockage NetApp ».

* Les noms des systèmes de stockage doivent être uniques.
+
SnapCenter ne prend pas en charge plusieurs systèmes de stockage portant le même nom sur différents clusters.  Chaque système de stockage pris en charge par SnapCenter doit avoir un nom unique et une adresse IP LIF de données unique.



.Étapes
. Lancez une session de connexion PowerShell Core à l’aide de l’applet de commande Open-SmConnection.
+
[listing]
----
PS C:\> Open-SmConnection
----
. Créez une nouvelle connexion au système de stockage à l’aide de l’applet de commande Add-SmStorageConnection.
+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Créez de nouvelles informations d’identification à l’aide de l’applet de commande Add-SmCredential.
+
Cet exemple montre comment créer une nouvelle information d'identification nommée FinanceAdmin avec les informations d'identification Windows :

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
. Ajoutez l’hôte de communication MySQL au serveur SnapCenter .
+
[listing]
----
PS C:> Add-SmHost -HostName 10.232.204.61 -OSType Windows -RunAsName FinanceAdmin -PluginCode mysql
----
. Installez le package et le plug-in SnapCenter pour MySQL sur l'hôte.
+
Pour Linux :

+
[listing]
----
PS C:> Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode mysql
----
+
Pour Windows :

+
[listing]
----
Install-SmHostPackage -HostNames 10.232.204.61 -ApplicationCode mysql -FilesystemCode scw -RunAsName FinanceAdmin
----
. Définissez le chemin vers SQLLIB.
+
Pour Windows, le plug-in MySQL utilisera le chemin par défaut pour le dossier SQLLIB : « C:\Program Files\IBM\SQLLIB\BIN »

+
Si vous souhaitez remplacer le chemin par défaut, utilisez la commande suivante.

+
[listing]
----
PS C:> Set-SmConfigSettings -Plugin -HostName 10.232.204.61 -PluginCode
MySQL -configSettings @{“MySQL_SQLLIB_CMD” = “<custom_path>\IBM\SQLLIB\BIN”}

----


Les informations concernant les paramètres pouvant être utilisés avec l'applet de commande et leurs descriptions peuvent être obtenues en exécutant _Get-Help command_name_. Alternativement, vous pouvez également vous référer à la https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guide de référence de l'applet de commande du logiciel SnapCenter"^] .
