---
permalink: protect-mysql/types-of-restore-performed-for-auto-discovered-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for mysql 
summary: 'SnapCenter prend en charge les types de restauration SnapRestore basés sur le volume (VBSR), SnapRestore à fichier unique et de connexion et de copie pour les bases de données MySQL découvertes automatiquement.' 
---
= Types d'opérations de restauration pour MySQL découvert automatiquement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le plug-in SnapCenter pour MySQL prend en charge les types de restauration SnapRestore à fichier unique et de connexion et de copie pour les bases de données MySQL découvertes automatiquement.



== Single File SnapRestore est effectué dans les environnements NFS pour les scénarios suivants :

* Si seule l'option *Ressource complète* est sélectionnée
* Lorsque la sauvegarde sélectionnée provient d'un emplacement secondaire SnapMirror ou SnapVault et que l'option *Ressource complète* est sélectionnée




== Single File SnapRestore est exécuté dans les environnements SAN pour les scénarios suivants :

* Si seule l'option *Ressource complète* est sélectionnée
* Lorsque la sauvegarde est sélectionnée à partir d'un emplacement secondaire SnapMirror ou SnapVault et que l'option *Ressource complète* est sélectionnée

